### PR TITLE
docs: Remove Containerfile and containerignore

### PR DESCRIPTION
**Pull request by Foxboron**
These where moved to buildah but because they are useful for podman and
the other tooling they are moved back into the common project.

Partially reverts a9e66ec72b55c7d2a854adca9670f8a336f95fc5

Signed-off-by: Morten Linderud <morten@linderud.pw>

/kind documentation

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@Foxboron thanks for the PR!  I see the commit that moved some of these files to [Buildah](https://github.com/containers/common/commit/fc7cb9cf92020cc2f58683bba693f70332a9dca3), but I'm not seeing the PR where they moved back and I don't see the files that atm.

Am I looking with end of day reviewing eyeballs?

**Comment by Foxboron** [comment]
I opened a PR here :)
https://github.com/containers/common/pull/905

**Comment by TomSweeneyRedHat** [comment]
@Foxboron missed that PR, thx for the pointer.

@edsantiago the smoke test failure looks like it's related to the removal of these .5.md files and a safety test failing due to that.  Is there some other file that needs to be tweaked?  I looked, but didn't find it...

**Comment by TomSweeneyRedHat** [comment]
Do not merge prior to https://github.com/containers/common/pull/905 being merged and potentially a new version of c/common vendored into Buildah.

**Comment by TomSweeneyRedHat** [comment]
@Foxboron FYI, https://github.com/containers/buildah/pull/3745 is making changes to Containerfile.5.md that should be picked up.

**Comment by edsantiago** [comment]
@TomSweeneyRedHat if there are no more `.5` files, you need to remove this line https://github.com/containers/buildah/blob/7bcca21a282dc42099fcc8883da386a000273d4b/docs/Makefile#L30

**Comment by rhatdan** [comment]
Let's hold this off until after 4.0 is released.

**Comment by rhatdan** [comment]
@Foxboron Needs a rebase.

**Comment by Foxboron** [comment]
Rebased :) Sorry for the delay

**Comment by rhatdan** [comment]
@Foxboron Could you fix this PR since the containers/common PR was merged.

**Comment by Foxboron** [comment]
@rhatdan I assume you wanted a rebase? If there is anything else missing please do tell :)

**Comment by rhatdan** [comment]
You also have to fix the makefile to not install those man pages.

**Comment by Foxboron** [comment]
I forgot! Removed the lines relevant for section 5 manpages from the Makefiles :)

**Pull request merged**
