### PR TITLE
Refactor code in package imagebuildah

### PR DESCRIPTION
**Pull request by WanLinghao**
The file imagebuildah/build.go is too long to read, we should refactor it

### CODE REVIEW

**Comment by WanLinghao** [comment]
bot, test pull request

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
Thanks @WanLinghao 
You need to sign your commit.

git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
bot, test pull request

**Comment by WanLinghao** [comment]
@rhatdan Done

**Comment by rhatdan** [comment]
LGTM
@giuseppe @nalind @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but I really want a head nod from @nalnd on this one.

**Comment by rhatdan** [comment]
@WanLinghao Needs a rebase.

**Comment by WanLinghao** [comment]
@rhatdan  Rebase done

**Comment by TomSweeneyRedHat** [comment]
@WanLinghao another rebase is needed.  We're about to ship a new release today/tomorrow.  I think I'd like to hold this one until after the release so if you want to wait until early next week to rebase that would work.

**Comment by WanLinghao** [comment]
@TomSweeneyRedHat  Hi, could I continue this now?

**Comment by rhatdan** [comment]
@WanLinghao Still needs rebase, then we can merge.  Not sure what you mean "Can I continue this now?"

**Comment by TomSweeneyRedHat** [comment]
@WanLinghao yes, please feel free to continue now.  @rhatdan I'd asked @WanLinghao to hold off on the work until after 1.8.4 landed.

**Comment by WanLinghao** [comment]
@TomSweeneyRedHat @rhatdan  Hi, rebase done, PTAL

**Comment by rhatdan** [comment]
Thanks @WanLinghao 
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
LGTM
@WanLinghao TYVM for not only the changes, but for holding them back a bit when requested and the rebase work that resulted.  Very appreciated!

**Comment by TomSweeneyRedHat** [comment]
I've restarted the failing Homu jobs.  They issues don't look at all related to this change.

**Comment by WanLinghao** [comment]
@TomSweeneyRedHat It seems it's still failed

**Comment by TomSweeneyRedHat** [comment]
@WanLinghao can you try repushing your PR?  Sometimes homu goes crazy and the best way to make it happy is to repush.  Sorry!

**Comment by rhatdan** [comment]
@jlebon Any chance you could kick this?

@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by jlebon** [comment]
Yup, the PAPR tests ran and passed already on the Homu merge commit (hover over the yellow dot). Don't mind the "An internal error occurred." here. That status is for the PR itself, which wasn't retested since the infra flakes.

**Comment by WanLinghao** [comment]
What should I do now... I am confused

**Comment by rhatdan** [comment]
@WanLinghao I don't know.  I really do not understand what is going on here. Seems that only one test suite in Travis is continuously failing.  I have kicked it off one more time.

**Comment by TomSweeneyRedHat** [comment]
@jlebon any thoughts on what we can do to make homu/Red Hat CI happy with this PR?

**Comment by jlebon** [comment]
> @jlebon any thoughts on what we can do to make homu/Red Hat CI happy with this PR?

The comment from `rh-atomic-bot` higher up points to Travis CI being unhappy. The PAPR tests themselves passed (see https://github.com/containers/buildah/pull/1659#issuecomment-506860764).

To retest on the PR itself to get rid of the "An internal error occurred.", you can comment `bot, retest this please`, but note this is independent from the test Homu does on merge. If you want to retry the merge itself and have Travis rerun, you can do `@rh-atomic-bot retry`.

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot retry

**Comment by TomSweeneyRedHat** [comment]
WOOT!  Finally merged!  TYVM for the work @WanLinghao  and TYVM @jlebon for the CI help.

**Pull request closed without merging**
