### PR TITLE
docs: clarify the "triples" format

### PR DESCRIPTION
**Pull request by markstos**
> /kind documentation

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@markstos Thanks for the PR, but could you sign it.

git commit -a --amend -s
git push --force

**Comment by markstos** [comment]
@rhatdan I don't need the credit and didn't even check out the tree. This was a quick contribution through the Github website and I don't expect to contribute again soon. 

Could you just apply the simple diff locally and close this?

https://patch-diff.githubusercontent.com/raw/containers/buildah/pull/2420.diff

**Comment by TomSweeneyRedHat** [comment]
Thanks @markstos I'll throw a PR together.

**Comment by TomSweeneyRedHat** [comment]
Closing in favor of #2421

**Pull request closed without merging**
