### PR TITLE
intermediate-images inherit-label test: make it debuggable

### PR DESCRIPTION
**Pull request by edsantiago**
Test is currently very hard to debug on failure. Fix that
by adding unique test descriptors and a little whitespace.

Also, fix a broken/NOP test (copypaste artifact)

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Review by kolyshkin — COMMENTED** [review]
tests/helpers.bash says `expect_output` is deprecated by `assert`. Now, I'm sure it does not make sense to convert everything to `assert`, but maybe use a new version when you touch the code.

**Review by kolyshkin — COMMENTED** [review]
LGTM overall.

**Comment by edsantiago** [comment]
@kolyshkin point taken, but I was going for ease of review to get this in ASAP (for your #4832, actually, in case it could be helpful in tracking down that weird CI failure).

**Pull request merged**
