### PR TITLE
Fix (make vendor)

### PR DESCRIPTION
**Pull request by mtrmac**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
`(export a=b command args)` does not run `(command args)` with `a=b`, it sets `$a` to `b`, and marks variables `$a` `$command` `$args` as exported, i.e. `(command args)` is not run.

So, before #2287 we were not actually running `(go mod tidy)`, and now we are not running `(go mod vendor)`.

Fix that, and re-vendor.

Notably, vendored c/image and several other dependencies currently don’t correspond to `go.mod`.

#### How to verify it
Manually run (go mod …) and compare that with the results of running (make vendor)

#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?
None

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mtrmac thanks!
Can you sign the PR and repush please.
And Yikes, we really needed that tidy!

**Comment by mtrmac** [comment]
The three test failures in https://cirrus-ci.com/task/4722459664449536 are all on merge commits, including a two-months-old d654a795 which passed in the previous run. I’m not sure what is going on.

**Comment by rhatdan** [comment]
Is there a validate EPOCH we need to update?

**Comment by rhatdan** [comment]
tests/validate/git-validation.sh

**Comment by mtrmac** [comment]
> Is there a validate EPOCH we need to update?

That could hide it, sure, but really, what is going on here?

All the three failing commits succeed in https://cirrus-ci.com/task/5357058849505280?command=validate_test (the previous PR), and fail here.

The git-validation version is the same. The git RPM version is the same.

**Comment by rhatdan** [comment]
Newer go compiler?

**Comment by mtrmac** [comment]
Both 1.12.17-1.fc30 .

**Comment by mtrmac** [comment]
OK, I’m completely out of ideas. For now, as a desperate last guess, I’m dropping the `make -C test/tools vendor` commit, which AFAICS should make absolutely no difference.

**Comment by mtrmac** [comment]
Still fails, but now with two different merge commits.

I’m re-adding the tools commit, but otherwise giving up for today.

**Pull request closed without merging**
