### PR TITLE
fix /etc/hosts and resolv.conf setup with network configs

### PR DESCRIPTION
**Pull request by Luap99**
#### What type of PR is this?

> /kind api-change

 /kind bug

> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
Fixes problems with incorrectly configured hosts and resolv.conf files for containers.
```

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM , needs rebase though.

**Comment by Luap99** [comment]
> LGTM , needs rebase though.

No it doesn't, the only thing merged sine my changes is https://github.com/containers/buildah/pull/5410 which doesn't cause any conflicts.

**Comment by flouthoc** [comment]
> > LGTM , needs rebase though.
> 
> No it doesn't, the only thing merged sine my changes is #5410 which doesn't cause any conflicts.

@Luap99 Ah its the github UI then, just asking for a rebase with `main` branch since your branch is not in sync with `main`.
I have no clue why does it asks for a rebase when it has no conflicts :smile: 

Anyways PR LGTM

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by Luap99** [comment]
@mheon @baude PTAL

**Comment by mheon** [comment]
LGTM

**Pull request merged**
