### PR TITLE
show program's output when executing `podman run`

### PR DESCRIPTION
**Pull request by madorn**
add -t to `podman run` so when user executes this step, they get excited when they see the output of `runecho.sh`.

### CODE REVIEW

**Comment by rhatdan** [comment]
@madorn Could you sign your PR

git commit -a -s --amend
git push --force

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
Oh very nice catch and fix, TYVM @madorn !

**Comment by TomSweeneyRedHat** [comment]
oops, forgot the most important part.
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
