### PR TITLE
vendor github.com/containers/image@v2.0.1

### PR DESCRIPTION
**Pull request by vrothberg**
* progress bar: use spinners for unknown blob sizes
* use 'containers_image_ostree' as build tag
* ostree: default is no OStree support
* Add "Env" to ImageInspectInfo
* config.go: improve debug message
* config.go: log where credentials come from
* Fix typo in docs/containers-registries.conf.5.md
* docker: delete: support all MIME types
* Try harder in storageImageDestination.TryReusingBlob
* docker: allow deleting OCI images
* ostree: improve error message

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM although test failures look real.

**Comment by vrothberg** [comment]
Need to fix the ostree tag :) Working on it now.

**Comment by rhatdan** [comment]
@vrothberg Needs a rebase.

**Comment by vrothberg** [comment]
@rhatdan, rebased :heavy_check_mark:

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
