### PR TITLE
Fix documentation of the --format option of buildah push

### PR DESCRIPTION
**Pull request by mtrmac**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

The `push --format` option affects all transports; and without `--format`, we try several manifest formats.

#### How to verify it

Manual inspection.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
/approve
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
@vrothberg @giuseppe @saschagrunert PTAL

**Review by vrothberg — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
