### PR TITLE
Overlay mounts are supported in rootless mode

### PR DESCRIPTION
**Pull request by awerlang**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Conform the docs to the available feature.

#### How to verify it

```
buildah from -v ~/test:/test:O scratch
```

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Nice catch
LGTM

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @ashley-cui @QiWang19 @nalind @vrothberg PTAL

**Comment by QiWang19** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
I'm going to try and rekick the CI.  The failed test is not related to this change.

**Comment by TomSweeneyRedHat** [comment]
can't get the test to restart, going to place my trust in bors (oh boy)
bors r+

**Comment by TomSweeneyRedHat** [comment]
bors retry

**Pull request merged**
