### PR TITLE
pkg/parse: expose public `CleanCacheMount` API

### PR DESCRIPTION
**Pull request by flouthoc**
PR https://github.com/containers/buildah/pull/4490 added a new API `CleanCacheMount` which allows cleaning the buildcache and cache generated on host by --mount=type=cache just like buildkit's prune command.

Following API is needed to tools like podman can utilize this and integrate it to the commands like `podman system reset`

[NO NEW TESTS NEEDED]
[NO TESTS NEEDED]
Test already added here: https://github.com/containers/buildah/pull/4490

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
pkg/parse: expose public `CleanCacheMount` API
```

### CODE REVIEW

**Comment by flouthoc** [comment]
CI is blocked becuase of https://github.com/containers/buildah/issues/4551

**Comment by vrothberg** [comment]
> CI is blocked becuase of #4551

If CI is using `ubuntu:latest` that should be fixed IMO.  Images should be stable (and under our control) to avoid that 3rd parties can nuke our CI - even by accident.

**Comment by flouthoc** [comment]
Yes I am wondering if we even need `ubuntu` for this probably `alpine` or `scratch` should work for the test https://github.com/containers/buildah/pull/4552

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
