### PR TITLE
Fix transition test to work with latest selinux policy

### PR DESCRIPTION
**Pull request by rhatdan**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

[CI:NEXT]

### CODE REVIEW

**Comment by rhatdan** [comment]
This PR needs an updated container-selinux 2.216.0 PR.
https://github.com/containers/container-selinux/pull/250

**Comment by lsm5** [comment]
> This PR needs an updated container-selinux 2.216.0 PR. [containers/container-selinux#250](https://github.com/containers/container-selinux/pull/250)

once that merges, we should use the `[CI:NEXT]` keyword so packages from `rhcontainerbot/podman-next` will be fetched instead of the ones in the image.

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/buildah/pull/4772

**Comment by rhatdan** [comment]
Needs https://github.com/containers/container-selinux/releases/tag/v2.216.0

**Comment by lsm5** [comment]
@cevich is https://github.com/containers/podman/pull/18439#issuecomment-1553473044 still valid here for [CI:NEXT] or have things changed?

**Comment by lsm5** [comment]
> @cevich is [containers/podman#18439 (comment)](https://github.com/containers/podman/pull/18439#issuecomment-1553473044) still valid here for [CI:NEXT] or have things changed?

also, any reason the PR needs to be turned into draft?

**Comment by cevich** [comment]
> still valid here for [CI:NEXT] or have things changed?

Nope, that magic string isn't setup in buildah CI.  May I assume from the question, that it's needed here?

> also, any reason the PR needs to be turned into draft?

Yes, this is really important.  In podman CI, the `[CI:NEXT]` magic is setup to **fail** if the PR is not a draft.  Since draft's cannot be merged, this forces removal of the `[CI:NEXT]` magic and a re-run of the PR changes through regular CI to ensure it's also happy.

**Comment by lsm5** [comment]
> > still valid here for [CI:NEXT] or have things changed?
> 
> Nope, that magic string isn't setup in buildah CI. May I assume from the question, that it's needed here?

Yes, we just merged a change in container-selinux, a new version has been cut but updates-testing / stable updates will take a while, so we need to fetch from podman-next.

> 
> > also, any reason the PR needs to be turned into draft?
> 
> Yes, this is really important. In podman CI, the `[CI:NEXT]` magic is setup to **fail** if the PR is not a draft. Since draft's cannot be merged, this forces removal of the `[CI:NEXT]` magic and a re-run of the PR changes through regular CI to ensure it's also happy.

Got it, thanks

**Comment by cevich** [comment]
> Yes, we just...

Okay, I'll start work on porting that here from podman CI.

**Comment by cevich** [comment]
Opened https://github.com/containers/buildah/pull/4830

**Comment by TomSweeneyRedHat** [comment]
LGTM once the underlying dependencies are tended to.

**Comment by cevich** [comment]
> I am trying to move buildah to testing f37 and f38. But it is blowing up?

Can I assume this needs the new/recently build container-selinux packages?  If so, those are in `c20230517t144652z-f38f37d12` not the older `c20230426t140447z-f38f37d12`.  **BUT** those images [come with 60k lines of probably necessary baggage](https://github.com/containers/buildah/pull/4772#issuecomment-1535329903).

Otherwise, WRT [the Smoke Test failure](https://cirrus-ci.com/task/5099303245447168):

```
[+0013s] ./tests/tools/build/golangci-lint run --deadline=20m --color=always -j1
[+0200s] make: *** [Makefile:198: lint] Killed
```

Those can be a major PITA to debug :angry: In the distant past, I've seen that failure-mode caused by broken golangci-lint plugins and/or not enough memory on the system.  I don't _think_ the later is the problem here since `.cirrus.yml` says:

```yaml
    gce_instance:
        memory: "12Gb"
```

But maybe that's whats happening?  Though it _could_ also easily be another flavor of the golang 1.20 based panic I ran into in #4772.  In that PR it was more obvious, with [a giant PANIC message and traceback](https://github.com/containers/buildah/pull/4772#issuecomment-1533155021).

Hmmm...it's not a timeout problem.  Gosh...I'm not really sure what else to suggest :disappointed:

**Comment by rhatdan** [comment]
@cevich could you update to f37 and f38 in a separate PR, to what we should be using.  Then I can rebase this PR on the latest.

**Comment by cevich** [comment]
> could you update to f37 and f38 in a separate PR

I can...but it will immediately fail CI due to golang-ci shenanigans :cry:

**Comment by cevich** [comment]
@rhatdan okay #4863 is merged, so https://github.com/containers/buildah/pull/4772 only has the CI VM updates in it now if you want to rebase on it.

**Comment by cevich** [comment]
Note: In case it helps (i.e. w/ newer SELinux/related packages), I've started [building yet-another image update](https://github.com/containers/automation_images/pull/284).  They're required for podman CI, but I'm happy to coordinate tagging those images until this PR merges - meaning, they'd only be used in podman CI for the near-term.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan I'll be building a v1.31 this evening.  This looks to be the last PR we have pending.  If it's still not merged then, we can backport it to the 1.31.0 branch and get it into Podman RC2 next week.  @ashley-cui FYI

**Comment by rhatdan** [comment]
I don't think we should release buildah until it passes tests on f38. Unless you want to release buildah as a RC1.

**Comment by cevich** [comment]
> If it's still not merged then, we can backport it to the 1.31.0 branch and get it into Podman RC2 next week.

I hate to rush anybody.  So I'll just point out it would be "nice" to have the F38 CI VM update (included in this PR) pre-baked into the release branch.

It's not completely out of the question to backport the setup, esp. while the new branch is fresh.  But it will fairly quickly become a less and less desirable thing to do to a RHEL release branch.

My motivation here is trying to keep the Fedora->RHEL gap as small as possible, and F37 is quite far away from F38 WRT what's going into RHEL - at least that's my wishful thinking.  I could be wrong.

**Comment by rhatdan** [comment]
@cevich Once this completes and merges we can bump the VMs again.

**Pull request merged**
