### PR TITLE
Vendor in latest containers/(common, storage, image)

### PR DESCRIPTION
**Pull request by rhatdan**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @giuseppe @vrothberg @TomSweeneyRedHat @umohnani8 @flouthoc @lsm5 PTAL

**Comment by rhatdan** [comment]
@giuseppe @flouthoc PTAL This should bring in the zstd changes.

**Review by lsm5 — APPROVED** [review]
/lgtm
/hold

**Review by vrothberg — COMMENTED** [review]
/hold cancel
LGTM

**Pull request merged**
