### PR TITLE
Bump to v1.19.5

### PR DESCRIPTION
**Pull request by rhatdan**
Vendoring in the latest containers/common and containers/image for this release to match podman and store
shortnames in the cache directory.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by vrothberg** [comment]
> [+1707s] not ok 495 buildah version current in .spec file changelog

**Comment by rhatdan** [comment]
/hold
I think we should wait for https://github.com/containers/buildah/pull/2993
@TomSweeneyRedHat What about https://github.com/containers/buildah/pull/2978 Should we wait for this?

**Comment by rhatdan** [comment]
Ok there are bugs in both cases, so I will merge and we can get the fixes in a later release.

**Pull request merged**
