### PR TITLE
Revert "buildah image should not enable fuse-overlayfs for rootful mode"

### PR DESCRIPTION
**Pull request by flouthoc**
This reverts commit 2e25b156f74dfaeb3a44dcad663db1c041a803ef.

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

Closes: https://github.com/containers/buildah/issues/4715

### CODE REVIEW

**Comment by flouthoc** [comment]
@rhatdan Could you please take a look, it looks like last change broke lot of users.

**Comment by rhatdan** [comment]
Why, rootful users should not be defaulting to fuse-overlay?

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm

**Pull request merged**
