### PR TITLE
Vendor in containers/(common, storage, image)  and Codespell

### PR DESCRIPTION
**Pull request by rhatdan**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by saschagrunert** [comment]
I think this also requires https://github.com/containers/common/pull/1077

**Comment by flouthoc** [comment]
I am not at all sure yet but looks like something broke at `c/storage` **really bad**, i am not able to get basic tests passing on local with `v1.41.1-0.20220711135711-e0b3b886e994` of `c/storage`

**Comment by flouthoc** [comment]
This needes revendor of storage and common.

**Review by ashley-cui — COMMENTED** [review]
/lgtm

**Pull request merged**
