### PR TITLE
Add make depend, no build if there are no changes

### PR DESCRIPTION
**Pull request by afbjorklund**
Generate depend files for make, using a `go list` script.

### CODE REVIEW

**Comment by afbjorklund** [comment]
Signed.

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @umohnani8 @nalind @vrothberg PTAL

**Comment by vrothberg** [comment]
@afbjorklund, thanks for the PR! I don't think we need this optimization as `go-build` doesn't recompile when there are no changes. However, it does link the objects which is fairly cheap in comparison to compiler optimizations.

What I find very important is sensitivity to changes to the environment, which the proposed script in this PR is not, see below:

```bash
[valentin@nebuchadnezzar buildah]$ TAGS="123" make buildah
make: 'buildah' is up to date.
```

IMHO we should stick with the go tooling. You can try an incremental compilation by first cleaning the cache `rm -rf ~/.cache/go-build` and then perform two compilations. On my machine the time drops from around 14 seconds to around 2.5 seconds.

**Comment by afbjorklund** [comment]
Yeah, I suppose it makes for a bigger difference with big projects like minikube.

**Comment by afbjorklund** [comment]
For me it takes 4.5 seconds to build (with cache). Running make take 0.8 seconds*.
As a comparison it takes 0.5 seconds to list the depends, and 30 seconds without cache.

\* The main reason why make is so "slow", is because of RCS. Running `make -r` is 10x.
https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html

**Pull request closed without merging**
