### PR TITLE
import method ValidateVolumeOpts from libpod

### PR DESCRIPTION
**Pull request by QiWang19**
move ValidateVolumeOpts from libpod to buildah so libpod can vendor it in.

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM, although we should have a couple of tests for this to make sure we support the additional options.

**Comment by rhatdan** [comment]
@mheon @TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
Line 266 should probably not be a strings. Join() on all the options.

**Comment by QiWang19** [comment]
fix L266

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
