### PR TITLE
docs/tutorials: add tutorial on GitLab CI and caching

### LINKED ISSUE #2954: caching buildah images (base + created) using github actions/cache
I want to cache the buildah images so that they are not pulled every time using github actions/cache. Can you please help me understand what layers should be cached. I started with ~/var/lib/containers and /var/lib/containers but that did not help

```
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install oc tool
      run: mkdir /tmp/s2i/ && cd /tmp/s2i/ && curl -s https://api.github.com/repos/openshift/source-to-image/releases/latest | grep browser_download_url | grep linux-amd64 | cut -d '"' -f 4 | wget -qi - && tar xvf source-to-image*.gz && sudo mv s2i /usr/local/bin && rm -rf /tmp/s2i/
    - name: Login to quay.io using Buildah
      run: buildah login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io
    - name: Cache local Maven repository & buildah containers
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-buildah-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-buildah-
    - name: Build with Maven
      run: pwd && mvn -B clean install -DskipTests -f ./vertx-starter/pom.xml
    - name: Create the Dockerfile
      run: printf "FROM openjdk:8-slim\nARG JAR_FILE=target/*.jar\nRUN mkdir -p /deployments\nCOPY \${JAR_FILE} /deployments/app.jar\nRUN chown -R 1001:0 /deployments && chmod -R 0755 /deployments\nEXPOSE 8080 8443\n USER 1001\nENTRYPOINT [\"java\",\"-jar\",\"/deployments/app.jar\"]" > Dockerfile && cat Dockerfile
    - name: Create image using buildah
      run: buildah bud --layers --log-level debug --build-arg JAR_FILE="vertx-starter/target/app.jar" -t quay.io/himanshumps/vertx_demo .

```

### PR DESCRIPTION
**Pull request by penn5**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Explain how to do caching with CI

#### How to verify it
Follow tutorial and see if it works

#### Which issue(s) this PR fixes:

Fixes #2954

#### Special notes for your reviewer:
https://github.com/containers/buildah/issues/2954#issuecomment-1602390693

I had to apply the workaround in https://github.com/containers/container-selinux/issues/257 to my runner before this would work, so I've made it draft until that issue is resolved (it's probably a PEBCAK but I couldn't figure it out).

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
You have to sign your commits.
git commit -a --amend -s
git push --force

**Comment by penn5** [comment]
Will do. If I haven't by tomorrow, it's because I forgot, so please feel free to ping me!

**Comment by sanmai-NL** [comment]
Can you cover the relations with Containerfile instruction `RUN`, for example:

```Containerfile
RUN \
  --mount=type=cache,target=/var/cache/apk \
  apk add curl
```

And `podman-build`'s `--cache-from`, `--cache-to`?

**Comment by penn5** [comment]
This doesn't work. I'll open an issue to make a relevant feature in buildah.

**Pull request closed without merging**
