### PR TITLE
Bump to v1.6

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
I'll circle back with a follow up for the 1.7-dev after this gets posted.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@nalind @umohnani8 @vrothberg @giuseppe PTAL

**Comment by vrothberg** [comment]
Should we wait for c/storage v1.5 and vendor it here?

**Comment by rhatdan** [comment]
Actually yes we should get the user namespace fix.  Although I think there might be a fix required for buildah as well.

**Comment by TomSweeneyRedHat** [comment]
Repulled and pushed, now included the containers/storage update from this morning.  Fingers crossed that tests will pass.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
Homu isn't hip, retrying.

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
