### PR TITLE
fix build on 32bit arches

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

#### What type of PR is this?

> /kind other

#### What this PR does / why we need it:

fixes build on i686 and armv7hl

#### How to verify it

build without the change:
https://koji.fedoraproject.org/koji/taskinfo?taskID=50696956

scratch build with the change:
https://koji.fedoraproject.org/koji/taskinfo?taskID=50700329

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

None

```release-note
None
```

@nalind @TomSweeneyRedHat @rhatdan @ashcrow PTAL

### CODE REVIEW

**Comment by nalind** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@lsm5 if you want this to get into 1.15.2, can you spin up a pr for this on the release-1.15 branch please?

**Comment by nalind** [comment]
I spoke too soon over there.  The `pkg/rusage` package is new for 1.16, so there's no change needed on the 1.15 branch.

**Comment by lsm5** [comment]
> I spoke too soon over there. The `pkg/rusage` package is new for 1.16, so there's no change needed on the 1.15 branch.

ah yes, my bad, noticed this only now when I tried to cherry-pick on release-1.15 :D . Thanks.

**Comment by TomSweeneyRedHat** [comment]
OK, if by chance we backport rusage, we'll have to try and remember to backport this then too.

**Pull request merged**
