### PR TITLE
Run logout,manifest,source,unmount without userns

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/buildah/issues/5750

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@AdamWill PTAL
@nalind @giuseppe @lsm5 @TomSweeneyRedHat @flouthoc PTAL

**Comment by nalind** [comment]
I'm skeptical that this will work for `manifest push`.

**Comment by rhatdan** [comment]
@AdamWill could you see if buildah manifest push fails when not in the user namespace.  Since this follows the similar path to buildah push, most likely @nalind is correct.

**Comment by rhatdan** [comment]
```
$ ./bin/buildah manifest create quay.io/rhatdan/mymanifest
ff08b4da30d4c9474dcbebde7d61e03864f404541c44f5b2890798d7dbcae3ca
$ ./bin/buildah manifest push quay.io/rhatdan/mymanifest
Getting image list signatures
Copying 0 images generated from 0 images in list
Writing manifest list to image destination
Storing list signatures
```

This worked.

**Comment by nalind** [comment]
I'm doubtful that many of the relevant code paths were invoked there, since there was no image rootfs being pushed.

**Comment by AdamWill** [comment]
I'm not sure this is safe. login *used* to be in the list, but you took it out in https://github.com/containers/buildah/pull/3278 because of https://github.com/containers/buildah/issues/3259 .

If adding all these other things to the list means #3259 won't be an issue any more, great, but I'm worried maybe that's not the case :)

**Comment by rhatdan** [comment]
Well it looks like login, logout and manifest are likely to require UserNS then.

**Comment by AdamWill** [comment]
well the thinking behind my suggestion (make it an arg) was that what you can't do is "cross the streams", right? run some things in userns but some things outside it. but (at least as I understood it) it *should* in theory be okay to run only non-container-build-y commands, all outside userns. so my idea was to provide a somewhat-hidden way to do that, for this specific use case. if a command-line argument is too prominent it could be an env var or something, I guess.

**Comment by rhatdan** [comment]
I am fine with adding a hidden option --unshare and forcing the user to need to deal with it.

**Comment by rhatdan** [comment]
@nalind Thoughts?

**Comment by nalind** [comment]
Would it actually solve the problem?  Attempting to push layers without configuring a user namespace can very easily trip over permissions problems.

**Comment by AdamWill** [comment]
I can try and test my patch later, I didn't have time when I wrote it.

**Comment by TomSweeneyRedHat** [comment]
I'd be curious to hear @giuseppe 's opinion here.  The code change looks fine for what you want to do, I'll let others decide if that's an appropriate approach.  The hidden `--unshare` option is appealing.

Looks like a rebase is needed.

**Comment by giuseppe** [comment]
> I'd be curious to hear @giuseppe 's opinion here. The code change looks fine for what you want to do, I'll let others decide if that's an appropriate approach. The hidden `--unshare` option is appealing.

if we are accessing the storage as @nalind pointed out, it won't work without a user namespace since we need `CAP_DAC_OVERRIDE`  to access some of the files in an exploded rootfs

**Comment by AdamWill** [comment]
sorry for not testing this; after some extensive discussion we decided to try having the image uploader produce its own multi-arch manifest and push it with skopeo, to avoid the need for buildah and podman. I'm just finishing up that code now (adapted from https://pagure.io/koji-flatpak/blob/main/f/koji_flatpak/plugins/flatpak_builder_plugin.py#_586 ). If it works, we'll probably not care about this so much (though it'd still be nice if this could be addressed somehow in skopeo or buildah or podman so we could drop the manifest creation code from our tool).

**Comment by AdamWill** [comment]
Update - [we changed our uploader tool to build the manifest itself](https://pagure.io/cloud-image-uploader/pull-request/31), and it works, so we'll just go with that for now. Bit more code than we really want to carry/maintain, but hey. If there's ever a way to use podman or buildah or skopeo to construct the manifest that doesn't run through this userns stuff, we'll try it.

**Pull request closed without merging**
