### PR TITLE
chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

### PR DESCRIPTION
**Pull request by Juneezee**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The `github.com/ghodss/yaml` package is no longer actively maintained. There are numerous inquiries about the project's status on its issue tracker: https://github.com/ghodss/yaml/issues. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @Juneezee 
LGTM
/approve
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
@flouthoc @giuseppe @vrothberg @nalind @umohnani8 PTAL

**Review by vrothberg — COMMENTED** [review]
+2 −984 

I love commits removing code, thank you!

/lgtm
/hold

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
