### PR TITLE
Add gomod instructions and mailing list links

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Added instructions for how to use go mod to vendor in the contributing.md file.

Also added a few links to the Buildah mailing list.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
First Go Mod attempt, buyer beware!  @vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
Also fixes: #1704

**Comment by vrothberg** [comment]
Not sure how to restart Cirrus here (it flaked). Other than that, LGTM

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Was there a reason that my PR was not merged and you opened this one?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan cause I'm a dope and thought you'd updated libpod but not buildah?

**Comment by TomSweeneyRedHat** [comment]
I'll get you're merged in, then will revamp this one for the updated doc.

**Comment by TomSweeneyRedHat** [comment]
Rebased after #1701 went through and changed the title/description to remove the vendor component of the original.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat No problem, I just thought I missed something.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
