### PR TITLE
Cherry-pick   `run: fix check for host pid namespace`

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @vrothberg @TomSweeneyRedHat @saschagrunert @containers/podman-maintainers PTAL

**Comment by TomSweeneyRedHat** [comment]
Cherry picked from #2973

**Comment by TomSweeneyRedHat** [comment]
LGTM
As this is a cherry pick, I'm going to push this over the line.

**Pull request merged**
