### PR TITLE
Update container/storage to v1.15.4

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @vrothberg @saschagrunert @baude PTAL

**Comment by rhatdan** [comment]
@mbaldessari PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by mbaldessari** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Pull request closed without merging**
