### PR TITLE
Vendor latest containers/image

### PR DESCRIPTION
**Pull request by umohnani8**
Catches more errors when checking for login credentials.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
Do not merge yet, @mtrmac is opening two more cleanup PRs, will pick those once merged as well.

**Comment by umohnani8** [comment]
Should be ready to merge once tests are green.

**Comment by mtrmac** [comment]
Hopefully fixes #1079 .

**Comment by umohnani8** [comment]
@rhatdan @nalind @TomSweeneyRedHat any idea why the tests are getting a permission denied error?

**Comment by rhatdan** [comment]
@umohnani8 Rebase and repush.  I think the podman selinux issue caused this.

**Comment by umohnani8** [comment]
Rebased

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
