### PR TITLE
vendor github.com/containers/image@v3.0.0

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan @nalind @TomSweeneyRedHat we need this in before we can update libpod and CRI-O.

**Comment by vrothberg** [comment]
Travis is not behaving with all the network flakes... meh

**Comment by vrothberg** [comment]
Force pushed in hope to get some fresh Travis nodes.

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @nalind @giuseppe @QiWang19 @ashley-cui PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming travis is happy

**Comment by rhatdan** [comment]
@rh-atomic-bot r+
@TomSweeneyRedHat I think it is time for a new release. so we can get this merged into CRI-O and Podman.
@QiWang19 We need buildah login updated to use keyring and then we can make a full release.

**Comment by vrothberg** [comment]
> @QiWang19 We need buildah login updated to use keyring and then we can make a full release.

Note that we cannot update libpod and cri-o without this change. Anything we want for the next release would potentially delay the update unless we'd merge a non-release commit of buildah.

**Comment by vrothberg** [comment]
@rhatdan @TomSweeneyRedHat can we please force merge? The registries are flaky at the moment and I am restarting tests for around two hours now :-D

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, ack on the new release.  I'll bump to 1.10 unless I hear otherwise.

**Comment by TomSweeneyRedHat** [comment]
Just checked with @QiWang19 , the keyring PR is on the libpod side.  We should also add it to Buildah, but I wouldn't hold 1.10 for it.   https://github.com/containers/libpod/pull/3674

**Comment by TomSweeneyRedHat** [comment]
@vrothberg I've just started a retest on the one failing test.  In the mean time I'll go run some tests by hand.  Will merge by hand if still necessary afterwards.

**Comment by TomSweeneyRedHat** [comment]
Passes baseline tests.  Once the travis job wraps up, I'll merge.

**Comment by nalind** [comment]
@rh-atomic-bot retry

**Comment by TomSweeneyRedHat** [comment]
Finally past travis, off to build 1.10.

**Comment by QiWang19** [comment]
> Just checked with @QiWang19 , the keyring PR is on the libpod side. We should also add it to Buildah, but I wouldn't hold 1.10 for it. [containers/libpod#3674](https://github.com/containers/libpod/pull/3674)

sure. I just create this PR in buildah https://github.com/containers/buildah/pull/1758. we can get this in after 1.10

**Pull request closed without merging**
