### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**
#### What type of PR is this?

> /kind cleanup
> /kind feature

#### Does this PR introduce a user-facing change?

```release-note
Update nix pin with `make nixpkgs`
```

### CODE REVIEW

**Comment by rhatdan** [comment]
You forgot to sign you PR.

**Comment by hswong3i** [comment]
> You forgot to sign you PR.

Oops I signed but forgot to force push it :-P

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by TomSweeneyRedHat** [comment]
The fedora-33 storage_driver:overlay test hiccuped, it looks like a network flake.  I've restarted.  Otherwise
LGTM

**Pull request merged**
