### PR TITLE
Makefile: add missing files to $(SOURCES)

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Some source files were not included in $(SOURCES) in the top-level Makefile; add them.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by mtrmac — COMMENTED** [review]
Can this be automated further?

---

Comparing 
```make
log:
	echo $(SOURCES) | tr ' ' '\n'
```
with `find . -name '*.go' | grep -v vendor/ | sed 's,^\./,,'`:
```console
% diff -U0 0 1
--- 0	2024-04-30 21:40:26
+++ 1	2024-04-30 21:41:25
@@ -21,0 +22,34 @@
+cmd/buildah/addcopy.go
+cmd/buildah/build.go
+cmd/buildah/commit.go
+cmd/buildah/common.go
+cmd/buildah/common_test.go
+cmd/buildah/config.go
+cmd/buildah/containers.go
+cmd/buildah/containers_test.go
+cmd/buildah/dumpbolt.go
+cmd/buildah/from.go
+cmd/buildah/images.go
+cmd/buildah/images_test.go
+cmd/buildah/info.go
+cmd/buildah/inspect.go
+cmd/buildah/login.go
+cmd/buildah/logout.go
+cmd/buildah/main.go
+cmd/buildah/manifest.go
+cmd/buildah/mkcw.go
+cmd/buildah/mount.go
+cmd/buildah/passwd.go
+cmd/buildah/prune.go
+cmd/buildah/pull.go
+cmd/buildah/push.go
+cmd/buildah/rename.go
+cmd/buildah/rm.go
+cmd/buildah/rmi.go
+cmd/buildah/run.go
+cmd/buildah/source.go
+cmd/buildah/tag.go
+cmd/buildah/umount.go
+cmd/buildah/unshare.go
+cmd/buildah/unshare_unsupported.go
+cmd/buildah/version.go
@@ -94,0 +128 @@
+internal/types.go
@@ -100,0 +135 @@
+pkg/blobcache/blobcache.go
@@ -109,0 +145 @@
+pkg/dummy/dummy_test.go
@@ -112,0 +149,5 @@
+pkg/jail/jail.go
+pkg/jail/jail_int32.go
+pkg/jail/jail_int64.go
+pkg/jail/jail_test.go
+pkg/manifests/compat.go
@@ -126,0 +168 @@
+pkg/supplemented/compat.go
@@ -138,0 +181 @@
+pkg/volumes/volumes.go
@@ -152,0 +196,12 @@
+tests/conformance/conformance_test.go
+tests/conformance/selinux.go
+tests/conformance/selinux_unsupported.go
+tests/copy/copy.go
+tests/e2e/buildah_suite_test.go
+tests/e2e/inspect_test.go
+tests/imgtype/imgtype.go
+tests/serve/serve.go
+tests/testreport/testreport.go
+tests/testreport/types/types.go
+tests/tools/tools.go
+tests/tutorial/tutorial.go
```

**Comment by mtrmac** [comment]
… on a second look, the `cmd/buildah` parts, and maybe some of the others as well, are explicitly handled in Makefile rules.  And some of the subpackages are deprecated compatibility shims.

So maybe all of those omissions are intentional? I don’t know how I could tell.

**Comment by nalind** [comment]
The variable is more or less intended to be "library bits", since we use them to build multiple targets.  If we can do this as a validation step and avoid the cost of another shell invocation every time someone runs `make`, I'm for it.

**Comment by mtrmac** [comment]
Doing that in a validation step would be truly elegant.

**Comment by mtrmac** [comment]
/lgtm 

right now it’s a clear improvement anyway. Automation would be nice but I’ll leave the prioritization of that up to you.

**Pull request merged**
