### PR TITLE
run: ensure that stdio pipes are labeled correctly

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Label stdio pipes to ensure that processes we run can read through `/dev/stdin` and write through the `/dev/stdout` and `/dev/stderr` links.

#### How to verify it

New integration test!

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@nalind Could you change this to use https://github.com/opencontainers/selinux/releases/tag/v1.10.0 and just use label.Relabel().

**Comment by nalind** [comment]
> @nalind Could you change this to use https://github.com/opencontainers/selinux/releases/tag/v1.10.0 and just use label.Relabel().

Done.

**Pull request merged**
