### PR TITLE
imagebuildah: use the specified logger for logging preprocessing warnings

### LINKED ISSUE #3285: podman-remote build, with preprocessor: warnings go to server, not client
Another one of those cases where output is seen by podman server, but not the client.

In window 1:
```console
$ podman system service --timeout=0
```
In window 2:
```console
$ mkdir aaa
$ printf "FROM scratch\n\n#error\n" >aaa/Warn.in
$ printf "FROM scratch\n\n#include \"nonesuch\"\n" >aaa/Err.in
$ ./bin/podman-remote build -q -t foo -f Warn.in aaa
d6f2a9b367c5d6a3851225517e055430cf63042b310bbaa8373d96e92a70d4c4
$ ./bin/podman-remote build -q -t foo -f Err.in aaa
1339dc1a137603d0dcfe34c561c69323c4a41545220d15543e0716d0501f5963
```
Back to window 1:
```
WARN[0004] Ignoring <stdin>:3:2: error: #error

WARN[0006] Ignoring <stdin>:4:2: fatal error: nonesuch: No such file or directory
compilation terminated.
```
In all cases, exit status is 0. I'm not really OK with that, but that's what buildah does, so (shrug).

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Remove some redundancy in `preprocessContainerfileContents()`, have it search the $PATH for `cpp`, and have it log warning messages containing errors output by the preprocessor using the specified logrus logger.

#### How to verify it

We don't have much testing around redirecting our logged output 

#### Which issue(s) this PR fixes:

Fixes #3285

#### Special notes for your reviewer:

Apparently we [NO TESTS NEEDED] this functionality.

#### Does this PR introduce a user-facing change?
```
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @vrothberg @ashley-cui @umohnani8 @giuseppe PTAL

**Comment by giuseppe** [comment]
LGTM, tests restarted

**Comment by umohnani8** [comment]
LGTM, tests are unhappy though

**Comment by rhatdan** [comment]
@nalind Whats up with this PR?

**Comment by nalind** [comment]
Looks like it broke because the .spec file and define/types.go disagreed about the version.  Rebased.

**Pull request merged**
