### PR TITLE
docs: correct default authfile path

### PR DESCRIPTION
**Pull request by wulfgarpro**
/kind documentation

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
In other places I'm seeing `the default is /run/containers/$UID/auth.json` in the man pages.  I think you might have found something that needs fixing in several places.  @rhatdan thoughts?

**Comment by rhatdan** [comment]
```
grep "/run/containers/.*UID/auth.json" . -r
./docs/buildah-push.1.md:Path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json. If XDG_RUNTIME_DIR is not set, the default is /run/containers/$UID/auth.json. This file is created using `buildah login`.
./docs/buildah-commit.1.md:Path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json. If XDG_RUNTIME_DIR is not set, the default is /run/containers/$UID/auth.json. This file is created using `buildah login`.
./docs/buildah-from.1.md:  An image in a registry implementing the "Docker Registry HTTP API V2". By default, uses the authorization state in `$XDG_RUNTIME_DIR/containers/auth.json`, which is set using `(buildah login)`.  If XDG_RUNTIME_DIR is not set, the default is /run/containers/$UID/auth.json. If the authorization state is not found there, `$HOME/.docker/config.json` is checked, which is set using `(docker login)`.
./docs/buildah-from.1.md:Path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json. If XDG_RUNTIME_DIR is not set, the default is /run/containers/$UID/auth.json. This file is created using `buildah login`.
./docs/buildah-login.1.md:is not set, the default is /run/containers/$UID/auth.json.
./docs/buildah-logout.1.md:The default path used is **${XDG\_RUNTIME_DIR}/containers/auth.json**.  If XDG_RUNTIME_DIR is not set, the default is /run/containers/$UID/auth.json.
./docs/buildah-manifest-add.1.md:Path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json. If XDG_RUNTIME_DIR is not set, the default is /run/containers/$UID/auth.json. This file is created using `buildah login`.
./docs/buildah-pull.1.md:Path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json. If XDG_RUNTIME_DIR is not set, the default is /run/containers/$UID/auth.json. This file is created using `buildah login`.
./docs/buildah-build.1.md:Path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json. If XDG_RUNTIME_DIR is not set, the default is /run/containers/$UID/auth.json. This file is created using `buildah login`.
```

**Comment by wulfgarpro** [comment]
It's also still a contradiction for root where `buildah login XXX` puts `auth.json` at `/run/containers/0/auth.json`. I'll fix it up when I have a spare moment. Is this documentation generated?

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
Documentation (Markdown) is not generated, it is hand edited.

**Pull request closed without merging**
