### PR TITLE
update to latest libimage

### PR DESCRIPTION
**Pull request by vrothberg**
Update Buildah to the latest libimage.  Migrating Podman over to
libimage entailed a number of fixes and changes to libimage which
we need to account for in Buildah.

Most notably:

 * `(*Runtime).LookupImage()` now returns `storage.ErrImageUnknown`
   instead of `nil` in case no matching image is found.

 * `(*Runtime).LookupImage()` now does quite a bit more work finding
   a local image and will also look at the repotags (or digests) of
   all local images if needed.

 * The signature of `(*Runtime).RemoveImages()` was changed and now
   returns a slice of reports and errors.  The reports aggregate the
   data of a removed image which allows the function to be used by
   `podman image prune` which is also interested in the size of the
   removed data.  The slice of errors is also needed in Podman which
   needs to have a closer look at _all_ rmi errors in order to determine
   the appropriate exit code (Docker compat).

 * `libimage/types` has been removed.  Pull policies have been merged
   into already existing logic in `pkg/config`.

Please refer to containers/podman/pull/10147 for a more detailed
changelog.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan @nalind FYI

The Podman PR is closer to turn green, so I used the time waiting for CI to reflect the changes to libimage in Buildah as well.

**Comment by vrothberg** [comment]
@rhatdan, ready :checkered_flag:

**Comment by vrothberg** [comment]
@giuseppe PTAL

**Comment by baude** [comment]
lgtm

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
