### PR TITLE
CI VMs: bump f40 -> f41

### PR DESCRIPTION
**Pull request by edsantiago**
Images built in https://github.com/containers/automation_images/pull/392

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
We will need to update the linter golangci-lint needs to be > 1.60 to work on go 1.23 AFAICT

**Comment by Luap99** [comment]
try picking https://github.com/containers/buildah/pull/5821 in here

**Comment by edsantiago** [comment]
ulimits failing. Probably the same thing as  https://github.com/containers/podman/pull/24335 but not caught because we don't run buildah tests on rawhide.

**Comment by Luap99** [comment]
> ulimits failing. Probably the same thing as [containers/podman#24335](https://github.com/containers/podman/pull/24335) but not caught because we don't run buildah tests on rawhide.

The test seem to call podman to figure out the limit podman uses. IMO this sounds super wrong, buildah cannot depend on the host podman version and expect things to never change... added in https://github.com/containers/buildah/commit/79fb3c2135db1a9f962ad3ce42e97b20867e9fa6

What we could test on podman is that podman run/build use the same limits which make sense to me but testing in buildah with a unknown host binary cannot work

**Review by Luap99 — APPROVED** [review]
LGTM

**Pull request merged**
