### PR TITLE
Bump 1.8.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@nalind @rhatdan PTAL

**Comment by nalind** [comment]
LGTM
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
I don't think I can cut a release until this merges, let me know if I can prior.  Will try to spin one up before I leave in the morning.

**Comment by TomSweeneyRedHat** [comment]
Still sitting on homu and I've lost the battle with the eyelids.  Will try and tag 1.8.1 early in the morning.

**Pull request closed without merging**
