### PR TITLE
[wip] Added containerId to etc/hosts so as to resolve hostname. Closes #4446

### LINKED ISSUE #4446: Buildah intermediate container(Id) is not resolvable
### Discussed in https://github.com/containers/buildah/discussions/4424

<div type='discussions-op-text'>

<sup>Originally posted by **SaurabhAhuja1983** November 18, 2022</sup>
### Docker  is assigning ipaddress to each intermediate container and containerId is resolvable. But buildah intermediate containerId is not resolvable...

```
I used following Dockerfile
FROM <REPO-TAKE-ANY-JAVA-IMAGE>/java_jdk_8:latest
COPY MyClass.java .

RUN echo "---" ; cat /etc/hosts ; echo "Hostname: $(hostname)" ; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass
```

```
cat MyClass.java

import java.net.InetAddress;
import java.net.UnknownHostException;

public class MyClass {
    public static void main(String args[]) {
        try {
            InetAddress ia = InetAddress.getLocalHost();
            String str = ia.getHostAddress();
            String HOSTNAME = InetAddress.getLocalHost().getHostName();
            System.out.println("hostname: " + HOSTNAME);
         } catch (final UnknownHostException e) {
            throw new IllegalStateException("cannot get host name", e);
         }
    }
}

```

```
See the following output
`buildah build --no-cache .
STEP 1/4: FROM <.............................>/java_jdk_8:latest
STEP 2/4: RUN which java
/usr/bin/java
STEP 3/4: COPY MyClass.java .
STEP 4/4: RUN echo "---" ; cat /etc/hosts ; echo "Hostname: $(hostname)" ; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass
---
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.20.203.214	agent-79ccf9cbc-cvstd
10.20.203.214	host.containers.internal
Hostname: 43d4f3951829
---
Exception in thread "main" java.lang.IllegalStateException: cannot get host name
	at MyClass.main(MyClass.java:12)
Caused by: java.net.UnknownHostException: 43d4f3951829: 43d4f3951829: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1418)
	at MyClass.main(MyClass.java:7)
Caused by: java.net.UnknownHostException: 43d4f3951829: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:866)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1288)
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:815)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1413)
	... 1 more
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN echo "---" ; cat /etc/hosts ; echo "Hostname: $(hostname)" ; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass": exit status 1
`
```

However the same code works fine with docker build as i could see the intermediate containerId to IP mapping in /etc/hosts.

Not sure if buildah intermediate container is not assigned an ipaddress but it's blocking our java projects from getting build as we are transitioning from docker to buildah for building images.</div>

### PR DESCRIPTION
**Pull request by SaurabhAhuja1983**
#### What type of PR is this?
https://github.com/containers/buildah/issues/4446

> /kind api-change
 /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:
To fix java builds. Hostname (containerId) was unable to resolve.
#### How to verify it
Run the script provided here before and after the fix.
https://github.com/containers/buildah/issues/4446#issuecomment-1341036423
#### Which issue(s) this PR fixes:
https://github.com/containers/buildah/issues/4446

Fixes #4446

#### Special notes for your reviewer:
I would appreciate if you can provide any feedback, this is my first commit to buildah 
#### Does this PR introduce a user-facing change?
No

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@SaurabhAhuja1983 Thanks for the PR!  A couple of things.  First, how did the file in the ./vendor directory change?  If you did so "by hand", that won't work.   The next time common is vendored in, it will be overwritten.  That fix, if it is not already, needs to be made in the containers/common project and then vendored into Buildah.

Second, you did not add a test for this change.  I think that's OK, but it would be best to add one if possible.  If not, please add the tag `[NO NEW TESTS NEEDED]` to the description text. Otherwise, our CI will never let this in.

**Comment by SaurabhAhuja1983** [comment]
Thank You @TomSweeneyRedHat  for the feedback.
>>First, how did the file in the ./vendor directory change? If you did so "by hand", that won't work.
Yes, i did it by hand.
>> That fix, if it is not already, needs to be made in the containers/common project and then vendored into Buildah.

**Comment by SaurabhAhuja1983** [comment]
Created [#1491](https://github.com/containers/common/pull/1491) in containers/common for vendor specific code. 
Next steps
1. Waiting on Approval
2. vendorize the buildah code with latest containers/common
3. Update this PR to remove vendor specific code and add the tag [NO NEW TESTS NEEDED]

**Comment by Luap99** [comment]
The java reproducer works fine for me on the latest buildah version. I don't understand what this is trying to achieve? The hostname is already in /etc/hosts in the current version so the reporducer works fine.

**Comment by SaurabhAhuja1983** [comment]
@Luap99  Here is the output where i am able to reproduce the problem.
buildah bud .
STEP 1/3: FROM <REPO-PleaseReplaceThisPublicRepoURL>/java_jdk_8:latest
STEP 2/3: COPY MyClass.java .
STEP 3/3: RUN echo "---" ; cat /etc/hosts ; echo "---" ; echo "Hostname: $(hostname)" ; echo "---"; cat /run/.containerenv; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass
---
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.20.213.177	agent-588ddcb847-sjkjz
10.20.213.177	host.containers.internal
---
Hostname: 4040283c83cd
---

engine="buildah-1.30.0"
name="java_jdk_8-working-container"
id="57b069c91740bd47dd5554051fab67e5f4f4f3fb9a5cccfddbb07595b94da0d4"
image="028647500327.dkr.ecr.us-west-2.amazonaws.com/base/java_jdk_8:latest"
imageid="a1d7714d474de0ad161716633b95157faf150d0d3700a112eac8335770f7f2b3"
rootless=1
---
Exception in thread "main" java.lang.IllegalStateException: cannot get host name
	at MyClass.main(MyClass.java:12)
Caused by: java.net.UnknownHostException: 4040283c83cd: 4040283c83cd: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1432)
	at MyClass.main(MyClass.java:7)
Caused by: java.net.UnknownHostException: 4040283c83cd: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:867)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:815)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1291)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1427)
	... 1 more
subprocess exited with status 1
subprocess exited with status 1
Error: building at STEP "RUN echo "---" ; cat /etc/hosts ; echo "---" ; echo "Hostname: $(hostname)" ; echo "---"; cat /run/.containerenv; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass": exit status 1

**Comment by Luap99** [comment]
How do you run buildah? Is this rootless or as root? Do you have any containers.conf options changed, i.e. `base_hosts_file`?

The hostname is already added here: https://github.com/containers/buildah/blob/7468369c0bca6e335269a62824f47db3c49ee6f7/run_common.go#L1223-L1236

**Comment by SaurabhAhuja1983** [comment]
Yes.. it's rootless. I already printed the env. in the above comment. 
Posting it again here
cat /run/.containerenv
```
engine="buildah-1.30.0"
name="java_jdk_8-working-container"
id="57b069c91740bd47dd5554051fab67e5f4f4f3fb9a5cccfddbb07595b94da0d4"
image="028647500327.dkr.ecr.us-west-2.amazonaws.com/base/java_jdk_8:latest"
imageid="a1d7714d474de0ad161716633b95157faf150d0d3700a112eac8335770f7f2b3"
rootless=1
```

**Comment by SaurabhAhuja1983** [comment]
> You are running inside a container? 

Yes, i am running rootless buildah inside a container to build apps.

> Check the containers.conf file in that container, I assume you run with host networking. 

yes, i want to run with --network host option. I didn't find anything in containers.conf, i believe buildah uses  --network host by default if we don't specify anything.
containers.conf
```
---
cat /etc/containers/containers.conf
[engine]
cgroup_manager = "cgroupfs"
---
```

> It should work if you set --network private.

I tried both --network private and --network host but getting the same problem.
I need a way to resolve containerId hostname and it would require entry in /etc/hosts.
or is there a way to specify hostname instead of containerId as hostname for the intermediate containers.


> We currently do not add the hostname in /etc/hosts when host networking is used, the same goes for podman.

Alright. Any reason for that.

>I assume you could add the hostname with host networking but that requires you to get the actual host ip, reusing HostContainersInternalIP is not correct for this. And of course this must only happen when host network is set.

oks.. Got it. but i am thinking when intermediate build hostname is containerId shouldn't the mapping be 
HostContainersInternalIP to containerId (or hostname for the intermediate container)
Also, as i mentioned i am getting the same problem with both --network host/private
```

buildah --network host bud . 
buildah --network private bud .
```

**Comment by SaurabhAhuja1983** [comment]
@Luap99 did you get a chance to read my comments. I would really appreciate your guidance here. We don't want to maintain the patch on buildah in our codebase and it should help others as well who are trying to build gradle/jave applications and using rootless buildah in a container. 
As long as containerId which is actually hostname resolves, we are good to go and gradle builds should be happy.
We can talk about what's the right thing to do here.

**Comment by Luap99** [comment]
@SaurabhAhuja1983 Can you give https://github.com/containers/buildah/pull/4869 a try? I think this should solve your problem.

**Comment by SaurabhAhuja1983** [comment]
@Luap99 Thank you for submitting #4869 I will give it a try but i don't think it will solve the problem.

Yes, you are right, i am using buildah_isolation=chroot but i am also using --network=host.

I have used public openjdk image to reproduce the problem...  Please use the dockerfile and MyClass.java and run rootless buildah in a container, you should be able to reproduce the problem.

**1. As you can from the output below see the only problem is 
Hostname: 12cbcea00125 
but there is no corresponding entry in /etc/hosts so there is no way to resolve hostname.** 

```
zr@agent-588ddcb847-vggrd:/ziprecruiter/branches$ buildah build .
STEP 1/3: FROM gcr.io/google-appengine/openjdk:8
STEP 2/3: COPY MyClass.java .
STEP 3/3: RUN echo "---" ; cat /etc/hosts ; echo "---" ; echo "Hostname: $(hostname)" ; echo "---"; cat /run/.containerenv; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass
---
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.20.207.235	agent-588ddcb847-vggrd
10.20.207.235	host.containers.internal
---
Hostname: 12cbcea00125
---

engine="buildah-1.30.0"
name="openjdk-working-container"
id="12cbcea0012569529c3944d7c4fce35de6c23cbdd04975c03ac222bf3e4ffb65"
image="gcr.io/google-appengine/openjdk:8"
imageid="24b0b1cf77f0c22b1b72fd120769fb7659a3c22bc36acbd4146f19828d510e83"
rootless=1
---
Exception in thread "main" java.lang.IllegalStateException: cannot get host name
	at MyClass.main(MyClass.java:12)
Caused by: java.net.UnknownHostException: 12cbcea00125: 12cbcea00125: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
	at MyClass.main(MyClass.java:7)
Caused by: java.net.UnknownHostException: 12cbcea00125: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
	... 1 more
subprocess exited with status 1
subprocess exited with status 1
Error: building at STEP "RUN echo "---" ; cat /etc/hosts ; echo "---" ; echo "Hostname: $(hostname)" ; echo "---"; cat /run/.containerenv; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass": exit status 1
```
Dockerfile
```
zr@agent-588ddcb847-vggrd:/ziprecruiter/branches$ cat Dockerfile
FROM gcr.io/google-appengine/openjdk:8
COPY MyClass.java .
RUN echo "---" ; cat /etc/hosts ; echo "---" ; echo "Hostname: $(hostname)" ; echo "---"; cat /run/.containerenv; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass
```
MyClass.java
```
zr@agent-588ddcb847-vggrd:/ziprecruiter/branches$ cat MyClass.java
import java.net.InetAddress;
import java.net.UnknownHostException;

public class MyClass {
    public static void main(String args[]) {
        try {
            InetAddress ia = InetAddress.getLocalHost();
            String str = ia.getHostAddress();
            String HOSTNAME = InetAddress.getLocalHost().getHostName();
            System.out.println("hostname: " + HOSTNAME);
         } catch (final UnknownHostException e) {
            throw new IllegalStateException("cannot get host name", e);
         }
    }
}
```

Env
```
zr@agent-588ddcb847-vggrd:/ziprecruiter/branches$ env | grep -i buildah
_BUILDAH_STARTED_IN_USERNS=
BUILDAH_ISOLATION=chroot
```

**Comment by SaurabhAhuja1983** [comment]
@Luap99 Just verified #4869 and it worked fine.

Thank you for fixing it. I can see hostname entry in /etc/hosts

```
10.20.206.5	f8e90dcd64a1
---
Hostname: f8e90dcd64a1
---
```
Please do update once #4869 is merged to main and when new version is released.
I will close my PR's and we can close the issue as well.

Here is the output for the same Dockerfile and MyClass.java
```
STEP 1/3: FROM gcr.io/google-appengine/openjdk:8
Trying to pull gcr.io/google-appengine/openjdk:8...
Getting image source signatures
Copying blob bf5fa58026af done
Copying blob 6c1ecc5fc89f done
Copying blob 3898cc33768f done
Copying blob 47053b57b33d done
Copying blob 4e645dc40a1e done
Copying blob 58006514b43a done
Copying blob 02de81cd3ec5 done
Copying blob 0ec52dc55701 done
Copying config 24b0b1cf77 done
Writing manifest to image destination
Storing signatures
STEP 2/3: COPY MyClass.java .
STEP 3/3: RUN echo "---" ; cat /etc/hosts ; echo "---" ; echo "Hostname: $(hostname)" ; echo "---"; cat /run/.containerenv; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass
---
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.20.206.5	agent-68b4457b45-v8qsk
10.20.206.5	host.containers.internal
10.20.206.5	f8e90dcd64a1
---
Hostname: f8e90dcd64a1
---

engine="buildah-1.31.0-dev"
name="openjdk-working-container"
id="f8e90dcd64a1fb8180e7e52f1b3821cdd637101dc2fe8f723976b6925e404659"
image="gcr.io/google-appengine/openjdk:8"
imageid="24b0b1cf77f0c22b1b72fd120769fb7659a3c22bc36acbd4146f19828d510e83"
rootless=1
---
hostname: f8e90dcd64a1
COMMIT
Getting image source signatures
Copying blob bae09f197569 skipped: already exists
Copying blob e8dfdad54e7f skipped: already exists
Copying blob 38f4df8894d4 skipped: already exists
Copying blob 9f7fab83bf06 skipped: already exists
Copying blob d45333c5e4e1 skipped: already exists
Copying blob cb46af800a4a skipped: already exists
Copying blob 2a0c9830ac72 skipped: already exists
Copying blob d871745b73e3 skipped: already exists
Copying blob 96c39b037d1f done
Copying config fbdbfeef33 done
Writing manifest to image destination
Storing signatures
--> fbdbfeef33bb
fbdbfeef33bb69d319b033afbb4d489fdba3623eec0252b62d66b79f006f84b2
```

**Comment by SaurabhAhuja1983** [comment]
It's taken care here #4869 
closing this Pull Request.

**Pull request closed without merging**
