### PR TITLE
[release-1.16] tag v1.16.3

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Update our version information to identify as v1.16.3.

#### How to verify it

Visual inspection

#### Does this PR introduce a user-facing change?

```
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
but one of the tests isn't hip, I've not looked.

**Comment by nalind** [comment]
Restarted the jobs that failed.

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons.  @rhatdan PTAL

**Comment by nalind** [comment]
Added some entries to changelogs that I previously omitted because I'm that forgetful.

**Comment by TomSweeneyRedHat** [comment]
@nalind, for your punishment, walk away from your keyboard right now and don't return to it until the morning....

**Comment by TomSweeneyRedHat** [comment]
LGTM
@rhatdan PTAL

**Pull request merged**
