### PR TITLE
Export fields of the DokcerIgnore struct

### PR DESCRIPTION
**Pull request by QiWang19**
export fields in DockerIgnore struct for implementing the dockerignore in libpod
Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mheon PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by mheon** [comment]
What's the ask here? Why does Libpod need to know about .dockerignore?

**Comment by TomSweeneyRedHat** [comment]
@nalind or @rhatdan do either of you no why we need to add @QiWang19 to the white list still?  She's a member of Buildah with Write privs

**Comment by mheon** [comment]
Code LGTM, but I'm really curious as to what we're going to do with this in libpod land.

**Comment by TomSweeneyRedHat** [comment]
The goal is to provide dockerignore functionality for podman build like @QiWang19 just did for buildah bud (https://github.com/containers/buildah/issues/699).  However you may be right, I'm not sure that we need to export these variables to make that work....

**Comment by QiWang19** [comment]
`dockr cp` can also exclude files in .dockerignore.
make `podman cp` do the same with `docker cp` if `.dockerignore` exists

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
