### PR TITLE
unshare: move some code from cmd/buildah/unshare

### PR DESCRIPTION
**Pull request by giuseppe**
so that it can be reused by other programs.

alternative version for: https://github.com/containers/storage/pull/313

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Can you put this in buildah/pkg/unshare?

**Comment by rhatdan** [comment]
make lint is not happy.

**Comment by giuseppe** [comment]
fixed :arrow_up:

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @nalind @vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
I'm just starting to wondering long-term if this package should live under Buildah or somewhere under a more generic containers project?

**Comment by rhatdan** [comment]
We have been discussing that back and forth, For now lets just fix it in Buildah so skopeo can use it, and then moving forward we could decide to move it.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, everything is green but it didn't merge?

**Pull request closed without merging**
