### PR TITLE
vendor github.com/containers/storage@v1.12.15

### PR DESCRIPTION
**Pull request by vrothberg**
* zstd: use github.com/klauspost/compress directly
* Add support for installing man pages
* Remove merged directory when it is unmounted
* Switch to golangci-lint
* Update generated files
* Keep track of the UIDs and GIDs used in applied layers
* Add cirrus vendor check
* Switch to go modules
* Use same variable name on both commands
* cirrus: ubuntu: try removing cryptsetup-initramfs
* Move lockfiles to their own package
* getLockfile(): use the absolute path
* lockfile: don't bother releasing a lock when closing a file
* locking: take read locks on read-only stores
* locking test updates

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Main motivation was to debloat a bit. This PR strips ~2.3MB from Buildah and drops from ~28 to ~26MB.

@TomSweeneyRedHat @giuseppe @nalind @rhatdan

**Comment by TomSweeneyRedHat** [comment]
Looks like some zsdt declaration issues.

```
### COMPLETED IN 0s
>>> cd $GOSRC/buildah && make darwin
GOOS=darwin go build -ldflags '-X main.GitCommit=681118de -X main.buildInfo=1563897924 -X main.cniVersion=v0.7.0-rc2'  -o buildah.darwin -tags "containers_image_openpgp" ./cmd/buildah
# github.com/containers/buildah/vendor/github.com/containers/storage/pkg/archive
vendor/github.com/containers/storage/pkg/archive/archive_zstd.go:34:48: zstdReader redeclared in this block
	previous declaration at vendor/github.com/containers/storage/pkg/archive/archive_nocgo.go:10:48
vendor/github.com/containers/storage/pkg/archive/archive_zstd.go:39:50: zstdWriter redeclared in this block
	previous declaration at vendor/github.com/containers/storage/pkg/archive/archive_nocgo.go:14:50
make: *** [Makefile:41: darwin] Error 2
```

**Comment by vrothberg** [comment]
Currently testing @nalind's fixes.

**Comment by vrothberg** [comment]
Looking good. The Travis errors is just a vendor hiccup.

**Comment by rhatdan** [comment]
LGTM once you get proper merge into container/storage.

**Comment by vrothberg** [comment]
@nalind, thanks for your fixes! Once we have a new c/storage patch release, I will update this PR.

**Comment by vrothberg** [comment]
-> https://github.com/containers/storage/pull/397

**Comment by vrothberg** [comment]
Now updated to v1.12.15. Thanks @nalind for the fixes!

**Comment by TomSweeneyRedHat** [comment]
Test issues again, but these look unrelated.  I restarted ubuntu but didn't see a way to get darwin going agin.

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
