### PR TITLE
contrib/buildahimage: set config correctly for rootless `build` user

### PR DESCRIPTION
**Pull request by flouthoc**
For image published at `quay.io/containers/buildah` buildah should correctly use `fuseoverlay` for rootless `build` user `fuse-overlayfs`.

Closes: https://github.com/containers/buildah/issues/4669

[NO NEW TESTS NEEDED]

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
contrib/buildahimage: set config correctly for rootless `build` user
```

### CODE REVIEW

**Comment by rhatdan** [comment]
```
$ podman run --user build --device /dev/fuse -v /tmp/dan/:/tmp:Z quay.io/buildah/stable buildah build /tmp
time="2023-07-03T10:35:39Z" level=warning msg="Error loading container config when searching for local runtime: mkdir /home/build/rundir/libpod: no such file or directory"
time="2023-07-03T10:35:39Z" level=error msg="failed to setup From and Build flags: failed to get container config: mkdir /home/build/rundir/libpod: no such file or directory"
```

Does this fix this issue?

**Comment by rhatdan** [comment]
LGTM

**Comment by flouthoc** [comment]
@containers/build-maintainers PTAL

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @giuseppe @nalind @vrothberg PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
/hold
for happy tests

**Comment by TomSweeneyRedHat** [comment]
@flouthoc PTAL, tests are not at all happy

**Comment by flouthoc** [comment]
@TomSweeneyRedHat It was caused due to temporary outage of `registry.k8s.io:`

**Pull request merged**
