### PR TITLE
Change RUN to comment in bud.bats

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Just before merging #5411, a comment was made
about changing a RUN command to a comment.  This
completes that.

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@Luap99 PTAL

**Comment by mheon** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
