### PR TITLE
Fix errors found by codespell

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
We should make this a requirement before cutting a release.

make codespell finds them although it does some nasty stuff with ERRO.

**Comment by TomSweeneyRedHat** [comment]
Could we add codespell to release.sh?

**Comment by rhatdan** [comment]
Well it gives a couple of false positives, that I have not figured out how to block.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @giuseppe @nalind @QiWang19 @vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
bors retry

**Comment by TomSweeneyRedHat** [comment]
bors retry

**Comment by rhatdan** [comment]
bors retry

**Pull request merged**
