### PR TITLE
Cirrus: Temporarily disable Ubuntu 19 testing

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, if you haven't already, can you add a Jira card to the backlog to turn this back on?

**Comment by cevich** [comment]
> can you add a Jira card to the backlog to turn this back on?

Oh thanks, that's a great idea.

**Comment by cevich** [comment]
okay done.

**Comment by rhatdan** [comment]
opensuse.org is back, do we still want this?

**Comment by cevich** [comment]
nope.

**Pull request closed without merging**
