### PR TITLE
Restore rootless isolation test for from volume ro test

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Remove rootless from tests.

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
@rhatdan @nalind another failure in Go 11.1 tests due to gofmt.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Should be able to rebase this now and get it merged.

**Comment by rhatdan** [comment]
bot, retest this please.

**Comment by TomSweeneyRedHat** [comment]
Going to close and reopen in hopes that will kick this finally.

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
