### PR TITLE
Turn stdio back to blocking when command finishes

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/buildah/issues/3152

Sometimes after running buildah run in a terminal, commands executed afterwards which try to read from stdin fail with EAGAIN. This is because it sets O_NONBLOCK on the FD:

[NO TESTS NEEDED] Since I don't know how to test this.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind I am not sure if this is correct, PTAL?

**Comment by nalind** [comment]
This assumes the descriptor was originally blocking, and I'm not sure that's a valid assumption.  Also, it looks like we don't set a default value for `options.Logger` in `Run()` in cases where the caller didn't specify one, and the tests are now hitting code paths that attempt to use the value, which they weren't before.

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
@Vogtinator I can not get the original bug to happen, could you check to see if this fixes your problem?

**Comment by Vogtinator** [comment]
> @Vogtinator I can not get the original bug to happen, could you check to see if this fixes your problem?

Even by running the loop in #3152? Strange. I'll give it a try, but might take until next week.

**Comment by Vogtinator** [comment]
> > @Vogtinator I can not get the original bug to happen, could you check to see if this fixes your problem?
> 
> Even by running the loop in #3152? Strange. I'll give it a try, but might take until next week.

Went quicker than expected. I first reproduced the original bug a few times:

```
localhost:~ # grep flags /proc/self/fdinfo/0; while ! grep 'flags.*4002$' /proc/self/fdinfo/0; do buildah run tumbleweed-working-container /bin/true; echo -n .; done; cat -
flags:  02
.......flags:   04002
cat: -: Resource temporarily unavailable
localhost:~ # grep flags /proc/self/fdinfo/0; while ! grep 'flags.*4002$' /proc/self/fdinfo/0; do buildah run tumbleweed-working-container /bin/true; echo -n .; done; cat -
flags:  02
...flags:       04002
cat: -: Resource temporarily unavailable
localhost:~ # grep flags /proc/self/fdinfo/0; while ! grep 'flags.*4002$' /proc/self/fdinfo/0; do buildah run tumbleweed-working-container /bin/true; echo -n .; done; cat -
flags:  02
.....flags:     04002
cat: -: Resource temporarily unavailable
```

and then installed `buildah` from this PR:

```
localhost:~ # grep flags /proc/self/fdinfo/0; while ! grep 'flags.*4002$' /proc/self/fdinfo/0; do buildah run tumbleweed-working-container /bin/true; echo -n .; done; cat -
flags:  02
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^C
```

No failure!

For completeness, I also wrote a quick test program which opens `stdin` with `O_NONBLOCK` set and can confirm that it stays set even after multiple invocations of `buildah run`.

From my perspective, LGTM. Thanks!

**Pull request merged**
