### PR TITLE
Bump to containers/image v5.10.1

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@rhatdan the smoke test is failing hard in make for reasons that aren't totally clear in the log....

**Comment by rhatdan** [comment]
I forgot to merge some additional vendored files.

**Comment by rhatdan** [comment]
@nalind @mtrmac Is this an issue in buildah or containers/image?

**Comment by nalind** [comment]
That looks like something we need to fix in containers/image - we're passing `nil` in as a `SystemContext` pointer when calling a `docker` `ImageReference`'s `NewImageSource()` method, and that's supposed to be allowed.

**Review by QiWang19 — COMMENTED** [review]
Needs rebase

**Comment by TomSweeneyRedHat** [comment]
LGTM
but looks like you need a rebase.

**Comment by umohnani8** [comment]
LGTM but needs rebase

**Pull request merged**
