### PR TITLE
dockerignore tests : remove symlinks, rework

### PR DESCRIPTION
**Pull request by edsantiago**
rpm 4.16 alpha in rawhide has broken our koji build:

   https://github.com/containers/buildah/issues/2264

   https://github.com/rpm-software-management/rpm/issues/1159

TL;DR we can no longer package the 'circular-symlink' file
used in tests. This PR removes that and other symlinks from
the git working tree, and reworks the test so it runs from
a temporary directory and creates all necessary symlinks.

Also, since the test as written was simply checking "did it
run" without actually testing anything, add a test to confirm
that the files added to the image are exactly what we expect.

Signed-off-by: Ed Santiago <santiago@redhat.com>

#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Work around behavior change in rpmbuild

#### How to verify it

buildah will build in koji on rawhide (it currently does not)

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by edsantiago** [comment]
Tests failing due to l18n. Testing my fix now, will re-push once confirmed.

**Comment by edsantiago** [comment]
tests green

**Comment by QiWang19** [comment]
LGTM

**Comment by edsantiago** [comment]
Followup: [koji build succeeded](https://koji.fedoraproject.org/koji/buildinfo?buildID=1488861). Thanks everyone for quick review.

**Pull request merged**
