### PR TITLE
Update c/storage after https://github.com/containers/storage/pull/1436

### PR DESCRIPTION
**Pull request by mtrmac**

### CODE REVIEW

**Comment by mtrmac** [comment]
Now includes updates to avoid newly deprecated interfaces.

**Comment by mtrmac** [comment]
The c/storage PR was merged, and requires Buildah updates from this PR to avoid now-deprecated interfaces.

So, leaving this PR open, and ready for merge at some point. Merging it before the eventual vendor dance, and running the new code base in the meantime, might also introduce our confidence in the c/storage changes a bit.

**Comment by rhatdan** [comment]
/approve
LGTM
@flouthoc PTAL

**Review by flouthoc — APPROVED** [review]
LGTM @nalind @containers/buildah-maintainers PTAL

**Pull request merged**
