### PR TITLE
Remove configuration for bors

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Remove the configuration for the bors bot from this branch.  We're moving to something else.

#### How to verify it

n/a

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

The bors-ng bot is also installed as a github application in this repository.  One of the project admins will need to remove it.

#### Does this PR introduce a user-facing change?

```
None
```

### CODE REVIEW

**Comment by nalind** [comment]
> @nalind: The label(s) `kind/other` cannot be applied, because the repository doesn't have them

If I'm reading the docs right, each slash-kind we suggest in the template needs to have a corresponding "kind/foo" label that can be applied to the PR or issue as a result.  Renaming the Bug label to kind/bug.

**Comment by nalind** [comment]
Added labels for each kind that we list in the PR template, along with needs-rebase and do-not-merge/hold labels mentioned in the process doc.

**Comment by TomSweeneyRedHat** [comment]
Addresses: #2666

**Comment by TomSweeneyRedHat** [comment]
@cevich PTAL
LGTM

**Comment by nalind** [comment]
Removed the integration because we've seen the other bot handle a merge already.

**Pull request merged**
