### PR TITLE
Bump github.com/containers/image/v5 from 5.3.1 to 5.4.3

### PR DESCRIPTION
**Pull request by rhatdan**
Bumps [github.com/containers/image/v5](https://github.com/containers/image) from 5.3.1 to 5.4.3.
- [Release notes](https://github.com/containers/image/releases)
- [Commits](https://github.com/containers/image/compare/v5.3.1...v5.4.3)

Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rhatdan go mod is spitting up.

**Comment by rhatdan** [comment]
Removing vendor/modules.txt got this to pass.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
