### PR TITLE
Bump 1.20.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says!

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rhatdan @lsm5 @vrothberg @nalind PTAL, try 2 for the c/storage cve fix update

**Review by lsm5 — APPROVED** [review]
LGTM

**Pull request merged**
