### PR TITLE
tests: Fix file permissions

### PR DESCRIPTION
**Pull request by q384566678**
mode change 100755 => 100644.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
bot, retest this please.

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
