### PR TITLE
Re-Add file check to cacheing algorithm

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Add back the file checking mechanisms that were removed as part of the
reworking of the cache in #1792.  If we have a 'COPY mytar.tar.xz' command
in the Containerfile and the tar file was regenerated after an intial build,
secondary 'buildah bud' commands would use the cache from the first build
for the tar file instead of regenerating it.

The historyMatches() function (https://github.com/containers/buildah/blob/master/imagebuildah/executor.go#L287)
does not seem to pick up this type of change and I wasn't able to quickly
rework that to do so.  We may want to revert back to this check for now,
then tweak the historyMatches to work properly in a follow up PR.

Regardless, I've added a test as part of this PR to catch this issue
going forward.

FWIW, with the exception of the test code, all of the code is a reversion to pre-existing code.

Fixes:  #1906

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Tests are not happy.

**Comment by TomSweeneyRedHat** [comment]
Ugh, I swear I spend more time making the tests work in the CI than I do the actual code changes sometimes.  This worked fine in my sandbox, but it looks like an environment variable resolution issue in the CI.  I'll go hard code it, thanks for the heads up @rhatdan

**Comment by TomSweeneyRedHat** [comment]
I take the variable bit back, it looks like a git hiccup, it's not seeing my new bud/change-archive directory.  Gotta dig.

**Comment by TomSweeneyRedHat** [comment]
OMG, second day in a row with a corrupted sandbox.  Will have to spin up a new PR for this.

**Pull request closed without merging**
