### PR TITLE
Vendor in latest containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
Replaces a lot of write locks with read locks, which should help with
performance.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @vrothberg @TomSweeneyRedHat @nalind @pixdrift PTAL

**Comment by vrothberg** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
