### PR TITLE
Update github.com/openshift/imagebuilder to v1.2.14

### LINKED ISSUE #4948: Stage names that contain variables don't work with `--target`
**Description**

Stage names that contain a variable can't be resolved

```Dockerfile
ARG NAME="TEST"

from scratch as ${NAME}
```

```bash
$ buildah bud --target TEST
Error: The target "TEST" was not found in the provided Dockerfile
```

We encountered this issue here https://github.com/ublue-os/bluefin/pull/353

The root cause is in openshift/imagebuilder, and I already have [a fix](https://github.com/openshift/imagebuilder/commit/89e04944f0c8c2eb16e7a2de888ba8723080a120), but I want to clean up my code a bit before opening a PR.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.31.0-1.fc38.x86_64
```

**Output of `buildah version`:**

```
Version:         1.31.0
Go Version:      go1.20.5
Image Spec:      1.1.0-rc.3
Runtime Spec:    1.1.0-rc.3
CNI Spec:        1.0.0
libcni Version:  
image Version:   5.26.1
Git Commit:      
Built:           Wed Jul  5 15:10:35 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64

```

**Output of `cat /etc/*release`:**

```
Fedora release 38 (Thirty Eight)
NAME="Fedora Linux"
VERSION="38.20230731.0 (Silverblue)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38.20230731.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://silverblue.fedoraproject.org"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://github.com/fedora-silverblue/issue-tracker/issues"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='38.20230731.0'
Fedora release 38 (Thirty Eight)
Fedora release 38 (Thirty Eight)
```

**Output of `uname -a`:**

```
Linux fedora 6.4.6-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jul 24 20:51:12 UTC 2023 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

* Bump github.com/openshift/imagebuilder from v1.2.11 to v1.2.14, introducing a `BuiltinArgDefaults` field in a `Builder` that holds defaults for built-in `BUILD...` and `TARGET...` arguments.
* Always supply values for $TARGET... build args.

#### How to verify it

New conformance tests!
New integration test!

#### Which issue(s) this PR fixes:

Also fixes #4948.

#### Does this PR introduce a user-facing change?

```release-note
* `buildah build` should be more consistent about defining the TARGET family of built-in ARGs.
* Expanded support for evaluating environment and ARG references which use /, #, and % to modify results.
* `buildah build --target` now correctly resolves stage names which reference build arguments.
```

### CODE REVIEW

**Comment by nalind** [comment]
One of the test failures we're seeing needs https://github.com/openshift/imagebuilder/pull/294 to fix it properly.

**Review by flouthoc — APPROVED** [review]
LGTM
/approve
/lgtm
/hold

**Comment by nalind** [comment]
The merge commit for https://github.com/openshift/imagebuilder/pull/295 included bits from https://github.com/openshift/imagebuilder/pull/294 that we needed, so the commit that we tagged as imagebuilder v1.2.13 didn't include them.  I have opened https://github.com/openshift/imagebuilder/pull/296 to try to get it right.

**Pull request merged**
