### PR TITLE
[release-1.36] Fixes Listing tags in JFrog Artifactory may fail 

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Addresses the problem first described in https://github.com/containers/skopeo/issues/2346

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@lsm5 thoughts on the packit failures?

**Comment by lsm5** [comment]
> @lsm5 thoughts on the packit failures?

I suspect it's something in the ELN-aarch64 env given it's only failing there and nowhere else. I've pinged them but feel free to ignore if we need to get this going.

**Comment by TomSweeneyRedHat** [comment]
@lsm5 how can we move this forward at this point?  Do I just ask for the merge hammer from @rhatdan ?

**Comment by lsm5** [comment]
> @lsm5 how can we move this forward at this point? Do I just ask for the merge hammer from @rhatdan ?

there are no packit failures anymore. I hit the rerun button on failed cirrus tests just now.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@Luap99 PTAL at failures

**Comment by Luap99** [comment]
I would assume you need to backport https://github.com/containers/buildah/pull/5574 for test fixes

**Pull request merged**
