### PR TITLE
Retry on conflicts when generating a random image name

### PR DESCRIPTION
**Pull request by mtrmac**
#### What type of PR is this?

> /kind bug

#### What this PR does / why we need it:

Eliminate the risk of possibly generating a conflicting image name.

#### How to verify it

No non-invasive way.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mtrmac** [comment]
Fair point, I should actually write a test for the name collision check at least.

**Review by vrothberg — COMMENTED** [review]
I think there is a race between checking if the name is free and creating the image with this specific name.  We recently had a similar issue in Podman when assigning random names to containers.

**Comment by mtrmac** [comment]
Oops, you’re right, this is racy anyway; we would need to pre-allocate the name in a way that persistently records that cross-process, which this code does not do.

So, this would make the race smaller but not actually eliminate it, just adding false sense of security and potentially confusing readers of this code. Let’s not do that.

I don’t see how to truly fix this at this point, so I guess we’ll have to hope the 256-bit ID namespace is large enough :)

**Comment by vrothberg** [comment]
Maybe we can find a similar solution here.  What happened in Podman is loop around `CreateContainer` and do another round if the error indicates a name conflict with an existing container.

But I am not sure if that would work with images.

**Comment by mtrmac** [comment]
It probably would _work_, it’s just so ugly and expensive. (We create the image with a deterministic ID, typically using the config digest; all of that would succeed, only a final `Store.SetNames` with the conflicting name would fail — and we would tear down the whole image (re-creating squashed layers in the worst case?), and try again.)

**Comment by mtrmac** [comment]
Strictly speaking the user owns the namespace, so a collision is always possible. Pragmatically, maybe some combination of (container ID, timestamp) could be unique enough. But then the current code uses 256 bits of true randomness (unlike most of Podman, which uses the deterministic PRNG), which is at least as unique.

**Pull request closed without merging**
