### PR TITLE
Native OSX build

### PR DESCRIPTION
**Pull request by cevich**
***Depends on:*** #2631

#### What type of PR is this?

> /kind feature

#### What this PR does / why we need it:

These changes execute the cross-compile build naively on an OSX VM to more thoroughly verify multi-platform support (other than on Linux).  In other words, it confirms that any Linux-only changes do not leak into non-Linux environments.

#### How to verify it

The new/replaced Cirrus-CI task `Cross Compile` will pass.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Does this mean we nolonger compile Windows Mode?  Did we ever compile with window mode?

**Comment by cevich** [comment]
> Does this mean we nolonger compile Windows Mode? Did we ever compile with window mode?

I'm unaware of ever having a Windows build in CI.  This PR doesn't alter the make target used, only the platform we run it on.

**Comment by rhatdan** [comment]
LGTM
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
