### PR TITLE
Bump openshift/imagebuilder to v1.1.6

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
bors retry

**Comment by TomSweeneyRedHat** [comment]
@cevich got a big bors hammer to get this through?  I don't think bors has completed since you fixed the registry issue.

**Comment by rhatdan** [comment]
Saving the planet

**Pull request merged**
