### PR TITLE
imagebuildah: use "useCache" instead of "noCache"

### PR DESCRIPTION
**Pull request by nalind**
Name the field "useCache" and flip its meaning to make it easier to read the logic that uses it.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@vrothberg @TomSweeneyRedHat PTAL

**Comment by nalind** [comment]
@rh-atomic-bot r=vrothberg

**Comment by nalind** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
