### PR TITLE
Bats cgroups v2

### PR DESCRIPTION
**Pull request by edsantiago**

### CODE REVIEW

**Comment by edsantiago** [comment]
This is a two-part commit; if possible, I encourage you to review the two commits separately. It'll be a lot easier.

The gist is, this gets the `from.bats` (cgroups) tests passing on rawhide. Most of them are skipped, one is tweaked to conform to the new cgroupsv2 paths. It may be possible to tweak some of the other tests similarly; I couldn't find any way to do so.

The first commit is simply refactoring that I thought could be helpful and make my new addition (in commit #2) more readable.

**Comment by edsantiago** [comment]
This isn't even close to enough to get tests passing on rawhide. It's a mess. There's a lot more broken: timeouts, segfaults, more EPERMs, a spurious `error opening storage: vfs driver does not support overlay.mountopt options`, and more. But in the interests of readability and reviewability, I submit this small piece.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@mheon @giuseppe @TomSweeneyRedHat @QiWang19 @vrothberg @baude @cevich PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
