### PR TITLE
[CI:DOCS] Migrate buildah container image

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Moved to: https://github.com/containers/image_build

This is needed to consolidate both the content and the automation into one location.  Having both in the same place is intended to both protect push secrets and allow for PR-level CI testing.

#### How to verify it

N/A

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by edsantiago — APPROVED** [review]
LGTM, you get the idea

**Comment by cevich** [comment]
This is ready to go, new [build automation is functional and pushing images from `containers/image_build`](https://cirrus-ci.com/build/5993980085665792).

**Comment by cevich** [comment]
Force-push: Rebased.

@nalind @TomSweeneyRedHat PTAL, can we merge this please?

**Comment by cevich** [comment]
> but not Skopeo? Or did I miss it?

You missed it, already merged :wink:

**Pull request merged**
