### PR TITLE
Sort CLI flags

### LINKED ISSUE #1086: Sort CLI flags
@QiWang19 create this PR: https://github.com/containers/libpod/pull/1619 in Podman.  We need to do a similar thing here in Buildah.

### PR DESCRIPTION
**Pull request by QiWang19**
fix #1086 
Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @umohnani8 @giuseppe @pixdrift @vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM and passes baseline tests.

**Comment by umohnani8** [comment]
LGTM

**Comment by giuseppe** [comment]
LGTM

@rh-atomic-bot retry

**Pull request closed without merging**
