### PR TITLE
Add authentication system tests for 'commit' and 'bud'

### PR DESCRIPTION
**Pull request by hshiina**
Signed-off-by: Hironori Shiina <shiina.hironori@jp.fujitsu.com>

#### What type of PR is this?

/kind other

#### What this PR does / why we need it:
This PR adds a few system test to verify authentication flags of `commit` and `bud` subcommands.

#### How to verify it
Run system tests.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @hshiina 
LGTM

**Review by edsantiago — APPROVED** [review]
LGTM, thank you!

**Comment by TomSweeneyRedHat** [comment]
@hshiina TY!
LGTM

**Pull request merged**
