### PR TITLE
Update vendor of containers/common to v0.6.1

### PR DESCRIPTION
**Pull request by rhatdan**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@lsm5 @TomSweeneyRedHat @QiWang19 @vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
Can you tweak the title from 1.6.1 to 0.6.1 please?
LGTM otherwise

**Comment by rhatdan** [comment]
This should fix the compiler problem @lsm5 saw in rawhide.

**Comment by QiWang19** [comment]
LGTM

**Comment by rhatdan** [comment]
bors retry

**Comment by rhatdan** [comment]
@edsantiago Is buildah building in Rawhide again?

**Comment by edsantiago** [comment]
It [doesn't look like it](https://koji.fedoraproject.org/koji/packageinfo?packageID=24131). Smells like another 32-bit problem. [logs of latest build attempt this morning](https://koji.fedoraproject.org/koji/taskinfo?taskID=42611322)

**Comment by vrothberg** [comment]
@edsantiago, do build break frequently enough on Rawhide to justify a (non-blocking) job in the usptream CI here? We could run builds in a rawhide container. Maybe there's already such a pipeline that I may not be aware of.

**Comment by edsantiago** [comment]
Builds break constantly, but it's nothing to do with rawhide, and everything to do with 32-bit incompatibilities. We catch them in rawhide because there are frequent builds. I believe the CI setup should include `make` on a 32-bit system.

**Comment by rhatdan** [comment]
Right we should be compiling Podman with a 32 bit compiler.

**Comment by rhatdan** [comment]
Something like d51191e8e8d2fd95657c230242f5d21a6120a018

**Comment by lsm5** [comment]
still failing https://koji.fedoraproject.org/koji/taskinfo?taskID=42618824

**Comment by lsm5** [comment]
err, my buildah job might not be updating atm, ignore ^

**Comment by rhatdan** [comment]
Not easy to see what is going wrong?

**Comment by lsm5** [comment]
the autobuild job wasn't updating the commit, so it was building an older version, doing a new one now..

**Comment by lsm5** [comment]
builds fine now https://koji.fedoraproject.org/koji/taskinfo?taskID=42619477
Thanks.

**Pull request merged**
