### PR TITLE
bump github.com/opencontainers/runtime-tools

### PR DESCRIPTION
**Pull request by dfr**
This picks up the changes that add FreeBSD support to
runtime-tools/generate:

    go get github.com/opencontainers/runtime-tools@17b3287fafb78aee959deac9c234b7a123a242a7

Signed-off-by: Doug Rabson <dfr@rabson.org>

#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

This pulls in FreeBSD support for github.com/opencontainers/runtime-tools

#### How to verify it

Build and run buildah on FreeBSD

#### Special notes for your reviewer:

Not sure this is the right way to do this but it seems faster than waiting for a new release tag in runtime-tools.

#### Does this PR introduce a user-facing change?

None

### CODE REVIEW

**Comment by rhatdan** [comment]
There is no code in your revendor?  Did  you leave some files in the vendor directory?

**Comment by dfr** [comment]
Good question - I'll try to figure out what happened. Bear with me - I'm still getting back up to speed after getting over the latest covid.

**Comment by dfr** [comment]
Learning new things: I needed to run 'go mod vendor' after 'go get'.

**Comment by rhatdan** [comment]
We just use `make vendor-in-container`

**Pull request merged**
