### PR TITLE
Add conformance tests for COPY ""

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Add a couple of conformance tests exercising "" as a source name for COPY instructions, so that we don't regress on https://github.com/openshift/imagebuilder/issues/181 in the future.
Add a conformance test for COPY --from where the source location is a symbolic link.
Add conformance tests for COPY where the source location is an absolute path with multiple components.

#### How to verify it

New conformance tests!

#### Which issue(s) this PR fixes:

Nothing here, this just adds tests that we already would have passed.

#### Does this PR introduce a user-facing change?

```
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests.

**Comment by nalind** [comment]
Added a few more tests.

**Comment by rhatdan** [comment]
@nalind seems to have been cancelled in cirrus, we might need to repush to get the ci/cd system working again.

**Pull request merged**
