### PR TITLE
Move away from using docker.io

### PR DESCRIPTION
**Pull request by mtrmac**
Per @jnovy , backporting #2844 to release-1.16.

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
@rhatdan PTAL

**Comment by mtrmac** [comment]
Adding a backport of #2856 ; that just turns off a failing test, but the PR to actually fix it (linked from it) is still in a draft state.

@cevich PTAL.

**Comment by edsantiago** [comment]
/approve

Thank you @mtrmac

**Pull request merged**
