### PR TITLE
from: fix isolation option

### PR DESCRIPTION
**Pull request by q384566678**
Add the isolation option to the from command.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@q384566678 nice catch and fix.  Can you also update the `./contrib/completions/bash/buildah` file and add isolation to the options under from too please?

**Comment by rhatdan** [comment]
@q384566678 Are you able to update the PR, or should I just merge and wait for a second PR?

**Comment by rhatdan** [comment]
Ok I am going to merge so we can release buildah 1.4 with this feature.  @q384566678 Please open another PR so we can get the bash completions.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
