### PR TITLE
Add overlayfs to fuse-overlayfs tip

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
This adds a note about replacing overlayfs with
fuse-overlayfs.  We've had a number of issues reported
about overlayfs not working in a rootless environment
and this will hopefully help.  Reference: #1745, #1720 and

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mheon and @giuseppe PTAL.  I'll plan to add this verbiage to the Podman's troubleshooting guide too.

**Comment by rhatdan** [comment]
Should the buildah man page have this information also.

**Comment by giuseppe** [comment]
LGTM, but I still think we need to add fuse-overlayfs as a dependency so not everyone needs to manually configure it

**Comment by rhatdan** [comment]
Yes it should be a recommends.

**Comment by rhatdan** [comment]
@lsm5 FYI ^^

**Comment by TomSweeneyRedHat** [comment]
I concur @giuseppe about it being a recommends, just trying to ease the pain a bit with this change.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan I'm not sure which man page you're referring to in Buildah.  But I'm not sure of which man page it should be in, they generally don't contain "gotcha" kind of notes.  I am working on getting this into the Podman troubleshooting guide if that is what you were thinking.

**Comment by rhatdan** [comment]
Under `man podman`  There is a section o podman rootless mode.  We should mention fuse-overlayfs in that section and that section should be copied into the buildah man pages.

These are some of the most common complaints people are getting with podman/buildah running rootless.

**Comment by TomSweeneyRedHat** [comment]
Thanks @rhatdan, I'll take a look at adding the info on the podman page then too.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request merged**
