### PR TITLE
Bump 1.25.0

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Bump to v1.25.0 in for the next release targeted at Fedora.

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mheon @vrothberg @giuseppe @nalind @rhatdan @flouthoc  PTAL

**Review by lsm5 — APPROVED** [review]
i see the bump is directly from 1.25.0 to 1.26.0-dev. Is there going to be a separate release branch to continue 1.25 ?

LGTM either way.

**Comment by TomSweeneyRedHat** [comment]
@lsm5 1.25.+ will be in main going forward.  We generally only cut a release branch when we have a version headed for RHEL.  My guess is we won't make a branch for 1.25.  I think it will be a following version in August when we're getting ready for RHEL 8.7/9.1

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
