### PR TITLE
imagebuildah: if user sets `--jobs=0` they expect no parallelism

### PR DESCRIPTION
**Pull request by flouthoc**
Lot of users and tests set --jobs=0 they are expecting no parallelism
between stages but we still end up running builds in parallel for
multi-arch builds which indirectly executes stages in parallel since builds are parallel.

Example tests like https://github.com/containers/buildah/blob/main/tests/bud.bats#L3609 set `--jobs=0` but they still execute build for similar name but different arch in parallel.

**[Note:]** This PR does not fix more that one race condition which is seen when multi-arch builds are performed without `--jobs=0` as documented here: https://github.com/containers/buildah/issues/3710#issuecomment-1081613407 but it should fix flakes in CI as reported here: https://github.com/containers/buildah/issues/3710

### CODE REVIEW

**Comment by flouthoc** [comment]
This should fix the flake as tests in CI use `--jobs=0` but this does not means that actual race is fixed which can be seen again without `--jobs=0` for `multi-arch` builds.

**Comment by nalind** [comment]
> Lot of users and tests set --jobs=0 they are expecting no parallelism between stages but we still end up running builds in parallel for multi-arch builds which indirectly executes stages in parallel since builds are parallel.
> 
> Example tests like https://github.com/containers/buildah/blob/main/tests/bud.bats#L3609 set `--jobs=0` but they still execute build for similar name but different arch in parallel.

That's why that test specifies `--jobs=0`.  The default is to behave as though `--jobs=1` was specified.

**Comment by flouthoc** [comment]
@nalind If I inferred it correctly `--jobs=0` should mean no parallelism at all but we still do builds for each platform in parallel manner.

**Comment by nalind** [comment]
The intent of that test is definitely maximum parallelization.

**Comment by flouthoc** [comment]
@nalind Oh i see but then I think users have no way to serialize `mult-arch` builds.

**Comment by cevich** [comment]
> users have no way to serialize mult-arch builds.

I think it's incorrect to equate serialized builds with serialized pulls, one doesn't necessarily imply the other.  Though I appreciate it vastly complicates the fix.  As a user doing an operation requiring a multi-arch pull, I expect that pull to happen as fast as my bandwidth allows - meaning in parallel when possible.

**Comment by flouthoc** [comment]
> > users have no way to serialize mult-arch builds.
> 
> I think it's incorrect to equate serialized builds with serialized pulls, one doesn't necessarily imply the other. Though I appreciate it vastly complicates the fix. As a user doing an operation requiring a multi-arch pull, I expect that pull to happen as fast as my bandwidth allows - meaning in parallel when possible.

@cevich Pulls are not causing the issue but i think builds are causing the issue, its easily reproduce-able  when you run `bud-multiple-platform-no-run` a few times.

I'm going to close this PR since it is not doing what i expected it to do.

**Pull request closed without merging**
