### PR TITLE
Replace k8s.gcr.io/pause in tests with registry.k8s.io/pause

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

In kubernetes 1.25, the default source for the pause image is now registry.k8s.io instead of k8s.gcr.io (https://github.com/kubernetes/kubernetes/pull/109938).  Update our references to the pause image.

#### How to verify it

Tests should continue to pass.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@vrothberg @flouthoc @giuseppe @TomSweeneyRedHat @ashley-cui @umohnani8 PTAL

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Review by vrothberg — APPROVED** [review]
LGTM

**Pull request merged**
