### PR TITLE
Check earlier for bad image tags name

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/buildah/issues/3134

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
All kinds of red test unhappiness @rhatdan

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @containers/podman-maintainers PTAL
Fixed now.

**Comment by rhatdan** [comment]
@saschagrunert @giuseppe @vrothberg PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
