### PR TITLE
Update buildah-login.md

### PR DESCRIPTION
**Pull request by rhatdan**
Fix typo in man page.

Thanks to @lukeyeager for finding this.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces https://github.com/containers/buildah/pull/1689

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @ashley-cui @QiWang19 @vrothberg PTAL

**Comment by ashley-cui** [comment]
LGTM

**Comment by rhatdan** [comment]
@jlebon Is there something broken in the Red Hat CI?

**Comment by jlebon** [comment]
Yup, internal OpenStack instance having some issues right now.

**Comment by vrothberg** [comment]
I'm force merging. No need to waste energy for this simple change.

**Pull request merged**
