### PR TITLE
vendor c/common@v0.49.1

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
@mtrmac @flouthoc PTAL

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by mtrmac** [comment]
@vrothberg Thanks!

**Pull request merged**
