### PR TITLE
Return exit code from failed containers

### PR DESCRIPTION
**Pull request by rhatdan**
Buildah run was exiting with the correct exit code, when a container
failed.  Buildah bud was not, so this should fix this.

Also switched to the proper exit codes when containers fail.  When
Buildah fails to execute it will exit with a 125 exit code like
Podman does.  If a command fails to execute inside of a container
we will exit with a 126. Currently we do not support the 127 for
exiting when the command does not exist.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/buildah/issues/2305
@TomSweeneyRedHat @mheon @vrothberg @QiWang19 @nalind PTAL

**Comment by rhatdan** [comment]
@frenzymadness PTAL

**Comment by TomSweeneyRedHat** [comment]
@rhatdan looks like some real test unhappiness

**Comment by rhatdan** [comment]
@vrothberg Added a couple of tests.  Hopefully tests will pass now.

**Comment by frenzymadness** [comment]
The diff looks good to me (althou I am not go expert). There are two problems in CI:
One failing test:
```
[+1640s] not ok 404 run-exit-status on non executable
[+1640s] # (from function `die' in file ./helpers.bash, line 174,
[+1640s] #  from function `run_buildah' in file ./helpers.bash, line 162,
[+1640s] #  in test file ./run.bats, line 383)
[+1640s] #   `run_buildah 125 run ${cid} /etc' failed
[+1640s] # # [checking for: alpine]
[+1640s] # # [restoring from cache: /var/tmp/buildah-image-cache.1 / alpine]
[+1640s] # Getting image source signatures
[+1640s] # Copying blob sha256:5930684f102265e2c4de4c1c4ad36e24fc10fc7793b1f8ba7e499d382d7fadc9
[+1640s] # Copying config sha256:1c0ce5587a33a2e4e3814a2cf4c7f401947f5c0df4f71d11bd2bcc7447f2136e
[+1640s] # Writing manifest to image destination
[+1640s] # Storing signatures
[+1640s] # Loaded image(s): localhost/alpine
[+1640s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../buildah from --quiet --pull=false --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json alpine
[+1640s] # alpine-working-container
[+1640s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../buildah run alpine-working-container /etc
[+1640s] # process exited with error: fork/exec /etc: permission deniedsubprocess exited with status 1
[+1640s] # [ rc=1 (** EXPECTED 125 **) ]
[+1640s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+1640s] # #| FAIL: exit code is 1; expected 125
[+1640s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
And a problem with ubuntu repositories.

I've tried to build this version locally and it seems to work with my simple reproducer from #2305 : 
```
$ ./buildah build-using-dockerfile ~/temp/podman-exit-test/Dockerfile 
STEP 1: FROM fedora:31
STEP 2: ADD exit.sh /
STEP 3: RUN /exit.sh
ERRO exit status 3
$ echo $?
3
```

Thank you!

**Comment by rhatdan** [comment]
Now we have the bad Ubuntu image problem. :^(

**Comment by rhatdan** [comment]
@cevich Can we drop the cisco release from Ubuntu?  Do you have any idea what is going on ?

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Tests are passing.  PTAL

**Comment by TomSweeneyRedHat** [comment]
The change to test/bud.bats can't be right.  It looks to be updating one test and removing the rest?

**Comment by rhatdan** [comment]
Yikes, fixing.

**Comment by cevich** [comment]
> Can we drop the cisco release from Ubuntu? Do you have any idea what is going on ?

@rhatdan I'm not well versed in Ubuntu/Debian, so I'm not sure what "cisco release" is or how to drop it.   Assuming you're talking about the extra package repos added by google, yes, I'm working on that (part of #1971 is using static VM images, instead of trying to install/update them at testing-runtime).  This will improve both speed and reliability, and is my focus this week.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @vrothberg @giuseppe @nalind PTAL  Can we get this merged.

**Pull request merged**
