### PR TITLE
Support multiple manifests in c/storage

### PR DESCRIPTION
**Pull request by mtrmac**
<s>WIP, do not merge: Right now only <s>to have a fallback implementation and</s> to get it through CI.</s>

<s>**The c/image branch is unmerged upstream.**</s>

### CODE REVIEW

**Comment by nalind** [comment]
LGTM

**Comment by rhatdan** [comment]
@mtrmac Can fix this PR so we can merge it?

**Comment by mtrmac** [comment]
We still don’t have tests for the c/image part, but it’s been merged into CRI-O already and all the buildah/libpod/CRI-O tests are passing, so sure, let’s call this good enough.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
