### PR TITLE
CI VMs: bump, to debian with cgroups v2

### PR DESCRIPTION
**Pull request by edsantiago**
Per consent in 2024-03-20 Planning, remove support for cgroups v1.
And, per discovery on 2024-05-28, systemd 256 no longer even
boots on a cgroups v1 system.

This commit switches to VMs built in:

  https://github.com/containers/automation_images/pull/338

...in which Debian is now cgroups v2 with crun.

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
@containers/buildah-maintainers PTAL, this is important for gating tests, and for podman bud tests, and for getting rid of cgroups v1.

@nalind if you can offer me a quick fix for the commented-out tests, I'd love that, otherwise I'll file issues.

**Comment by lsm5** [comment]
rawhide build failures are unrelated and should be fixed automatically on the infra side soon. Ignore for now

**Comment by edsantiago** [comment]
@containers/buildah-maintainers please merge when convenient.
* docker tests: will need to be fixed by @nalind some day
* bats tests (the debian ulimit thing): I've looked into it on a ci-vm, have not been able to figure it out, am quitting for today and will look again tomorrow with a fresh brain.
* the `git` fix is necessary because VM images have a new `git` which throws new errors when root serves non-root files.

**Comment by rhatdan** [comment]
/approve
lgtm

**Comment by rhatdan** [comment]
@cevich @lsm5 @nalind @giuseppe PTAL

**Pull request merged**
