### PR TITLE
linux: add check for sysctl before using it

### PR DESCRIPTION
**Pull request by giuseppe**
check that the sysctl we'd like to use is supported by the kernel
before using it.

Closes: https://github.com/containers/buildah/issues/1618

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
`./run_linux.go:1460:36: undefined: strings.ReplaceAll`

Has `ReplaceAll()` been added with go 1.12?

**Comment by vrothberg** [comment]
Oh yes, that's a fairly new function (see https://go-review.googlesource.com/c/go/+/137855/). @giuseppe, can you change to use [Replace](https://golang.org/pkg/strings/#Replace) to remain backwards compatible?

**Comment by giuseppe** [comment]
@vrothberg sure, I had pushed a fixed version and was waiting for the CI to complete

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by vrothberg** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
