### PR TITLE
vendor: bump c/storage to `55ee2d19292f`

### PR DESCRIPTION
**Pull request by flouthoc**
[NO NEW TESTS NEEDED]

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
vendor: bump c/storage to v1.46.2-0.20230526114421-55ee2d19292f
```

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by edsantiago** [comment]
Once this merges, I'll run it through the treadmill.

**Comment by TomSweeneyRedHat** [comment]
@flouthoc the conformance tests aren't happy.

**Comment by flouthoc** [comment]
Rebased after https://github.com/containers/buildah/pull/4819

**Comment by flouthoc** [comment]
@rhatdan This needs force merge, or I need to rebase.

**Pull request merged**
