### PR TITLE
Don't fail copy to emptydir

### PR DESCRIPTION
**Pull request by rhatdan**
pick f379c5c2 Don't fail copy to emptydir

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind @terceiro any idea why these are failing?

**Comment by TomSweeneyRedHat** [comment]
I don't know the why's, but a conformance test is failing a .dockerignore test, which I think is coming from the copy to emptydir PR that I've yet to chase down.

**Comment by rhatdan** [comment]
There are several tests that are failing for this on the main branch now.

Basically dockerignore checks were expecting to fail when the directory exists, but all of the contents of the directory are blocked by .dockerignore.  The change in your PR causes these tests to no longer fail.

**Comment by rhatdan** [comment]
This breaks conformance with Docker, closing.

**Pull request closed without merging**
