### PR TITLE
Move DiscoverContainerfile to define directory, so podman can use it

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by nalind** [comment]
The point of moving type definitions into this directory is to avoid having consumers build code that they might not end up calling, and this seems to run counter to that goal.  Somewhere under `pkg` or in the `util` grab bag would be more appropriate.

**Comment by TomSweeneyRedHat** [comment]
If @nalind likes the location, the changes LGTM.  Tests aren't happy yet though.

**Comment by nalind** [comment]
I don't _love_ it (why must it be added in an existing import path?), but it's not a hill I'm particularly interested in dying on.  Either way, the commit message and pull request name need to be updated.

**Comment by rhatdan** [comment]
@nalind Moved it to pkg/util

**Comment by TomSweeneyRedHat** [comment]
@rhatdan the smoke test is smoking

**Comment by nalind** [comment]
Needs to add `pkg/util/*.go` to the `SOURCES` list in the top-level Makefile, then LGTM.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan looks like a rebase is wanted.

**Pull request merged**
