### PR TITLE
Remove device mapper support

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What this PR does / why we need it:

Remove device mapper support.

It seems that no one is using devicemapper storage driver nowadays, since overlayfs is so much better.

#### Which issue(s) this PR fixes:

Related to https://github.com/containers/storage/issues/1619

#### Does this PR introduce a user-facing change?

```release-note
Device mapper storage driver is removed.
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Maybe I need more tea this morning, but this looks like the test should have passed.  @edsantiago can you tell me where I'm mis-reading?

```
[+1012s] not ok 140 build using intermediate images should not inherit label
[+1012s] # (from function `assert' in file ./helpers.bash, line 430,
[+1012s] #  from function `expect_output' in file ./helpers.bash, line 457,
[+1012s] #  in test file ./bud.bats, line 1964)
[+1012s] #   `expect_output --substring --from="${lines[$i]}" "Using cache"' failed
[+1012s] # /var/tmp/go/src/github.com/containers/buildah/tests /var/tmp/go/src/github.com/containers/buildah/tests
[+1012s] # # [checking for: docker.io/library/alpine]
[+1012s] # # [restoring from cache: /var/tmp/buildah-image-cache.9270 / docker.io/library/alpine]
[+1012s] # Getting image source signatures
[+1012s] # Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
[+1012s] # Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
[+1012s] # Writing manifest to image destination
[+1012s] # Storing signatures
[+1012s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah build --no-cache --layers --label somefancylabel=true --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json -t imageone -f Dockerfile.name /var/tmp/go/src/github.com/containers/buildah/tests/./bud/multi-stage-builds
[+1012s] # [1/2] STEP 1/2: FROM alpine AS myname
[+1012s] # [1/2] STEP 2/2: COPY Dockerfile.name /
[+1012s] # --> f892218adecd
[+1012s] # [2/2] STEP 1/3: FROM scratch
[+1012s] # [2/2] STEP 2/3: COPY --from=myname /Dockerfile.name /Dockerfile.name
[+1012s] # --> 4fb82e4e6451
[+1012s] # [2/2] STEP 3/3: LABEL "somefancylabel"="true"
[+1012s] # [2/2] COMMIT imageone
[+1012s] # --> b2010c270d55
[+1012s] # Successfully tagged localhost/imageone:latest
[+1012s] # b2010c270d55b5b5c5db710c5cb78cb5444cdcd812a280f41bc0e79f7466249a
[+1012s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah inspect --format {{ index .Docker.Config.Labels "somefancylabel"}} imageone
[+1012s] # true
[+1012s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah build --layers --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json -t imagetwo -f Dockerfile.name /var/tmp/go/src/github.com/containers/buildah/tests/./bud/multi-stage-builds
[+1012s] # [1/2] STEP 1/2: FROM alpine AS myname
[+1012s] # Trying to pull docker.io/library/alpine:latest...
[+1012s] # Getting image source signatures
[+1012s] # Copying blob sha256:8a49fdb3b6a5ff2bd8ec6a86c05b2922a0f7454579ecc07637e94dfd1d0639b6
[+1012s] # Copying config sha256:5e2b554c1c45d22c9d1aa836828828e320a26011b76c08631ac896cbc3625e3e
[+1012s] # Writing manifest to image destination
[+1012s] # Storing signatures
[+1012s] # [1/2] STEP 2/2: COPY Dockerfile.name /
[+1012s] # --> ace9312b60b8
[+1012s] # [2/2] STEP 1/2: FROM scratch
[+1012s] # [2/2] STEP 2/2: COPY --from=myname /Dockerfile.name /Dockerfile.name
[+1012s] # --> Using cache 4fb82e4e645168a4b52f04c79c7d05baee81947332084c2b3e819a850c662135
[+1012s] # [2/2] COMMIT imagetwo
[+1012s] # --> 4fb82e4e6451
[+1012s] # Successfully tagged localhost/imagetwo:latest
[+1012s] # 4fb82e4e645168a4b52f04c79c7d05baee81947332084c2b3e819a850c662135
[+1012s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+1012s] # #|     FAIL: buildah build --layers --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json -t imagetwo -f Dockerfile.name /var/tmp/go/src/github.com/containers/buildah/tests/./bud/multi-stage-builds
[+1012s] # #| expected: =~ 'Using cache'
[+1012s] # #|   actual:    'Getting image source signatures'
[+1012s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+1012s] # /var/tmp/go/src/github.com/containers/buildah/tests
```

**Comment by edsantiago** [comment]
So, to simplify the life of whoever debugs this, here is a good/bad diff:
```
$ buildah build --layers [...]  -t imagetwo -f Dockerfile.name .../multi-stage-builds
[1/2] STEP 1/2: FROM alpine AS myname             | <same>
[1/2] STEP 2/2: COPY Dockerfile.name /            | Trying to pull docker.io/library/alpine:latest...
--> Using cache fa1c25317072...                   | Getting image source signatures
--> fa1c25317072                                  | Copying blob ...
```
Left is good (expected output), right is bad (failure in this CI run). Basically, the failed run does "Trying to pull alpine". Again, I can't explain why, and leave it to smarter people to investigate.

**Comment by TomSweeneyRedHat** [comment]
Thanks @edsantiago your answer is what I was looking for.  I saw the "Using cache" in the output, and given that, thought the test `expected: =~ 'Using cache'` should have been successful.

**Comment by kolyshkin** [comment]
Rebased to include #4837

**Comment by kolyshkin** [comment]
Rebased

**Comment by rhatdan** [comment]
/approve
LGTM

**Review by vrothberg — APPROVED** [review]
LGTM, thanks!

**Comment by rhatdan** [comment]
Now we need to debate whether we bump the major version of Buildah.

**Comment by vrothberg** [comment]
> Now we need to debate whether we bump the major version of Buildah.

Assuming devicemapper has never been supported, we may win in court :^)

**Pull request merged**
