### PR TITLE
Add history names support

### PR DESCRIPTION
**Pull request by saschagrunert**
The new `buildah images --history` flags shows the history of the names
an image had in the past. If the latest image in the history is equal
the current image's name, then we skip that on from the history for
convenient purposes.

### CODE REVIEW

**Comment by rhatdan** [comment]
Missing:
Command completions

**Comment by rhatdan** [comment]
Tried it out and it looks good.

**Comment by saschagrunert** [comment]
> Missing:
> Command completions

Alright, I added the bash completion. Now I'm just wondering why the bud integration test fails :thinking:

**Comment by rhatdan** [comment]
This looks like a bug caused by a different patch to containers/storage.

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, @vrothberg anythoughts on the c/storage error in the test?

**Comment by saschagrunert** [comment]
This seems to be the cause of the issue: https://github.com/containers/storage/pull/466

**Comment by rhatdan** [comment]
@saschagrunert does the latest container/storage fix this issue, or do we need to cut another release?

**Comment by saschagrunert** [comment]
I think so, let's see what the CI think about it. :)

**Comment by rhatdan** [comment]
Looks like that xattrs patch is still problematic?

**Comment by saschagrunert** [comment]
Yes, I wrote a comment at the linked closed PR for containers storage. I’m not sure if we should revert the change honestly. I’ll debug further tomorrow.

**Comment by saschagrunert** [comment]
Added a commit to vendor the fix of https://github.com/containers/storage/pull/483, but I expect that it will break stuff again...

**Comment by rhatdan** [comment]
This looks good, lets get the other PRs merged into container/storage and then I can cut another release.

**Comment by TomSweeneyRedHat** [comment]
LGTM.  @rhatdan I'll let you pull the trigger on the merge of this one.

**Comment by saschagrunert** [comment]
Let's wait for https://github.com/containers/storage/pull/485, which I can vendor in here.

**Comment by saschagrunert** [comment]
Rebased on v1.15.2, ready for review.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
