### PR TITLE
fix(docs): typo in install.md

### PR DESCRIPTION
**Pull request by Shanduur**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

It fixes minor typo in install.md file.

#### How to verify it

As it is documentation fix, simply compare versions.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@Shanduur thanks for the PR and nice eagle eye.  Our CI requires that the commits be signed.  Can you `git commit --amend -s`, rebase and push again please?

**Comment by Shanduur** [comment]
Yeah, this should have fixed the issue. Thanks for the explaination!

**Comment by Shanduur** [comment]
I don't get why it is failing, @TomSweeneyRedHat could you please take a look?

```powershell
PS C:\Repos\buildah> git --no-pager log -1
commit 37d46bb1147bfaac7480d6036a4cfb47496ce0df (HEAD -> patch-1, origin/patch-1)
Author: Mateusz Urbanek <mateusz.urbanek.98@gmail.com>
Date:   Fri Jun 4 08:37:25 2021 +0200

    fix(docs): typo
PS C:\Repos\buildah> git verify-commit HEAD
gpg: Signature made Sat Jun  5 20:05:02 2021 CEDT
gpg:                using RSA key 83CB5368B5B368848A525092965531459857EDA0
gpg: Good signature from "Mateusz Urbanek <mateusz.urbanek.98@gmail.com>" [ultimate]
```

**Comment by rhatdan** [comment]
The failures have nothing to do with this PR.

**Comment by rhatdan** [comment]
Thanks @Shanduur

**Pull request merged**
