### PR TITLE
Don't set ambient caps; switch to moby/sys/capability

### PR DESCRIPTION
**Pull request by kolyshkin**
github.com/moby/sys/capability is a fork of the (no longer maintained) github.com/syndtr/gocapability package.

For the list of changes since the fork took place, see https://github.com/moby/sys/blob/main/capability/CHANGELOG.md

#### What type of PR is this?

/kind other

#### Special notes for your reviewer:

Note that removing the AMBENT caps from chroot is a no-op -- since ambient caps couldn't be set without inheritable, practically they were not set since commit e7e55c988.

See also
* https://github.com/containers/common/pull/2167
* https://github.com/containers/storage/pull/2103
* https://github.com/opencontainers/runtime-tools/pull/777

#### Does this PR introduce a user-facing change?

```release-note
none
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
I think I found a bug :)

```
[kir@kir-tp1 chroot]$ go test -run TestNoop -exec sudo  -v
=== RUN   TestNoop
    run_test.go:121: run: exit status 1: error setting capabilities for process: setting capabilities: operation not permitted
        subprocess exited with status 1
--- FAIL: TestNoop (0.08s)
FAIL
exit status 1
FAIL	github.com/containers/buildah/chroot	0.107s
```

One of the most important fixes in the capability package fork was this one: https://github.com/kolyshkin/capability/pull/3/commits/4d79446943b85de52b0a52d4e229a8131d16989f

Essentially, an error from setting ambient capabilities was ignored. Now it is not.

Most probably ambient capabilities are set without setting inheritable ones. We found the same issue in runc.

**Comment by kolyshkin** [comment]
> Most probably ambient capabilities are set without setting inheritable ones. We found the same issue in runc.

Right. Added a commit that fixes that.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@nalind @giuseppe @mtrmac @mheon @flouthoc PTAL

**Comment by mheon** [comment]
LGTM

**Comment by nalind** [comment]
LGTM, thanks!
/approve
/lgtm

**Pull request merged**
