### PR TITLE
Bump 1.8.0 try2

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Try 2, bump the version to 1.8.0 and 1.9-dev.  Bumping to 1.8 over 1.7.4 to hopefully avoid further Fedora 30 kitting issues and due to changes in c/storage.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM but I would change your script to specify 1.9.0-dev for the next time we do this.

**Comment by TomSweeneyRedHat** [comment]
The script falls down and doesn't do the second commit.  It also doesn't touch up the buildah.spec with the changes correctly.  I've just been using it for the first commit, mostly to generate the changelog, then the rest by hand.

**Comment by TomSweeneyRedHat** [comment]
All green if you want to merge this or I can touch up the 1.9.0-dev if you'd like.  If not I'll do a follow on PR.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
