### PR TITLE
Tests tools bump

### PR DESCRIPTION
**Pull request by kolyshkin**
/kind cleanup

#### What this PR does / why we need it:

Some vendoring bumps and simplifications for tests/tools.

This is a followup to #3717, addressing TODO in https://github.com/containers/buildah/pull/3717#issuecomment-1015042870 and a few more things (see individual commits for details).

#### How to verify it

CI should be sufficient

#### Which issue(s) this PR fixes:

none

#### Special notes for your reviewer:

Please review commit-by-commit, and see individual commit messages for details.

⚠️ See also: https://github.com/containers/buildah/issues/3722 (needs to be implemented before merging this)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
I have had temporary commit added to check if the new subject line length check it working, and it is! (see 
https://github.com/containers/buildah/actions/runs/1721490520)

**Comment by flouthoc** [comment]
LGTM

**Comment by kolyshkin** [comment]
rebased

**Comment by TomSweeneyRedHat** [comment]
@cevich PTAL

**Pull request merged**
