### PR TITLE
Cirrus: Make use of shared get_ci_vm container

### PR DESCRIPTION
**Pull request by cevich**
***Note***: An updated version of common automation tooling required, also included in new VM images.

Depends on:
    https://github.com/containers/automation_images/pull/57
    https://github.com/containers/automation/pull/64
    https://github.com/containers/automation/pull/66
    https://github.com/containers/automation/pull/67
    https://github.com/containers/automation/pull/68

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@rhatdan it is, but...TBH the script here is tiny.  It's just the front-end to a container image (with 1000+ lines of bash) that haven't been reviewed: https://github.com/containers/automation_images/pull/57  @edsantiago is probably the only other person with sufficient willpower to stomach staring at that much bash.  **OTOH**, this is a "hack", so maybe results (it works) are more important than pretty-code?

My intention [was to demo it using podman](https://github.com/containers/podman/pull/9840) today, since I would at least like to get some user-experience feedback.  But I'll likely be out at the clinic getting vaccinated :confused:

**Comment by cevich** [comment]
> I'm confused here.

[The podman PR](https://github.com/containers/podman/pull/9840) is likely easier to look at.  I didn't add/remove any tests, just did some renaming and re-arranging of `.cirrus.yml` to make it compatible with `get_ci_vm` (basically make it use standard YAML, not Cirrus-YAML).

In all cases, `hack/get_ci_vm.sh` was growing unwieldy, being duplicated across all repositories using Cirrus-CI.  The implementation here (and in the podman PR), makes use of a container to allow sharing all the common bits, and support better CI testing. [ That work is all over in an automation_images PR](https://github.com/containers/automation_images/pull/57), where all the juicy code (and tests) are.

> get_ci_vm (which I've never been able to understand or use)

Think of it as a Cirrus-CI manual-override, it lets developers get into a VM and execute `XYZ_script:` instructions (from the YAML) exactly as automation does.  It supports developers going hands-on in a 98% identical environment to CI, instrumenting code, running in debug-mode, etc.  This is needed (sometimes) because the VM's we run for all upstream CI are customized with bleeding-edge dependencies.  Therefor, it's easily possible to encounter problems in PRs with CI, before they present themselves in downstream distribution channels.

So, since you're mainly focused on downstream work, it's probably fine and normal that you don't need/use this tool.  It's also a "hack", and so I'm also okay if you're "too busy with more important stuff" to take a look.  Otherwise, as always, I appreciate any feedback you can provide.

**Comment by cevich** [comment]
rebased and force-pushed w/ a minor safety-related change to the get_ci_vm interface.

**Comment by TomSweeneyRedHat** [comment]
@cevich conformance tests are less than happy

**Comment by cevich** [comment]
Ooof, what did I break...

**Comment by cevich** [comment]
...whew, it was just a flake of some sort.

**Comment by cevich** [comment]
Rebased with minor addition to support easier debugging.

**Comment by cevich** [comment]
I think this is ready to go in.  [It's probably too much to ask](https://github.com/containers/automation_images/pull/57) @edsantiago to review at this time, I'm okay with that.  I'll just have to implement fixes as-found or as-needed.  More than likely I'll be able to do that in the container image, instead of inside every single repo. like before.

**Pull request merged**
