### PR TITLE
[skip-ci] [release-1.24] Packit: enable pre-merge copr builds and TMT tests

### PR DESCRIPTION
**Pull request by lsm5**
#### What type of PR is this?

 /kind other

#### What this PR does / why we need it:

adds packit el8 rpm build tasks to check for buildability.

#### How to verify it

check if packit tasks are successful

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
validate test using packit+tmt is blocked on https://github.com/teemtee/tmt/issues/2444

**Comment by lsm5** [comment]
skipping cirrus runs for this as we're more concerned with packit+tmt

**Comment by lsm5** [comment]
unit tests are also blocked on tmt supporting git metadata in test envs.

**Comment by rhatdan** [comment]
@lsm5 Is this still active?

**Comment by lsm5** [comment]
Closing for now. WIll reopen if we still need it.

**Comment by TomSweeneyRedHat** [comment]
release 1.24 is in RHEL 8.6 and 9.0, both very supported and for quite a while yet.

**Pull request closed without merging**
