### PR TITLE
Buildah bud should not use stdin by default

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/8066
Is reporting that buildah is eating stdin.  I don't beleive
we should be using stdin when doing a buildah bud command
unless `buildah bud -` is specified.  After this PR, the
`-` Dockerfile is still handled.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/buildah/issues/2705

**Comment by nalind** [comment]
LGTM, though this does add a difference between how we handle RUN instructions and `buildah run`.

**Comment by rhatdan** [comment]
I think that is ok.  The question I have is should we add an --interactive mode to docker build to add stdin back in.
I know where have an issue somewhere talking about how `buildah bud` or `podman build` hung waiting for input from apt-update.
If we added `-i` flag then dnf update and other commands could wait for user input.

**Comment by edsantiago** [comment]
LGTM. Could you add this test, or something equivalent?
```bash
@test "bud does not gobble stdin" {
  _prefetch alpine

  ctxdir=${TESTDIR}/bud
  mkdir -p $ctxdir
  cat >$ctxdir/Dockerfile <<EOF
FROM alpine
RUN true
EOF

  random_msg=$(head -10 /dev/urandom | tr -dc a-zA-Z0-9 | head -c12)

  # Prior to #2708, buildah bud would gobble up its stdin even if it
  # didn't actually use it. This prevented the use of 'cmdlist | bash';
  # if 'buildah bud' was in cmdlist, everything past it would be lost.
  #
  # This is ugly but effective: it checks that buildah passes stdin untouched.
  passthru=$(echo "$random_msg" | (run_buildah bud --quiet --signature-policy ${TESTSDIR}/policy.json -t stdin-test ${ctxdir} >/dev/null; cat))

  expect_output --from="$passthru" "$random_msg" "stdin was passed through"
}
```

**Comment by edsantiago** [comment]
P.S. the test (as expected) fails on current master, passes with this PR.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @edsantiago @vrothberg @giuseppe @ashley-cui This is ready to go in.  Merge me.

**Comment by hansborr** [comment]
> I think that is ok. The question I have is should we add an --interactive mode to docker build to add stdin back in.
> I know where have an issue somewhere talking about how `buildah bud` or `podman build` hung waiting for input from apt-update.
> If we added `-i` flag then dnf update and other commands could wait for user input.

I would like to see this added.

This change broke something for me -- I used to have a bud file which prompted for user input during the RUN stage (running smbpasswd).
This was to avoid having a cleartext password in the file, but to allow the hashed password to be baked into the image.

After updating to the newest buildah, that no longer works.

I was able to work around it, but I expect there are probably other people who will encounter this.

**Comment by rhatdan** [comment]
Interested in opening a PR, it is actually a fairly easy change to add an option for this.

BTW, Please open an issue for this anyways, rather then in this closed PR.

**Pull request merged**
