### PR TITLE
Stop littering

### PR DESCRIPTION
**Pull request by edsantiago**
Don't touch the test source dir (I missed one in #3841).

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
This was probably done by me.  I make this mistake all the time.

LGTM

**Comment by edsantiago** [comment]
I didn't `git blame`, and see no reason to. It seems impossible *not* to make the mistake, given the similarity between `TESTDIR` and `TESTSDIR`.

**Review by flouthoc — APPROVED** [review]
/lgtm
/hold

**Pull request merged**
