### PR TITLE
Reduce --label arguments to a single layer

### LINKED ISSUE #3370: rebuild labels with build --label
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If the image has been built with dynamic --labels, the next build with other dynamic labels does not neforce rebuild of labels layer

**Steps to reproduce the issue:**

```
$ podman -v; set -x; podman image rm podman_issue; podman build -t podman_issue . --label "dynamic_label1=value1"; echo ""; podman inspect podman_issue --format "LABEL {{ .Config.Labels.dynamic_label1 }};{{ .Labels.dynamic_label1 }}"; podman build -t podman_issue . --label "dynamic_label1=value2"; echo ""; podman inspect podman_issue --format "LABEL {{ .Config.Labels.dynamic_label1 }};{{ .Labels.dynamic_label1 }}"; podman image rm podman_issue; podman build -t podman_issue . --label "dynamic_label1=value2"; echo ""; podman inspect podman_issue --format "LABEL {{ .Config.Labels.dynamic_label1 }};{{ .Labels.dynamic_label1 }}"; set +x
```
```
podman version 3.1.2
+ podman image rm podman_issue
Untagged: localhost/podman_issue:latest
Deleted: 4391583b1b31d53ed3f64c86dfb29cbdb7635856431034e30e3bd99d111c7cca
+ podman build -t podman_issue . --label dynamic_label1=value1
STEP 1: FROM docker.io/adoptopenjdk/openjdk11:alpine-jre
STEP 2: CMD ls -la .
STEP 3: COMMIT podman_issue
--> 504c4f91411
504c4f914111e239a0465855d9ef418d692e3a1e327d8d24e1278995ced17259
+ echo ''

+ podman inspect podman_issue --format 'LABEL {{ .Config.Labels.dynamic_label1 }};{{ .Labels.dynamic_label1 }}'
LABEL value1;value1
+ podman build -t podman_issue . --label dynamic_label1=value2
STEP 1: FROM docker.io/adoptopenjdk/openjdk11:alpine-jre
STEP 2: CMD ls -la .
--> Using cache 504c4f914111e239a0465855d9ef418d692e3a1e327d8d24e1278995ced17259
STEP 3: COMMIT podman_issue
--> 504c4f91411
504c4f914111e239a0465855d9ef418d692e3a1e327d8d24e1278995ced17259
+ echo ''

+ podman inspect podman_issue --format 'LABEL {{ .Config.Labels.dynamic_label1 }};{{ .Labels.dynamic_label1 }}'
LABEL value1;value1
+ podman image rm podman_issue
Untagged: localhost/podman_issue:latest
Deleted: 504c4f914111e239a0465855d9ef418d692e3a1e327d8d24e1278995ced17259
+ podman build -t podman_issue . --label dynamic_label1=value2
STEP 1: FROM docker.io/adoptopenjdk/openjdk11:alpine-jre
STEP 2: CMD ls -la .
STEP 3: COMMIT podman_issue
--> e36b8938983
e36b89389833bbd5eb7578fde3cc5c549684230ab7fc5614bcb1a54eaeb3649a
+ echo ''

+ podman inspect podman_issue --format 'LABEL {{ .Config.Labels.dynamic_label1 }};{{ .Labels.dynamic_label1 }}'
LABEL value2;value2
+ set +x

```

**Describe the results you received:**

The label value is set only if image is rebuild becaus of lower layers are missing/changed

**Describe the results you expected:**

The dynamic labels on command line for build should enforce label layer recreation.

**Additional information you deem important (e.g. issue happens only occasionally):**

docker works as expected

**Output of `podman version`:**

```
podman version 3.1.2
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-2.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 12
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.16-200.fc33.x86_64
  linkmode: dynamic
  memFree: 454234112
  memTotal: 16358834176
  ociRuntime:
    name: crun
    package: crun-0.19.1-2.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc33.x86_64
    version: |-
      slirp4netns version 1.1.9
      commit: 4e37ea557562e0d7a64dc636eff156f64927335e
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 98h 43m 48.14s (Approximately 4.08 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/dosmanak/.config/containers/storage.conf
  containerStore:
    number: 18
    paused: 0
    running: 0
    stopped: 18
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.5
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/dosmanak/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 20
  runRoot: /run/user/1000/containers
  volumePath: /home/dosmanak/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1619097693
  BuiltTime: Thu Apr 22 15:21:33 2021
  GitCommit: ""
  GoVersion: go1.15.8
  OsArch: linux/amd64
  Version: 3.1.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.1.2-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical as seen from info --debug

### PR DESCRIPTION
**Pull request by cbandy**
#### What type of PR is this?

/kind api-change

#### What this PR does / why we need it:

#3517 fixed #3370 by adding a step/layer for every `--label` argument which matches the behavior of Docker build. Buildkit, however, does not add any layer for `--label` arguments.

Rather than clutter an image with empty layers, we can combine label arguments in a single layer.

#### How to verify it

Compare different tools using the following Dockerfile and arguments.

```dockerfile
FROM alpine
LABEL \
  file1=one \
  file2=two
```

```sh-session
# Without this PR
$ buildah build --layers --tag cbandy:latest --label arg1=one --label arg2=two .
STEP 1/4: FROM alpine
STEP 2/4: LABEL   file1=one   file2=two
--> 031d0e5ee40
STEP 3/4: LABEL "arg1"="one"
--> c35ed1cd582
STEP 4/4: LABEL "arg2"="two"
COMMIT cbandy:latest
--> 8dc4f003578
Successfully tagged localhost/cbandy:latest
8dc4f0035785abfe7d75ac683b0ce21a1b1f020bc58951dff2b21472ee78a907

$ podman history cbandy:latest
ID            CREATED        CREATED BY                                     SIZE        COMMENT
e66264b98777  3 seconds ago  /bin/sh -c #(nop) LABEL "arg2"="two"           0 B         FROM c35ed1cd5823
<missing>     3 seconds ago  /bin/sh -c #(nop) LABEL "arg1"="one"           0 B         FROM 031d0e5ee405
<missing>     3 seconds ago  /bin/sh -c #(nop) LABEL   file1=one   file...  0 B         FROM docker.io/library/alpine:latest
<missing>     5 days ago     /bin/sh -c #(nop)  CMD ["/bin/sh"]             0 B         
<missing>     5 days ago     /bin/sh -c #(nop) ADD file:8e81116368669ed...  5.81 MB
```

```sh-session
# With this PR
$ buildah build --layers --tag cbandy:latest --label arg1=one --label arg2=two .
STEP 1/3: FROM alpine
STEP 2/3: LABEL   file1=one   file2=two
--> 56fc28a1e56
STEP 3/3: LABEL "arg1"="one" "arg2"="two"
COMMIT cbandy:latest
--> d2418033201
Successfully tagged localhost/cbandy:latest
d2418033201681ccc30b7a3bce2c2f70a6e7816c5867c8d38f7ce602f7bda20e

$ podman history cbandy:latest
ID            CREATED        CREATED BY                                     SIZE        COMMENT
e66264b98777  4 seconds ago  /bin/sh -c #(nop) LABEL "arg1"="one" "arg2...  0 B         FROM 56fc28a1e566
<missing>     4 seconds ago  /bin/sh -c #(nop) LABEL   file1=one   file...  0 B         FROM docker.io/library/alpine:latest
<missing>     5 days ago     /bin/sh -c #(nop)  CMD ["/bin/sh"]             0 B         
<missing>     5 days ago     /bin/sh -c #(nop) ADD file:8e81116368669ed...  5.81 MB
```

```sh-session
$ docker buildx build --tag cbandy:latest --label arg1=one --label arg2=two .
…

$ docker history cbandy:latest
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
ef9cbb8f3175        5 days ago          LABEL file1=one file2=two                       0B                  buildkit.dockerfile.v0
<missing>           5 days ago          /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B                  
<missing>           5 days ago          /bin/sh -c #(nop) ADD file:8e81116368669ed3d…   5.52MB
```

#### Which issue(s) this PR fixes:

None

### CODE REVIEW

**Review by flouthoc — COMMENTED** [review]
I think one problem is that we will miss cache hit if order of label is changed and now with this PR the behavior of buildah differs from both buildkit and docker.

Could you let us know the issues caused by the existing behavior.

**Comment by nalind** [comment]
Labels are unordered in the image config, so I don't really have a problem with us running `sort.Strings()` on `options.Labels` before iterating through it to put them into a predictable order on the line that we synthesize.
I don't know that we've ever tested with more than one `--label` option on the `buildah build` command line, or that the build cache currently still gets a "hit" if the order of multiple `--label` options on the `buildah build` command line is changed, so if the tests don't complain, I don't think it breaks anything.

**Comment by cbandy** [comment]
> Could you let us know the issues caused by the existing behavior.

I like that `--label` arguments allow me to annotate images without having to go through `--build-arg` and `ARG` and `LABEL` instructions. I like that BuildKit and buildah v1.23.0 do so without adding to the history.

I was bitten by #3370 a few times and appreciate that was fixed in buildah v1.24.0. But now the history of my images is full of `LABEL` instructions.

> I think one problem is that we will miss cache hit if order of label is changed

If I understand correctly, this is true both before and after this PR. Note the args and missing cache messages in the third invocation:

```sh-session
# Without this PR
$ buildah build --layers --tag cbandy:latest --label arg1=one --label arg2=two .
…

$ buildah build --layers --tag cbandy:latest --label arg1=one --label arg2=two .
STEP 1/4: FROM alpine
STEP 2/4: LABEL   file1=one   file2=two
--> Using cache 56fc28a1e5669b7629007a01bd794fffa1fc1382143c0c852868dbb171bef50a
--> 56fc28a1e56
STEP 3/4: LABEL "arg1"="one"
--> Using cache 8c8cd32262c81cfccc989fea54f330817f08e2d2cc37bd583e3aaccf083afe30
--> 8c8cd32262c
STEP 4/4: LABEL "arg2"="two"
--> Using cache c4932f6355b9378abe448ca8d8a02cf972903baeb22d1763df7a3193fabb83da
COMMIT cbandy:latest
--> c4932f6355b
Successfully tagged localhost/cbandy:latest
c4932f6355b9378abe448ca8d8a02cf972903baeb22d1763df7a3193fabb83da

$ buildah build --layers --tag cbandy:latest --label arg2=two --label arg1=one .
STEP 1/4: FROM alpine
STEP 2/4: LABEL   file1=one   file2=two
--> Using cache 56fc28a1e5669b7629007a01bd794fffa1fc1382143c0c852868dbb171bef50a
--> 56fc28a1e56
STEP 3/4: LABEL "arg2"="two"
--> dc36ade8ba4
STEP 4/4: LABEL "arg1"="one"
COMMIT cbandy:latest
--> 821ecad1fde
Successfully tagged localhost/cbandy:latest
821ecad1fde81ae39f46c70ee826805060d6489c3b21db906f72e42b1dcf05f3
```

> with this PR the behavior of buildah differs from both buildkit and docker.

Agreed.

Looking more closely at the output of `docker build`, I see `buildah build` still differs with regard to caching. Regardless of the argument order `docker build` prints:

```
Step 3/4 : LABEL arg1=one
 ---> Using cache
 ---> a37a055bdea2
Step 4/4 : LABEL arg2=two
 ---> Using cache
 ---> 316a2a04c383
```

**Comment by cbandy** [comment]
> Labels are unordered in the image config, so I don't really have a problem with us running `sort.Strings()` on `options.Labels` before iterating through it to put them into a predictable order

Should the code in this PR sort `options.Labels` in-place, or make a copy then sort, or should something else sort the slice long before here?

> I don't know that we've ever tested with more than one `--label` option on the `buildah build` command line, or that the build cache currently still gets a "hit" if the order of multiple `--label` options on the `buildah build` command line is changed

I'm not familiar with the test suite, but I also don't see any in `bud.bats`. 🧐 It looks like `bud-multistage-relabel` could change a bit to cover this.

**Comment by nalind** [comment]
> > Labels are unordered in the image config, so I don't really have a problem with us running `sort.Strings()` on `options.Labels` before iterating through it to put them into a predictable order
> 
> Should the code in this PR sort `options.Labels` in-place, or make a copy then sort, or should something else sort the slice long before here?

I lean toward making a copy in the same place, and sorting it there.  We copy the slice out of the `options` struct in `newExecutor()`, and that copy is what the build cache has on-hand when it's doing its thing, so I'd prefer it if they didn't end up in different orders.
 
> > I don't know that we've ever tested with more than one `--label` option on the `buildah build` command line, or that the build cache currently still gets a "hit" if the order of multiple `--label` options on the `buildah build` command line is changed
> 
> I'm not familiar with the test suite, but I also don't see any in `bud.bats`. monocle_face It looks like `bud-multistage-relabel` could change a bit to cover this.

Agreed, that looks like a good place to do it.

**Comment by cbandy** [comment]
> We copy the slice out of the `options` struct in `newExecutor()`, and that copy is what the build cache has on-hand when it's doing its thing, so I'd prefer it if they didn't end up in different orders.

I see where you're talking about, but I'm getting a bit out of my depth. I see other slices that I suspect are also key/value pairs. Would `annotations` and `envs` need the same treatment? Perhaps someone else is better equipped to address caching separately from this PR about history?

https://github.com/containers/buildah/blob/fb28761ceb01e3e9050d3567bac721dabdb5953d/imagebuildah/executor.go#L251-L252

https://github.com/containers/buildah/blob/fb28761ceb01e3e9050d3567bac721dabdb5953d/imagebuildah/executor.go#L284-L288

**Comment by rhatdan** [comment]
@flouthoc any chance you can work on this?

**Comment by flouthoc** [comment]
@cbandy are you still working on this ? If you are fine I can take over this PR and include your commit.

**Comment by cbandy** [comment]
> @cbandy are you still working on this ? If you are fine I can take over this PR and include your commit.

@flouthoc I have nothing new for this. Please feel free.

**Comment by rhatdan** [comment]
@flouthoc any time to work on this?

**Comment by flouthoc** [comment]
Yes I'll cherry-pick the commits.

**Comment by rhatdan** [comment]
@flouthoc Did you ever get a chance to look at this?

**Comment by flouthoc** [comment]
I think @nalind has already implemented this here https://github.com/containers/buildah/pull/4511, hence closing this please re-open if i am mistaken.

**Pull request closed without merging**
