### PR TITLE
run: fix nil deref using the option's logger

### PR DESCRIPTION
**Pull request by vrothberg**
[NO TESTS NEEDED] since I've no idea how to force it.

Reported-in: containers/podman/issues/11148
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
@TomSweeneyRedHat @ashley-cui PTAL

**Comment by rhatdan** [comment]
@saschagrunert @giuseppe @containers/podman-maintainers PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
