### PR TITLE
chore: Enable codeql action

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This action runs GitHub's industry-leading semantic code analysis engine, CodeQL, against a repository's source code to find security vulnerabilities.

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql

https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@cevich 👀

**Comment by flouthoc** [comment]
Thanks @naveensrinivasan , I'll wait for @cevich to take a look.

But before merging this we must fix `codeql` feedbacks or maybe in this PR otherwise this blocks CI for others.

**Comment by rhatdan** [comment]
Can this be changed to not check the test and vendor directories?

**Comment by naveensrinivasan** [comment]
> Can this be changed to not check the test and vendor directories?

AFAIK this can be done for non `go` or interpreted languages https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-directories-to-scan

I don't know if the setting would work for `go`. I can still try 🤷 . I can try that later today or tomorrow.

**Comment by TomSweeneyRedHat** [comment]
@naveensrinivasan looks like you need a rebase

**Comment by rhatdan** [comment]
In Podman we agreed this should be done via a Linter, but requires no check on handling of paths from users.

**Pull request closed without merging**
