### PR TITLE
[release-1.21] Bump c/common to v0.38.11 and c/storage to v1.31.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Bumping c/common to v0.38.11 and c/storage to v1.31.1 to match the variants in Podman v3.2 to ready for RHEL 8.4.0.2 release.

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Vendor Dance in play for RHEL 8.4.0.2
@containers/buildah-maintainers PTAL
FYI @mheon

**Comment by TomSweeneyRedHat** [comment]
FYI @jnovy, once this merges, we'll spin Buildah v1.21.2 for RHEL 8.4.0.2

**Comment by TomSweeneyRedHat** [comment]
@cevich @edsantiago @rhatdan Do any of you know why the arch test would be failing trying to find the alpine image on the localhost?  Seems to be doing so on all the failing tests I looked at:

```
+0856s] not ok 234 bud with --arch flag
[+0856s] # (from function `die' in file ./helpers.bash, line 205,
[+0856s] #  from function `run_buildah' in file ./helpers.bash, line 192,
[+0856s] #  in test file ./bud.bats, line 2665)
[+0856s] #   `run_buildah bud --arch=arm64 -t arch-test --signature-policy ${TESTSDIR}/policy.json ${mytmpdir} <<< input' failed with status 125
[+0856s] # /var/tmp/go/src/github.com/containers/buildah/tests /var/tmp/go/src/github.com/containers/buildah/tests
[+0856s] # # [checking for: alpine]
[+0856s] # # [restoring from cache: /var/tmp/buildah-image-cache.7329 / alpine]
[+0856s] # Getting image source signatures
[+0856s] # Copying blob sha256:9450ef9feb156181f280a72a2a6c20ba2d2cbe7af0a251b1a0ad28008308767b
[+0856s] # Copying config sha256:1f97f0559cbddbff6c872039e93f18c1abdc279cbe82e0eb40258c28f4c30bfd
[+0856s] # Writing manifest to image destination
[+0856s] # Storing signatures
[+0856s] # Loaded image(s): localhost/alpine
[+0856s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah bud --arch=arm64 -t arch-test --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json /var/tmp/tmp0166c598277da08b926f25b3/my-dir
[+0856s] # STEP 1: FROM alpine
[+0856s] # Trying to pull localhost/alpine:latest...
[+0856s] # time="2021-06-25T22:50:24Z" level=warning msg="failed, retrying in 2s ... (1/3). Error: Error initializing source docker://localhost/alpine:latest: error pinging docker registry localhost: Get \"https://localhost/v2/\": dial tcp 127.0.0.1:443: connect: connection refused"
[+0856s] # time="2021-06-25T22:50:26Z" level=warning msg="failed, retrying in 2s ... (2/3). Error: Error initializing source docker://localhost/alpine:latest: error pinging docker registry localhost: Get \"https://localhost/v2/\": dial tcp 127.0.0.1:443: connect: connection refused"
[+0856s] # time="2021-06-25T22:50:28Z" level=warning msg="failed, retrying in 2s ... (3/3). Error: Error initializing source docker://localhost/alpine:latest: error pinging docker registry localhost: Get \"https://localhost/v2/\": dial tcp 127.0.0.1:443: connect: connection refused"
[+0856s] # error creating build container: Error initializing source docker://localhost/alpine:latest: error pinging docker registry localhost: Get "https://localhost/v2/": dial tcp 127.0.0.1:443: connect: connection refused
[+0856s] # [ rc=125 (** EXPECTED 0 **) ]
[+0856s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+0856s] # #| FAIL: exit code is 125; expected 0
[+0856s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+0856s] # /var/tmp/go/src/github.com/containers/buildah/tests
```

**Comment by TomSweeneyRedHat** [comment]
And just in case it's not obvious, this is happening in the release-1.2 and not the main branch.  Are there necessary tweaks missing here for localhost?

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
v0.38.4 is too old. We need to use v0.38.11; that’s what Podman v3.2.2 uses.

**Comment by TomSweeneyRedHat** [comment]
My bad on the commit/description.  I put in 38.4 in both places, but I had bumped to 38.11.  I've touched that up.

**Comment by vrothberg** [comment]
> My bad on the commit/description. I put in 38.4 in both places, but I had bumped to 38.11. I've touched that up.

Ah, sorry, I was purely parsing the title.  I'll investigate what's going on.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/common/pull/651. Really curious since I tested the changed against Buildah main before.

**Comment by vrothberg** [comment]
Yes, it really passes Buildah master (https://github.com/containers/buildah/pull/3342) without any fix. Seems like _something_ changed in the tests which ultimately doesn't hit the bug (i.e., a localhost/alpine in storage).

**Comment by vrothberg** [comment]
Opened https://github.com/containers/buildah/pull/3346 with the update c/common.

**Pull request closed without merging**
