### PR TITLE
vndr opencontainers/selinux

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @vrothberg @giuseppe @umohnani8 PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
