### PR TITLE
Update golangci-lint, its config, and fix some warnings

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Currently, golangci-lint used by this repo is old, and its configuration is unsafe (for updates, that it).

Fix both issues, run the updated linter, fix some of its warnings (surely those fixes come first to not break git-bisect).

Please see individual commits for details.

#### How to verify it

I hope that CI that runs on PRs is sufficient.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Some of the fixes are not too trivial, so a careful review is appreciated.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
TODO (once this is merged):
 - update other deps in test/tools
 - add test/tools to dependabot config

**Comment by rhatdan** [comment]
@nalind PTAL
Changes other then tests not running LGTM

**Comment by nalind** [comment]
Changes LGTM, but it looks like parts of `tests/tools/vendor` weren't included in the commit that updated other parts of it.

**Comment by TomSweeneyRedHat** [comment]
LGTM once tests are happy

**Comment by kolyshkin** [comment]
> it looks like parts of `tests/tools/vendor` weren't included in the commit that updated other parts of it.

It seems I will never be able to do `git add vendor` from the first try 🤦🏻 

Updated.

**Comment by kolyshkin** [comment]
Ah, now top-level .gitignore stands in a way of proper vendoring. Fixed.

**Comment by kolyshkin** [comment]
@vrothberg can you please review the https://github.com/containers/buildah/pull/3717/commits/0b86b161636b6ad3e733dfba0bcd474004432c89?

**Comment by kolyshkin** [comment]
It seems like fedora CI failure is a temp glitch (quay.io timeout). Can someone please restart it?

[+2834s] not ok 535 pull image with TMPDIR set
[+2834s] # (from function `die' in file ./helpers.bash, line 250,
[+2834s] #  from function `run_buildah' in file ./helpers.bash, line 237,
[+2834s] #  in test file ./pull.bats, line 366)
[+2834s] #   `run_buildah pull --policy always --signature-policy ${TESTSDIR}/policy.json quay.io/libpod/alpine_nginx:latest' failed with status 125
[+2834s] # /var/tmp/go/src/github.com/containers/buildah/tests /var/tmp/go/src/github.com/containers/buildah/tests
[+2834s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah pull --policy always --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json quay.io/libpod/alpine_nginx:latest
[+2834s] # Trying to pull quay.io/libpod/alpine_nginx:latest...
[+2834s] # Getting image source signatures
[+2834s] # Copying blob sha256:ac35fae19c6cb4820a5745bd6ce22fb9fe38c4d7e2225e184315cb4bc5e9ece8
[+2834s] # Copying blob sha256:4c0d98bf9879488e0407f897d9dd4bf758555a78e39675e72b5124ccf12c2580
[+2834s] # Copying blob sha256:5b0fccc9c35f7ea2f4a1c876e0a0be91677a378eb07361ba3e48ca86565d5790
[+2834s] # Copying blob sha256:4c0d98bf9879488e0407f897d9dd4bf758555a78e39675e72b5124ccf12c2580
[+2834s] # Copying blob sha256:ac35fae19c6cb4820a5745bd6ce22fb9fe38c4d7e2225e184315cb4bc5e9ece8
[+2834s] # Copying blob sha256:5b0fccc9c35f7ea2f4a1c876e0a0be91677a378eb07361ba3e48ca86565d5790
[+2834s] # writing blob: storing blob to file "/var/tmp/buildah_tests.ymqwhm/buildah-test/storage060557362/1": write /var/tmp/buildah_tests.ymqwhm/buildah-test/storage060557362/1: no space left on device
[+2834s] # [ rc=125 (expected) ]
[+2834s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah pull --policy always --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json quay.io/libpod/alpine_nginx:latest
[+2834s] # Trying to pull quay.io/libpod/alpine_nginx:latest...
[+2834s] # Getting image source signatures
[+2834s] # Copying blob sha256:4c0d98bf9879488e0407f897d9dd4bf758555a78e39675e72b5124ccf12c2580
[+2834s] # Copying blob sha256:5b0fccc9c35f7ea2f4a1c876e0a0be91677a378eb07361ba3e48ca86565d5790
[+2834s] # Copying blob sha256:ac35fae19c6cb4820a5745bd6ce22fb9fe38c4d7e2225e184315cb4bc5e9ece8
[+2834s] # Copying blob sha256:5b0fccc9c35f7ea2f4a1c876e0a0be91677a378eb07361ba3e48ca86565d5790
[+2834s] # Copying blob sha256:4c0d98bf9879488e0407f897d9dd4bf758555a78e39675e72b5124ccf12c2580
[+2834s] # reading blob sha256:ac35fae19c6cb4820a5745bd6ce22fb9fe38c4d7e2225e184315cb4bc5e9ece8: Get "https://cdn02.quay.io/sha256/ac/ac35fae19c6cb4820a5745bd6ce22fb9fe38c4d7e2225e184315cb4bc5e9ece8?Expires=1642546144&Signature=E5~djLnUfA~pnSYnJ20lvLdLm3vEpMqOLfqWB4a7j9hYosc3aKX1kdjHZhVJbHgifjYyo4Y1Ss5Fe2gSGC4AkK6fL6P9bgbjiqH0zX2RKUtZSdJa9JXAYm2aRH35ChgE50gjAFuSarAgZIKujL28kLbACQVzF2aoO6uExP0WZFWwh56zhMmGcF~5R4srNfXXChZg0-zdniSjDCCYyB~DP0Wgg3Eqxx0DMSwBezcUE20AJgwT21uea79PaSDWwzKauGhFp3dPgpzEfLmnbBKB1D7RXlzC23dJOnH-dJ75d6Wb0KxJWS5bn8F2huro1JjcvvIobbbgxDoxH~-euTwvQw__&Key-Pair-Id=APKAJ67PQLWGCSP66DGA": net/http: TLS handshake timeout
[+2834s] # [ rc=125 (** EXPECTED 0 **) ]
[+2834s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+2834s] # #| FAIL: exit code is 125; expected 0
[+2834s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+2834s] # /var/tmp/go/src/github.com/containers/buildah/tests

**Comment by kolyshkin** [comment]
"Unit tests w/ vfs" job timed out after 60 minutes. A flake?

**Comment by vrothberg** [comment]
> @vrothberg can you please review the [0b86b16](https://github.com/containers/buildah/commit/0b86b161636b6ad3e733dfba0bcd474004432c89)?

LGTM, thanks for cleaning up!

**Comment by vrothberg** [comment]
Restarted both failed jobs; looked like flakes to me.

**Pull request merged**
