### PR TITLE
[WIP] Vendor a branch of c/common to test Pasta as default

### PR DESCRIPTION
**Pull request by mheon**
DO NOT MERGE: This switches to my branch of c/common to test Pasta as default rootless netns provider.

#### What type of PR is this?

/kind other

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Luap99** [comment]
Pretty sure you need to update the VMs here as well, pasta is likely to old here and still hangs:
https://github.com/containers/buildah/blob/8436ffdea5e587ad7633a3a9448b247c15b1af6c/.cirrus.yml#L35

**Comment by mheon** [comment]
I think they're the same? Podman is using f39f38d13 as well

**Comment by Luap99** [comment]
Check the date, 2024-02-01 so it was created before the pasta fixes.
f39f38d13 is just for the distro versions used.

**Comment by rhatdan** [comment]
This will blow up with the crun debian issue.

**Comment by Luap99** [comment]
Yes we can ignore the crun failures. I mostly want to look at the logs and see if we have any pasta failures.

**Comment by Luap99** [comment]
well so much for the nice and easy one
```
 pasta failed with exit code 1:
[+0926s] # No routable interface for IPv6: IPv6 is disabled
[+0926s] # Couldn't open network namespace /proc/65626/ns/net: Permission denied
[+0926s] # [ rc=125 (** EXPECTED 0 **) ]
```

I think this a selinux problem, easy to reproduce locally `buildah build --network pasta .` if you have Containerfile with a RUN instruction.

 I know it also fails in podman unless we do `chcon -t container_runtime_exec_t` on it? It seems buildah is labeled `system_u:object_r:bin_t:s0`, any reason why it is not  `container_runtime_exec_t` like podman?
If I change buildah to container_runtime_exec_t it works locally.
@rhatdan Do you know?

**Comment by rhatdan** [comment]
I think this is vendored, so closing.

**Pull request closed without merging**
