### PR TITLE
tests: copy.bats: fix infinite hang

### PR DESCRIPTION
**Pull request by edsantiago**
The ignore-socket test in copy.bats has to create a UNIX socket
file. As it turns out, mknod won't do that: there are only
horrible kludgy options. The least bad of those is to run 'nc'
and control-C it; we do this hands-off via background job.

Until now, the test then infinite-looped a 'test -e socketfile'.
This failed catastrophically in gating tests, because 'nc' was
not installed (it was not a requirement of the RPM) (it is now).
To make things worse, it took months to track this down because
the gating-test logs aren't flushed. But that's another story.

Here we add a fixed number of retries to the 'test -e' loop,
and abort with a timeout error if the socket isn't created.
This may save someone on a distro where nc hasn't yet been
added as a dependency.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
Tested by changing `nc` in line 265 to `xxnc`. The test died after five seconds, as expected.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM
But I would have thought/hoped the test would blow up right away when nc does not exists.

**Review by vrothberg — COMMENTED** [review]
LGTM
Restarted the flake.

**Pull request merged**
