### PR TITLE
conformance tests: use mirror.gcr.io for most images

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind failing-test 

#### What this PR does / why we need it:

Use busybox and alpine images from mirror.gcr.io, where possible, to avoid tripping pull limits in CI.

#### How to verify it

So many updated conformance tests!

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
@edsantiago if you can give this a quick looksee, I'd appreciate it.

**Comment by edsantiago** [comment]
I'm confused. There's already a `registries.conf` that fixes this. Is it not fixing it? What problem are we seeing?

**Comment by edsantiago** [comment]
hold on, I merged local-registry in #5584. We should absolutely not be using any network pulls any more! What's happening?

**Comment by nalind** [comment]
Conformance tests use `docker build` with the docker daemon and friends as the baseline, and they don't pay attention to registries.conf.  In order to use the same base images, the code paths that use buildah can't either.

**Comment by nalind** [comment]
Well, not `docker build` per se, but the REST API that the docker engine provides.

**Pull request merged**
