### PR TITLE
bump(github.com/containers/storage); bump(github.com/containers/image)

### PR DESCRIPTION
**Pull request by nalind**
Update `github.com/containers/storage` and `github.com/containers/image`, and modify `containerImageRef.NewImageSource()` to account for the change that the `io.ReadCloser` that `store.Diff()` returns now holds a lock until it's closed, and because that's the same lock that `store.PutLayer()` takes, we can't read more than one layer's contents at a time.

### CODE REVIEW

**Comment by nalind** [comment]
Currently vendors the proposed changes from https://github.com/containers/image/pull/505; this can't be merged until that one's been resolved.

**Comment by nalind** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@nalind What is the latest state on this?

**Comment by nalind** [comment]
@rhatdan The tests pass, so we're holding on this until https://github.com/containers/image/pull/505 is merged.

**Comment by nalind** [comment]
Rebased.

**Comment by nalind** [comment]
bot, retest this please

**Comment by nalind** [comment]
bot, retest this please

**Comment by nalind** [comment]
@rhatdan no longer a WIP, ready to merge.

**Comment by nalind** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
