### PR TITLE
Accept repositories on login/logout

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
We now synchronize the behavior with Podman and accept repositories during login and logout per default.
#### How to verify it
Login/logout with a repository and verify `auth.json`. Push and pull should use the credentials in the same way as the Podman integration tests described in https://github.com/containers/podman/pull/11054.
#### Which issue(s) this PR fixes:

Requires https://github.com/containers/buildah/pull/3410

#### Special notes for your reviewer:
Incorporates with https://github.com/containers/podman/pull/11054
#### Does this PR introduce a user-facing change?

```release-note
Accept repositories (and registry namespaces) on login/logout and during push/pull.
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
Once you get tests to pass.

**Comment by saschagrunert** [comment]
Needs https://github.com/containers/buildah/pull/3416 now

**Comment by TomSweeneyRedHat** [comment]
@saschagrunert once the testing works, this LGTM.   But, is this functionality going to be upstream in Podman, Skopeo, and Buildah today?  I don't want to add this into the release we're making today if it's not going to be in the other two.

**Comment by saschagrunert** [comment]
> @saschagrunert once the testing works, this LGTM. But, is this functionality going to be upstream in Podman, Skopeo, and Buildah today? I don't want to add this into the release we're making today if it's not going to be in the other two.

It's already part of upstream Podman and skopeo, so I expect it has to be merged here, too. :)

**Comment by rhatdan** [comment]
Doesn't currently build, would like to get this in before release.

**Pull request merged**
