### PR TITLE
Update github.com/openshift/imagebuilder vendoring

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat @vrothberg @giuseppe @QiWang19 PTAL

**Comment by TomSweeneyRedHat** [comment]
could you repush with an updated title please?
`Update github.com/openshift/imagebuilder vendoring`

builder->imagebuilder

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
bors retry

**Pull request closed without merging**
