### PR TITLE
man pages: clarify `rmi` removes dangling parents

### PR DESCRIPTION
**Pull request by kwshi**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

This PR clarifies that `buildah rmi` removes not just the image it is given but also any of its dangling parents. Documenting this behavior makes `buildah rmi` more explicit & therefore predictable.

#### How to verify it

Read it :D

#### Which issue(s) this PR fixes:

#3202

#### Special notes for your reviewer:

Sorry this took me so long to get to, despite being such a small change!

#### Does this PR introduce a user-facing change?

Yes (changes the man pages) but I think that's too minor to warrant a release note?  Not sure.

```release-note
NONE
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@kwshi Thanks for the PR.
Our CI system requires that all PR's are signed.  Can you do `git commit --amend -s`, fetch, rebase and push this again please?  In the future, just add the `-s` option to your `git commit` command and that will sign the PR for you.

**Comment by rhatdan** [comment]
Thanks
You must sign your PRs

git commit -a --amend -s
git push --force

**Comment by kwshi** [comment]
Ah I see; I mistakenly assumed having `commit.gpgsign = true` meant signing was done by default, so I was omitting the `-s`.  Hopefully this fixes.

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Pull request merged**
