### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**
Also backport changes from https://github.com/cri-o/cri-o/pull/4065/files#diff-1d37e48f9ceff6d8030570cd36286a61R189-R197

Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

#### What type of PR is this?

> /kind bug
> /kind feature

#### Does this PR introduce a user-facing change?

```release-note
Update nix pin with `make nixpkgs`
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@saschagrunert PTAL

**Review by saschagrunert — APPROVED** [review]
Code LGTM, but the CI seems unhappy.

**Comment by hswong3i** [comment]
> Code LGTM, but the CI seems unhappy.

The fail is related to gate, therefore no direct relationship with static build? At least my local build looks good:
```
$ sudo ./result/bin/buildah info
{
    "host": {
        "CgroupVersion": "v1",
        "Distribution": {
            "distribution": "ubuntu",
            "version": "20.04"
        },
        "MemFree": 1470844928,
        "MemTotal": 16348082176,
        "OCIRuntime": "runc",
        "SwapFree": 17179865088,
        "SwapTotal": 17179865088,
        "arch": "amd64",
        "cpus": 8,
        "hostname": "hswong3i-XPS-13-9300",
        "kernel": "5.8.8-050808-generic",
        "os": "linux",
        "rootless": false,
        "uptime": "1h 2m 2.03s (Approximately 0.04 days)"
    },
    "store": {
        "ContainerStore": {
            "number": 0
        },
        "GraphDriverName": "overlay",
        "GraphOptions": null,
        "GraphRoot": "/var/lib/containers/storage",
        "GraphStatus": {
            "Backing Filesystem": "extfs",
            "Native Overlay Diff": "true",
            "Supports d_type": "true",
            "Using metacopy": "false"
        },
        "ImageStore": {
            "number": 0
        },
        "RunRoot": "/var/run/containers/storage"
    }
}
```

**Comment by TomSweeneyRedHat** [comment]
LGTM
going to retest with bors, I couldn't find a definitive failure and can't imagine this change would create one in the tests.

**Comment by TomSweeneyRedHat** [comment]
bors retry

**Comment by rhatdan** [comment]
Please rebase and force push, to clean up CI system failures.

**Comment by rhatdan** [comment]
bors retry

**Pull request merged**
