### PR TITLE
Use reversed logo for dark theme in README

### PR DESCRIPTION
**Pull request by Sea-n**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Currently the name `buildah` only shows `     ah` in dark mode.

#### How to verify it

Open my forked repo: https://github.com/Sea-n/buildah#readme
And maybe change `<html data-color-mode="auto">` to `light` and `dark` to verify.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

No

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@Sea-n thanks for the PR.  This can't be merged now as the branch needed to be updated, and one of the CI tests failed.  I think it was a bogus test failure and I'm hoping the update I just kicked off will fix it.

FWIW, in Dark mode for me, prior to this change, the word "Build" was all in black.  I can clearly see it, at least while using Firefox, but I can understand how others might not pick it up as easily.  I do like the change that you have made, regardless, so once we get happy tests, we can move forward with this.

Thanks!

@mairin if you have a quick moment to take a peak, I'd appreciate it.

**Comment by Sea-n** [comment]
Oh thanks, I've rebase'd and force-pushed the commit.

With `#0d1117` background, `#000000` text is hidden on my built-in screen, but clear to see on my external display.
Sorry for make the assumption without testing through.

**Comment by mairin** [comment]
@TomSweeneyRedHat looks perfect to me!!!! Thank you for the fix @Sea-n!!

**Pull request merged**
