### PR TITLE
container.conf: support attributed string slices

### PR DESCRIPTION
**Pull request by vrothberg**
All `[]string`s in containers.conf have now been migrated to attributed string slices which require some adjustments in Buildah and Podman.

[NO NEW TESTS NEEDED]

#### What type of PR is this?

/kind feature

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but there's apparently some kind of merge conflict with vendor/modules.txt

**Comment by vrothberg** [comment]
Now vendoring c/common@main.

Ready from my end: @rhatdan @nalind @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by vrothberg** [comment]
One more run but I think the unit-test failures are legit.
Will have a look tomorrow.  I changed some very minor things in c/common which maybe are responsible.

**Comment by vrothberg** [comment]
Luuuucky me, it was a flake.

Ready to merge :heavy_check_mark:

**Pull request merged**
