### PR TITLE
Enable vendor checks in Travis

### PR DESCRIPTION
**Pull request by vrothberg**
It required some cleanups and preparation commits that I tried to break into small chunks to ease reviewing.

### CODE REVIEW

**Comment by vrothberg** [comment]
If everything works as expected, I will add documentation on top :) @TomSweeneyRedHat PTAL

**Comment by vrothberg** [comment]
> If everything works as expected, I will add documentation on top :)

@TomSweeneyRedHat, in which document shall I put the explanation of how we do vendoring? I'd copy the one from https://github.com/containers/libpod/blob/master/install.md#vendoring---dependency-management

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
@vrothberg I'd vote for dropping the vendor information into the Buildah install.md also, I'll add it just before the Configuration Files section (https://github.com/containers/buildah/blob/master/install.md#configuration-files)

**Comment by TomSweeneyRedHat** [comment]
And thanks for putting this together!

**Comment by TomSweeneyRedHat** [comment]
Ooops, "I'll add it" was supposed to be "I'd add it".  If you want me to do so, I can add it.

**Comment by vrothberg** [comment]
Sounds good! I will wrap up a PR tomorrow. It's pub time now in my timezone :^)

**Pull request closed without merging**
