### PR TITLE
buildah.spec.rpkg: initial addition

### PR DESCRIPTION
**Pull request by lsm5**
This specfile along with a webhook will trigger auto rpm builds on the
`rhcontainerbot/podman-next` copr after every upstream PR merge.

Useful for those who want to fetch the latest upstream buildah without
having to build from source.

This commit also gets rid of `contrib/rpm/buildah.spec` and
`tests/version.bats`.

Known issue: Currently fails to build for EL8 envs.

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

Successful run at https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4542963/ 

@nalind @rhatdan @flouthoc PTAL

#### What type of PR is this?

/kind other

#### What this PR does / why we need it:
This PR will trigger rpm builds for buildah on `rhcontainerbot/podman-next` copr on every merge to the main branch.

#### How to verify it
Check if new builds get triggered at https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
btw, are we already sending builds to any other copr besides `rhcontainerbot/podman-next` ? I see a webhook `https://copr.fedorainfracloud.org/webhooks/github/18082/b6f1f77e-7eb1-4114-9c52-14b786833301/` in the Settings that's been failing for quite some time now. I can get rid of it if we're not using it.

**Comment by rhatdan** [comment]
@cevich and @TomSweeneyRedHat or @flouthoc Might know about the github action.  Perhaps building images on quay?

**Comment by lsm5** [comment]
I'll look at getting rid of `contrib/rpm/buildah.spec`

**Comment by lsm5** [comment]
removed the stale spec file, let's see what blows up now :D

**Comment by lsm5** [comment]
@cevich just to confirm, this will build rpms using the `last merged PR` and not the `current in-progress PR`. So, this likely isn't a replacement for `build from scratch` at least in it's current state. Is that ok?

**Comment by lsm5** [comment]
> Oh yeah. Yep, once this goes "live" we need to update `contrib/buildahimage/upstream` to install the RPM instead of building from scratch. That will improve the multi-arch build-time by probably double. Big thanks @lsm5

@cevich ah ok, it uses the latest main branch itself, and not the in-progress PR in Containerfile. So we should be fine. Correct me if I'm wrong.

**Comment by lsm5** [comment]
I'll update `contrib/buildhaimage/upstream/Containerfile` in this PR

**Comment by lsm5** [comment]
RE: `make validate`: `rpm -qV shadow-utils` barfs in `buildah from buildah` but works on my local environment. Is that expected?

**Review by flouthoc — APPROVED** [review]
LGTM 

@lsm5 Could you rebase plz :)

**Pull request merged**
