### PR TITLE
vndr in latest containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
This version of containers/storage will allow us to use metadata copyup
in overlay file system.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by rhatdan** [comment]
@pixdrift @nalind @umohnani8 @giuseppe @boaz1337 PTAL

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
