### PR TITLE
tests: improve build-with-network-test

### PR DESCRIPTION
**Pull request by sstosh**
This test could be failed when we enable firewall.
To reduce the impact of firewall, we use "curl".

Signed-off-by: Toshiki Sonoda <sonoda.toshiki@fujitsu.com>

#### What type of PR is this?

/kind failing-test 

#### What this PR does / why we need it:

This test will be failed in proxy environment.

<details>
<summary>NG log</summary>

```
not ok 1 build-with-network-test
# (from function `die' in file helpers.bash, line 333,
#  from function `run_buildah' in file helpers.bash, line 320,
#  in test file ng.bats, line 12)
#   `run_buildah build $WITH_POLICY_JSON ${TEST_SCRATCH_DIR}' failed
# ~/buildah/tests ~/buildah/tests
# # [checking for: docker.io/library/alpine]
# # [copy docker://docker.io/library/alpine dir:/tmp/buildah-image-cache.387453/docker.io-library-alpine-]
# Getting image source signatures
# Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
# Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
# Writing manifest to image destination
# Storing signatures
# # [copy dir:/tmp/buildah-image-cache.387453/docker.io-library-alpine- containers-storage:docker.io/library/alpine]
# Getting image source signatures
# Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
# Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
# Writing manifest to image destination
# Storing signatures
# # /root/buildah/tests/../bin/buildah build --signature-policy /root/buildah/tests/policy.json /tmp/buildah_tests.kkxc75
# STEP 1/2: FROM alpine
# STEP 2/2: RUN ping -c 1 4.2.2.2
# PING 4.2.2.2 (4.2.2.2): 56 data bytes
#
# --- 4.2.2.2 ping statistics ---
# 1 packets transmitted, 0 packets received, 100% packet loss
# Error: building at STEP "RUN ping -c 1 4.2.2.2": while running runtime: exit status 1
# [ rc=1 (** EXPECTED 0 **) ]
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #| FAIL: exit code is 1; expected 0
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# ~/buildah/tests
```
</details>

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
@edsantiago WDYT?

**Review by edsantiago — COMMENTED** [review]
Once again, @sstosh, I apologize for taking so long to review... and apologize because I can't approve.

I don't think these cases are equivalent. I think the reason you're seeing a test failure is because you have a firewall that blocks outgoing ICMP, which is only incidentally related to proxies. I believe there are environments that block ICMP but not HTTP, and vice-versa, so this PR is just an unreliable heuristic.

I think a possible way to keep the original spirit of the test might be:
```bash
    gw=$(ip route | awk '$1 == "default" { print $3 }')
```
...and ping that. But maybe not; I can see cases where that would fail.

I'm not going to block, but I would like @nalind or @mheon or @flouthoc or @Luap99 to weigh in. I'm OK with any of y'all merging, I just think this needs a little more thought.

And, one comment inline. Again, I won't block over it, I just think it would make the test a little friendlier to future maintainers.

**Comment by sstosh** [comment]
> I don't think these cases are equivalent. I think the reason you're seeing a test failure is because you have a firewall that blocks outgoing ICMP, which is only incidentally related to proxies. I believe there are environments that block ICMP but not HTTP, and vice-versa, so this PR is just an unreliable heuristic.

Thank you for your review.

I understand that this root problem is not proxy but firewall.
I verified that ping default gateway is successful in my environment.

Therefore, I choose the method of ping default gateway.

**Comment by sstosh** [comment]
> Therefore, I choose the method of ping default gateway.

CI tests are failed...
I choose curl again.

**Comment by edsantiago** [comment]
>CI tests are failed...
>I choose curl again.

Thank you for trying. Is there any chance you still have a window open showing the failure? Or at least remember the gist of it? I won't block, I'm just really curious.

/approve

@containers/buildah-maintainers PTAL

**Comment by sstosh** [comment]
> Is there any chance you still have a window open showing the failure? Or at least remember the gist of it?

`ping -c 1 $gw (10.128.0.1)` is failed in Cirrus environment.
https://cirrus-ci.com/task/4979492540645376?logs=integration_test#L1120-L1145

If we fix this issue, I think that we need to change the firewall rule about $gw (10.128.0.1) in Cirrus.
However, I don't know what the network configuration of Cirrus are.

<details>
<summary>Test log in Cirrus CI</summary>

```
[+1825s] not ok 393 build-with-network-test
[+1825s] # (from function `die' in file ./helpers.bash, line 332,
[+1825s] #  from function `run_buildah' in file ./helpers.bash, line 319,
[+1825s] #  in test file ./bud.bats, line 5870)
[+1825s] #   `run_buildah build ${WITH_POLICY_JSON} ${TEST_SCRATCH_DIR}' failed
[+1825s] # /var/tmp/go/src/github.com/containers/buildah/tests /var/tmp/go/src/github.com/containers/buildah/tests
[+1825s] # # [checking for: docker.io/library/alpine]
[+1825s] # # [restoring from cache: /var/tmp/buildah-image-cache.9161 / docker.io/library/alpine]
[+1825s] # Getting image source signatures
[+1825s] # Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
[+1825s] # Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
[+1825s] # Writing manifest to image destination
[+1825s] # Storing signatures
[+1825s] # # /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah build --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json /var/tmp/buildah_tests.dwcc3q
[+1825s] # STEP 1/2: FROM alpine
[+1825s] # STEP 2/2: RUN ping -c 1 10.128.0.1
[+1825s] # PING 10.128.0.1 (10.128.0.1): 56 data bytes
[+1825s] #
[+1825s] # --- 10.128.0.1 ping statistics ---
[+1825s] # 1 packets transmitted, 0 packets received, 100% packet loss
[+1825s] # Error: building at STEP "RUN ping -c 1 10.128.0.1": while running runtime: exit status 1
[+1825s] # [ rc=1 (** EXPECTED 0 **) ]
[+1825s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+1825s] # #| FAIL: exit code is 1; expected 0
[+1825s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+1825s] # /var/tmp/go/src/github.com/containers/buildah/tests
```
</details>

**Comment by edsantiago** [comment]
Interesting! Very odd. Thank you for providing this info, I've saved it because I think it will help us in the future. And thank you again for all your contributions.

**Pull request merged**
