### PR TITLE
Bump to 1.8.3 second attempt.

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Add in a couple new commits to 1.8.3.  Also allows for 32 bit builds.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
FYI @baude @saschagrunert

**Comment by nalind** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
All green test buttons, @nalind can you tell the bot to merge it please?

**Comment by nalind** [comment]
@rh-atomic-bot +r

**Comment by nalind** [comment]
Aargh.
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
Thanks @nalind!

**Pull request closed without merging**
