### PR TITLE
Update to github.com/vbauerster/mpb v7.1.5

### PR DESCRIPTION
**Pull request by mtrmac**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Update to github.com/vbauerster/mpb v7.1.5 to fix https://github.com/vbauerster/mpb/issues/100 .

```
go get github.com/vbauerster/mpb/v7@latest
make vendor
```

#### How to verify it

? Hope that occasional CI hangs go away. Rely on Podman reliably reproducing the hang with MPB 7.1.3, and it being fixed in this version.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM
@rhatdan @nalind PTAL

**Comment by nalind** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
