### PR TITLE
Update gitignore to exclude test Dockerfiles

### PR DESCRIPTION
**Pull request by lumjjb**
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Test Dockerfiles are not currently being tracked as part of the git repository. 

#### How to verify it

1. Modify test Dockerfile in `tests/bud/*` 
2. Run `git status` and verify that the change is tracked.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
and forgot most importantly, thanks @lumjjb !

**Pull request merged**
