### PR TITLE
overlay.MountReadOnly: support RO overlay mounts

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
Although tests are not happy.

@giuseppe @nalind @TomSweeneyRedHat @ashley-cui PTAL

**Comment by vrothberg** [comment]
/hold

Currently having some root issues.

**Comment by vrothberg** [comment]
@giuseppe @nalind PTAL

**Comment by vrothberg** [comment]
@rhatdan I wonder if we could move this package over to c/common as Buildah and Podman are using it.

**Comment by TomSweeneyRedHat** [comment]
LGTM but want a lgtm from @giuseppe or @nalind 
@vrothberg feels like a common package to me too, but would like to hear from others too.

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
I am fine with moving this over to containers/common,  I would guess there is a possibility of CRI-O using it also.

**Pull request merged**
