### PR TITLE
Fix ident for dependabot gha block

### PR DESCRIPTION
**Pull request by jlosito**
#### What type of PR is this?

This fixes a small indentation error on the dependabot config.

> /kind api-change

/kind bug

> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:

I don't believe dependabot is sending pull requests for actions because there are a couple that this project uses which are not up-to-date.

#### How to verify it

The version of the checkout action which this project currently uses is out-of-date. This project is currently using v2, but v3 is the latest. A pull request should come in from dependabot bumping the checkout action to version 3. 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
Although we are looking to switch to renovate?

**Comment by cevich** [comment]
> Although we are looking to switch to renovate?

Yes, but it needs more tire-kicking time before I want to bring it out to lots of repos.  This change is fine/low-risk.

**Pull request merged**
