### PR TITLE
Include the FROM directive in Docker history Closes #2391

### LINKED ISSUE #2391: Include the FROM directive in Docker history
Pulling this from https://bugzilla.redhat.com/show_bug.cgi?id=1649044 and @control-d

```
In the customer's own words:

---
"Please include the FROM directive in docker image information.  Nice to know what base image was used.  Docker history often lists <missing> on base image layers when pushed/pulled from a repository."
---



Just based on this I think what they would like to see, at a minimum, is:


# cat Dockerfile 
FROM fedora:latest
MAINTAINER http://fedoraproject.org/wiki/Cloud

RUN dnf -y update && dnf clean all
RUN dnf -y install nginx && dnf clean all
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN echo "nginx on Fedora" > /usr/share/nginx/html/index.html


# podman build -t test:bz1649044 .
STEP 1: FROM fedora:latest
Getting image source signatures
Skipping blob 01eb078129a0 (already present): 85.81 MiB / 85.81 MiB [=======] 0s
Copying config d09302f77cfc: 1.97 KiB / 1.97 KiB [==========================] 0s
Writing manifest to image destination
Storing signatures
STEP 2: MAINTAINER http://fedoraproject.org/wiki/Cloud
--> ff18bdd9b520b02fb3fc2ad26eb6ddc8e802b8496421902ea629801041aa8cb4
STEP 3: FROM ff18bdd9b520b02fb3fc2ad26eb6ddc8e802b8496421902ea629801041aa8cb4
STEP 4: RUN dnf -y update && dnf clean all
Fedora Modular 29 - x86_64                      388 kB/s | 1.5 MB     00:03    
{...]
--> e9fd39dc40f530626de0139e941faa5a7169f1722ac51dd135f5d6d6dcd50fe9
STEP 5: FROM e9fd39dc40f530626de0139e941faa5a7169f1722ac51dd135f5d6d6dcd50fe9
STEP 6: RUN dnf -y install nginx && dnf clean all
Fedora Modular 29 - x86_64                      2.4 MB/s | 1.5 MB     00:00    
[...]
--> b58279a3e1239bdfc870cf75cd3c4346346e40f84a999c7093b2fe948e2fdcd9
STEP 7: FROM b58279a3e1239bdfc870cf75cd3c4346346e40f84a999c7093b2fe948e2fdcd9
STEP 8: RUN echo "daemon off;" >> /etc/nginx/nginx.conf
--> 6823c19ecc131820aa2e6cbd43025b2038ac1c8f0fdef158481f3138e8816456
STEP 9: FROM 6823c19ecc131820aa2e6cbd43025b2038ac1c8f0fdef158481f3138e8816456
STEP 10: RUN echo "nginx on Fedora" > /usr/share/nginx/html/index.html
--> a75cd222709a12ba0e42d56f37988a3663c65c612a0d04e9f6ea8afdbd7f0327
STEP 11: COMMIT test:bz1649044


<start of hypothetical output>

# podman history test:bz1649044
ID             CREATED         CREATED BY                                      SIZE      COMMENT
a75cd222709a   3 minutes ago   /bin/sh -c echo "nginx on Fedora" > /usr/s...   252B      
6823c19ecc13   3 minutes ago   /bin/sh -c echo "daemon off;" >> /etc/ngin...   5.12kB    
b58279a3e123   3 minutes ago   /bin/sh -c dnf -y install nginx && dnf cle...   19.91MB   
e9fd39dc40f5   4 minutes ago   /bin/sh -c dnf -y update && dnf clean all       117MB     
ff18bdd9b520   8 minutes ago   /bin/sh -c #(nop) FROM fedora:latest            1.024kB   
d09302f77cfc   2 months ago    /bin/sh -c #(nop) CMD ["/bin/bash"]             1.024kB   
<missing>      2 months ago    /bin/sh -c #(nop) ADD file:508fcc9342ae817...   283MB     
<missing>      2 months ago    /bin/sh -c #(nop) ENV DISTTAG=fcontainer F...   283MB     
<missing>      4 months ago    /bin/sh -c #(nop) LABEL maintainer=Clement...   283MB     


OR

# podman history test:bz1649044
ID             CREATED          CREATED BY                                      SIZE      COMMENT
a75cd222709a   4 minutes ago    /bin/sh -c echo "nginx on Fedora" > /usr/s...   252B      
6823c19ecc13   4 minutes ago    /bin/sh -c echo "daemon off;" >> /etc/ngin...   5.12kB    
b58279a3e123   4 minutes ago    /bin/sh -c dnf -y install nginx && dnf cle...   19.91MB   
e9fd39dc40f5   6 minutes ago    /bin/sh -c dnf -y update && dnf clean all       117MB     
ff18bdd9b520   10 minutes ago   /bin/sh -c #(nop) MAINTAINER http://fedora...   1.024kB   FROM fedora:latest
d09302f77cfc   2 months ago     /bin/sh -c #(nop) CMD ["/bin/bash"]             1.024kB   
<missing>      2 months ago     /bin/sh -c #(nop) ADD file:508fcc9342ae817...   283MB     
<missing>      2 months ago     /bin/sh -c #(nop) ENV DISTTAG=fcontainer F...   283MB     
<missing>      4 months ago     /bin/sh -c #(nop) LABEL maintainer=Clement...   283MB     


It might even be better to record:

  FROM docker.io/library/fedora@sha256:787bce7f4d2dafd8c4923dd5c43fb2e4b8473b57ea52f6d12be9bb27bc8f1a85


As is, I don't think this fulfills the customer's request.  I apologize if the initial request was not clear enough.
```

### PR DESCRIPTION
**Pull request by ironknight78**
#### What type of PR is this?

> /kind bug

#### What this PR does / why we need it:

As requested by @TomSweeneyRedHat  on https://github.com/containers/buildah/issues/2391, taken from:
 https://bugzilla.redhat.com/show_bug.cgi?id=1649044 

#### Which issue(s) this PR fixes:

#2391

#### Special notes for your reviewer:

Please let me know if this fixes the issue, otherwise I'll continue to add better functionality. Thanks!! :) 

#### Does this PR introduce a user-facing change?

None

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @ironknight78 for the PR, Can you squash and sign your commits.  
Could you also add a test for this.

**Comment by ironknight78** [comment]
Of course. Where should I add the tests @rhatdan ?? 😁

**Comment by rhatdan** [comment]
You can add tests in tests/*bats.

tests/history.bats would probably be best place.

**Comment by TomSweeneyRedHat** [comment]
@ironknight78 Thanks for the PR!
You'll need to sign your PR, otherwise the gating test will continue to fail.
`git commit --amend -s`, then rebase and repush.

**Comment by ironknight78** [comment]
@TomSweeneyRedHat @rhatdan Of course! I'm very happy to have found the file!!
I'm note sure I'm doing the PR correctly, though, now it seems that there are a bunch of other PRs over here. I'm very sorry if this causes confusion, I'm new to using Github.

**Comment by rhatdan** [comment]
@ironknight78 You need to do the following in your git repo

git rebase -i origin

Now you should be placed in an editor.
In each of your 10 PR lines after the first,  you will swap out the first few characters with a "s"
Save your edit.

This should put you in a second edit where you can fixup the commit message.

**Comment by TomSweeneyRedHat** [comment]
@ironknight78 thanks for your work and hope you get through the git maze!

**Comment by ironknight78** [comment]
@TomSweeneyRedHat haha it's getting tricky!!! I'll fix it. 😁

**Pull request closed without merging**
