### PR TITLE
refine dangling filter

### PR DESCRIPTION
**Pull request by vrothberg**
By proxy by vendoring containers/common.  Previously, a "dangling" image
was an untagged image; just a described in the Docker docs.  The
definition of dangling has now been refined to an untagged image without
children to be compatible with Docker.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

WIP since I am currently vendoring in my fork of c/common for testing purposes.

### CODE REVIEW

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by umohnani8** [comment]
LGTM 
@rhatdan @nalind PTAL

**Review by TomSweeneyRedHat — COMMENTED** [review]
same comment here as in podman.  If you have not already, can you verify/touch up the man pages for rmi and images, please?

**Comment by TomSweeneyRedHat** [comment]
@vrothberg ^^

**Pull request merged**
