### PR TITLE
[WIP] default to zstd:chunked

### PR DESCRIPTION
**Pull request by rhatdan**
[NO NEW TESTS NEEDED]

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe Is the failure here the one you have been working with @mtrmac on?

Looks like buildah is pulling an image when it has it in cache?

**Comment by giuseppe** [comment]
yes that is one of the issues that containers/image#1980 is addressing

**Comment by rhatdan** [comment]
Should we move to tests everything with zstd:chunked at this point?  I think it is time to turn this on in testing to make sure everything works going forward.

**Comment by mtrmac** [comment]
Repeated zstd:chunked pushes are still known to be inefficient. I don’t think that’s exactly a _blocker_ to switching tests to zstd:chunked, but unless we are going to institute some kind of matrix where various option values are tested simultaneously, I think testing the most production-relevant values is more valuable.

**Comment by rhatdan** [comment]
Except the goal is to change the default in Fedora 41 to zstd:chunked.  I have already changed the default in Rawhide, to move this forward.  If we continue to default to gzip, we will never get to zstd:chunked.

**Pull request closed without merging**
