### PR TITLE
Vendor in opencontainers/selinux v1.10.1

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but we're having no luck at all vendoring today....  Tests are all unhappy.

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM. @rhatdan But wouldn't it cause issue if it points to another similar symlink however not sure if that is possible in case of `/proc/self/fd/%d`

**Comment by rhatdan** [comment]
@flouthoc perhaps, but this duplicates what would have happened before the fix in opencontainers/selinux.

**Review by flouthoc — APPROVED** [review]
LGTM, restarted flakes @nalind PTAL

**Comment by flouthoc** [comment]
@rhatdan Test `bud stdio is usable pipes` which exercises this part of code is failing. Could you PTAL.
Test was added here: https://github.com/containers/buildah/pull/3630

/hold till relevent test passes

**Pull request merged**
