### PR TITLE
StageExecutor.intermediateImageExists: recognize cached images based on scratch

### LINKED ISSUE #2403: cache bypassed when COPY'ing into empty image, such as "scratch"
**Description**
Currently, when doing a multi-stage bulid and using `FROM scratch` in a later stage, buildah creates a different `scratch` image every time and therefore gets zero caching, causing much slowed builds an greatly increased disk usage.  I've been able to workaround it by `c=$(buildah from scratch) ; buildah commit $c myscratch` then using `FROM myscratch` instead of `FROM scratch`.

**Steps to reproduce the issue:**
1. `podman build -f Dockerfile`
2. do it again
3. observe multiple images even though no changes to the `Dockerfile`
```
FROM fedora as build

FROM scratch
COPY --from=build / /
```

**Describe the results you received:**
Every run creates the image again with a different hash, and there is no caching.

**Describe the results you expected:**
Cache used for `scratch` images.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
podman-1.9.3-1.fc32.x86_64
buildah-1.14.9-1.fc32.x86_64

```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**
completely stock
```
(paste your output here)
```

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Update `imagebuildah.StageExecutor.intermediateImageExists()` to recognize images based on "scratch" as viable candidates for cache images when we ourselves are based on "scratch".

#### How to verify it

We add a couple of integration tests.  Tests which were there before should continue to pass.

#### Which issue(s) this PR fixes:

Fixes #2403.

#### Does this PR introduce a user-facing change?

```
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @vrothberg @giuseppe PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
will cut v1.16.0 once bors does its thing with this pr

**Comment by nalind** [comment]
bors retry

**Comment by TomSweeneyRedHat** [comment]
bors retry

**Comment by TomSweeneyRedHat** [comment]
c'mon bors, this was supposed to be quick and easy.

**Pull request merged**
