### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rhatdan**
Patch originally proposed by @adlermedrado but never signed.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces https://github.com/containers/buildah/pull/1658

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @ashley-cui @QiWang19 @vrothberg PTAL

**Comment by ashley-cui** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=ashley-cui

**Pull request closed without merging**
