### PR TITLE
secret: accept `required` flag without value

### PR DESCRIPTION
**Pull request by flouthoc**
`Buildkit` and `docker` accepts `required` flag as `true` when provided without any value in `--mount=type=secret` so lets do same for buildah.

Example usage

```Dockerfile
FROM docker.io/nginx:1.23.3

RUN --mount=type=secret,id=nginx-crt,dst=/nginx-repo.crt,required \
    --mount=type=secret,id=nginx-key,dst=/nginx-repo.key,required \
    set -x \
    && . /etc/os-release \
    && stat /nginx-repo.crt \
    && stat /nginx-repo.key
```

Closes: https://github.com/containers/podman/issues/18438

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
secret: accept `required` flag without value
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
Do we need a test with required=false?

**Comment by TomSweeneyRedHat** [comment]
I don't think we do, and it would be a good addition.
Otherwise, LGTM

**Comment by flouthoc** [comment]
Okay added a case for missing `required=false` in a new commit.

**Pull request merged**
