### PR TITLE
[WIP] Testing vendor fix for containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
Now we are seeing:
```
[+0332s]         	Error:      	Filesystem contents differ
[+0332s]         	Test:       	TestConformance/copy_file_to_deeper_directory_without_explicit_slash
[+0332s]         	Messages:   	Content which only exists in buildah version: /etc/hostname
[+0332s]         	            	File attributes in both versions have different values:
[+0332s]         	            	File:attr        Docker        buildah
[+0332s]         	            	/etc:mode        040755        0755
```

**Comment by rhatdan** [comment]
Where the other tests were failing with
```
[+0335s]         	Error Trace:	/var/tmp/go/src/github.com/containers/buildah/tests/conformance/conformance_test.go:482
[+0335s]         	            				/var/tmp/go/src/github.com/containers/buildah/tests/conformance/conformance_test.go:333
[+0335s]         	            				/var/tmp/go/src/github.com/containers/buildah/tests/conformance/conformance_test.go:151
[+0335s]         	Error:      	Filesystem contents differ
[+0335s]         	Test:       	TestConformance/copy_file_to_root
[+0335s]         	Messages:   	Content which only exists in buildah version: /etc/hostname
[+0335s]         	            	File attributes in both versions have different values:
[+0335s]         	            	File:attr        Docker        buildah
[+0335s]         	            	/a:mode          0644          0100644
```

**Comment by rhatdan** [comment]
@cevich which version of Docker is installed in these images?  When I test locally on F38 with  

$ docker -v
Docker version 24.0.2, build cb74dfc

Removing the fillGo18FileTypeBits causes the tests to blow up, which we are seeing here.  But in the tests without the removal we are seeing the opposite?

**Comment by cevich** [comment]
> which version of Docker is installed in these images

I actually have a way to check that...

**Comment by cevich** [comment]
...Ref: https://github.com/containers/automation_images/pull/282#issuecomment-1591402202

Looks like:

* In F37/38 we install a bunch related packages: podman-docker, python3-docker, docker-compose but no actual (official) docker package.
* In Debian (for the conformance tests) we cache packages for:

  ```
  debian: Get:2 https://download.docker.com/linux/debian bookworm/stable amd64 containerd.io amd64 1.6.21-1 [28.3 MB]
  debian: Get:3 https://download.docker.com/linux/debian bookworm/stable amd64 docker-buildx-plugin amd64 0.10.5-1~debian.12~bookworm [26.1 MB]
  debian: Get:4 https://download.docker.com/linux/debian bookworm/stable amd64 docker-ce-cli amd64 5:24.0.2-1~debian.12~bookworm [13.3 MB]
  debian: Get:5 https://download.docker.com/linux/debian bookworm/stable amd64 docker-ce amd64 5:24.0.2-1~debian.12~bookworm [22.9 MB]
  debian: Get:6 https://download.docker.com/linux/debian bookworm/stable amd64 docker-ce-rootless-extras amd64 5:24.0.2-1~debian.12~bookworm [9006 kB]
  debian: Get:7 https://download.docker.com/linux/debian bookworm/stable amd64 docker-compose-plugin amd64 2.18.1-1~debian.12~bookworm [10.9 MB]
   ```
* The cached Debian packages are [installed at runtime](https://github.com/containers/buildah/blob/main/contrib/cirrus/setup.sh#L50-L57).

Note: The Debian SID "Trixie" (13) images are actually installing docker for "Bookworm" (12) because at the time there was no docker repo. for Debian 13.  I just checked, there are still no docker packages for "Trixie" :confused:

**Comment by rhatdan** [comment]
Well it seems we have two different versions of Docker installed or something fishy is going on.  If I add my PR to remove the permission changes the comparison blows up, but if I don't add it, it blows up.
Docker version seems to change depending on the version I install

**Comment by rhatdan** [comment]
Do we have moby-engine installed?

**Comment by cevich** [comment]
> Well it seems we have two different versions of Docker installed or something fishy is going on. If I add my PR to remove the permission changes the comparison blows up, but if I don't add it, it blows up. Docker version seems to change depending on the version I install

Oof, yeah that's certainly odd.  Our CI setup is engineered specifically to NOT change versions of important things ***unless*** it's a different CI VM image :thinking: 

> Do we have moby-engine installed?

A long time ago with the Ubuntu VMs we use to.  I just searched through the image-build scripts and don't see "moby" anywhere.  Using `hack/get_ci_vm.sh Build Conformance w/ vfs`, I get:

```
# docker version
bash: docker: command not found
# dpkg -L docker-ce
dpkg-query: package 'docker-ce' is not installed
# ls -1 /var/cache/download
containerd.io_1.6.21-1_amd64.deb
docker-buildx-plugin_0.10.5-1~debian.12~bookworm_amd64.deb
docker-ce-cli_5%3a24.0.2-1~debian.12~bookworm_amd64.deb
docker-ce-rootless-extras_5%3a24.0.2-1~debian.12~bookworm_amd64.deb
docker-ce_5%3a24.0.2-1~debian.12~bookworm_amd64.deb
docker-compose-plugin_2.18.1-1~debian.12~bookworm_amd64.deb
```

That's expected, since `setup.sh` hasn't run (to install them).  The cached packages match what's in the VM image-build script.  Hmm, maybe a 're-run in terminal' would provide some more clues?

**Pull request closed without merging**
