### PR TITLE
stage_executor,heredoc: honor interpreter in heredoc

### PR DESCRIPTION
**Pull request by flouthoc**
If there are any shebang in heredoc file then buildah must honor that. Consider a case of

```Dockerfile
FROM python:3.11-slim-bullseye
RUN <<EOF
#!/usr/bin/env python
print('hello world')
EOF
```

Closes: https://github.com/containers/buildah/issues/5251

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### How to verify it
New Integration test

#### Does this PR introduce a user-facing change?

```release-note
stage_executor,heredoc: honor interpreter/shebang in heredoc
```

### CODE REVIEW

**Comment by flouthoc** [comment]
@nalind @rhatdan @containers/buildah-maintainers PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by flouthoc** [comment]
Rebased.

**Comment by flouthoc** [comment]
@nalind @containers/build-maintainers PTAL

**Comment by rhatdan** [comment]
@umohnani8 @TomSweeneyRedHat @giuseppe PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
the branch needs to be udated and I've just kicked that off.

**Comment by flouthoc** [comment]
@TomSweeneyRedHat I think rebased worked but it added additional commit, you can remove it with button (squash and merge)

**Pull request merged**
