### PR TITLE
Fix stutters

### PR DESCRIPTION
**Pull request by rhatdan**
Podman adds an Error: to every error message. So starting an error
message with "error" ends up being reported to the user as

Error: error ...

This patch removes the stutter.

Also ioutil.ReadFile errors report the Path, so wrapping the err message
with the path causes a stutter.

Signed-off-by: Daniel J Walsh dwalsh@redhat.com

[NO NEW TESTS NEEDED]

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by flouthoc — COMMENTED** [review]
It looks likes some tests needs to retrofit as per the new error messages.

**Comment by nalind** [comment]
Does this mean we stop mentioning that errors are errors when people run the `buildah` command?

**Comment by rhatdan** [comment]
@nalind I think most errors are clearly errors when they happen, but we can do the same as Podman and prepend Errors: if you think we should.

@flouthoc @TomSweeneyRedHat @nalind @vrothberg @giuseppe PTAL

**Review by flouthoc — APPROVED** [review]
Changes LGTM waiting for @nalind to confirm on his concern.

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by nalind** [comment]
> @nalind I think most errors are clearly errors when they happen, but we can do the same as Podman and prepend Errors: if you think we should.

The stutter you're trying to fix here only exists because podman does that, so yeah, I'd say we should.  To put a fine point on it, if fixing podman's stutter means making buildah's error messages less clear, I'm going to nack.

**Pull request merged**
