### PR TITLE
snap

### PR DESCRIPTION
**Pull request by mikeroyal**
Added snapcraft.yaml to build a [snap](https://snapcraft.io/) package for buildah. This Snap for buildah makes the installation and setup of buildah easier for the user by auto-updating to the latest version of buildah and can also rollback to the previous version if something breaks.

Signed-off-by: Michael Royal <mikerr90@outlook.com>
# Prep
sudo snap install snapcraft --classic
sudo snap install multipass --beta --classic

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mikeroyal The CI thinks you didn't sign the PR.  Can you `git commit --amend -s` and the repush please?

**Comment by TomSweeneyRedHat** [comment]
I'm not snap literate, but the changes LGTM.  Is there anything that should/could be added to the install.md  page regarding snap usage, especially for the folks new to snap?

**Comment by rhatdan** [comment]
@mikeroyal Still have the first PR without a signing.

You can do a 

git rebase -i origin 

And then modify the first commit.
Finally do a git push --force

**Comment by mikeroyal** [comment]
Hi @TomSweeneyRedHat, Here is install and setup info for snap usage.

# Install Snapd:

 $ sudo apt install snapd        # Ubuntu/Debian
 $ sudo dnf install snapd       # Fedora

To enable classic snap support for Fedora, enter the following to create a 
symbolic link between /var/lib/snapd/snap and /snap: 

 $ sudo ln -s /var/lib/snapd/snap /snap

# Install snap:

 $ sudo snap install buildah --edge --classic   # Ubuntu/Debian
 $ sudo snap install buildah --classic             # Fedora

**Comment by mikeroyal** [comment]
Hi @rhatdan, 
Sorry about the delayed response the last few weeks at my job have been busy for me. So I've been thinking it might easier for you and others if the snap was in a separate repo for testing. So I created a separate repo that's all setup with a readme that you can clone here. https://github.com/mikeroyal/buildah-snap

**Comment by rhatdan** [comment]
@lsm5 WDYT?

**Comment by lsm5** [comment]
> $ sudo snap install buildah --edge --classic # Ubuntu/Debian
> $ sudo snap install buildah --classic # Fedora

@mikeroyal do these steps work already? If yes, then LGTM for merge.

**Comment by rhatdan** [comment]
This is an old PR that never got merged.  If people are still interested then ask me to reopen. Closing.

**Pull request closed without merging**
