### PR TITLE
sign test: fix gpg failure on Rawhide

### PR DESCRIPTION
**Pull request by edsantiago**
Rawhide gating tests are failing with:

    gpg: keysize invalid; using 2048 bits
    gpg: agent_genkey failed: Inappropriate ioctl for device
    gpg: key generation failed: Inappropriate ioctl for device

The first is just a warning; easily fixed by s/512/2048/

The next two are actual errors caused by gpg trying to read
a passphrase using pinentry. Solution found here:

   https://d.sb/2016/11/gpg-inappropriate-ioctl-for-device-errors

I have no idea how this ever passed CI.

Also: refactored duplicate code.

Signed-off-by: Ed Santiago <santiago@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by edsantiago** [comment]
Tests green. @nalind @cevich PTAL

**Comment by cevich** [comment]
> I have no idea how this ever passed CI

It's not tested properly :D  We need the fix in this PR so enabling proper VM-based testing can happen: https://github.com/containers/buildah/pull/2115

**Comment by cevich** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
