### PR TITLE
Allow dst and destination for target in secret mounts

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/buildah/issues/3396

Patch from @mixedCase

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@mixedCase PTAL

**Comment by rhatdan** [comment]
@nalind @ashley-cui @umohnani8 @TomSweeneyRedHat PTAL

**Comment by ashley-cui** [comment]
LGTM, thanks @mixedCase!

**Review by TomSweeneyRedHat — COMMENTED** [review]
@ashley-cui @rhatdan do we need to tweak a man page anywhere for this?

**Comment by rhatdan** [comment]
It is talked about in the buildah-run man page.  But not the buildah bud man page.

**Comment by rhatdan** [comment]
It maybe should be documented in the non-existent Containerfile man page.  There is a Dockerfile man page, but we don't ship it, it comes from Docker.

**Comment by ashley-cui** [comment]
Docker's documentation seems pretty inconsistent, `dst` is documented only [here](https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information), `target` is documented only [here](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypesecret) and `destination` isn't documented at all.

**Pull request merged**
