### PR TITLE
Add buildah.io to README.md and doc fixes

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Adds a link to the buildah.io website from the Developers Information.  Also touches up some rm/rmi man pages per #1038

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
CI loves me, two line change to the README.md and it still fails.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by boaz1337** [comment]
LGTM

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
LGTM

**Comment by rhatdan** [comment]
Done fighting with the CI/CD system, Merging manually.

**Pull request merged**
