### PR TITLE
Add support for image_parallel_copies in containers.conf

### PR DESCRIPTION
**Pull request by rhatdan**
Adding this feature to allow people with little band with to adjust the
ammount of threads pulling an image.

I don't have an easy way to test this other then manually.

[NO TESTS NEEDED]

Helps Fix: https://github.com/containers/buildah/issues/2224

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg this might interfere with your big PR, so might have to wait.

**Comment by nalind** [comment]
LGTM.  Have you been able to confirm this manually, at least, with images like `registry.fedoraproject.org/f29/httpd` or `docker.io/library/swift`, which have multiple layers?

**Comment by vrothberg** [comment]
> @vrothberg this might interfere with your big PR, so might have to wait.

Yes, please don't merge. We can handle all of that transparently in `libimage`, so I don't think we actually need a Buildah PR for it.

**Comment by rhatdan** [comment]
@nalind Yes I verified this works.  @vrothberg ALready opened a PR and got it merged in containers/common.

**Pull request closed without merging**
