### PR TITLE
Never omit layers for emptyLayer instructions when squashing/cwing

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Ignore whether or not the final build instruction should produce a layer if we're squashing or producing a confidential workload, when we'd still have to produce a layer containing the contents of the base image.

#### How to verify it

Extended an integration test!

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
`buildah build` will no longer produce an empty image when the `--cw` flag is used along with the `--layers` flag and the final instruction in the Dockerfile is not one of ADD, COPY, or RUN.
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
Although I want @flouthoc to approve, since this looks familiar to me as potentially something that fixed a different bug.

**Review by flouthoc — APPROVED** [review]
LGTM since this only affects `cw` images , afaik `buildah` allows producing empty layer images.

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
