### PR TITLE
fix: `rmi --prune` when parent image is in store.

### LINKED ISSUE #2878: Image pruning fails if image store contains parent image
**Description**
When the image store contains a parent image pruning fails - even if the parent image is deleted successfully during the prune operation.

I wouldn't expect the code [here](https://github.com/containers/buildah/blob/00b8e9fdf2aa192d5f1a50e96e21e4992de33dd6/cmd/buildah/rmi.go#L206) to terminate with an error but to log a debug message or nothing at all.

**Steps to reproduce the issue:**
Create 1st image:
```
$ buildah from --name container1 scratch
container1
$ buildah commit container1
c530efe3ad369aeca61b73706670aab5e34101cecf99e71931894023d8cc8538
```
Create the 2nd image based on the 1st (and delete the containers):
```sh
$ buildah from --name container2 c530efe3ad369aeca61b73706670aab5e34101cecf99e71931894023d8cc8538
container2
$ buildah commit container2
f8d3ab231fa14c3ee03c2206edcea6bbe00124c832be73c759e55798378535a8
$ buildah delete container1 container2
180a0212f627513ac0c4072e127ae634b7dff986651d44577b22d643a77a6cf1
7a601ec14a9b420ebf2dc2f2be6727d20dad3b92b9ec485ec37ccce53c4635a7
```
Pruning the images now fails:
```sh
$ buildah rmi --prune --force
c530efe3ad369aeca61b73706670aab5e34101cecf99e71931894023d8cc8538
f8d3ab231fa14c3ee03c2206edcea6bbe00124c832be73c759e55798378535a8
unable to delete "c530efe3ad369aeca61b73706670aab5e34101cecf99e71931894023d8cc8538" (cannot be forced) - image has dependent child images
$ echo $?
125
```
However pruning a 2nd time succeeds since the image `c530...` apparently has been removed properly with the previous prune operation when deleting the child image `f8d3...`:
```sh
$ buildah rmi --prune --force
```

**Describe the results you received:**
`buildah rmi --prune --force` exits with an error code although it has pruned all images successfully.

**Describe the results you expected:**
`buildah rmi --prune --force` should exit with code 0 after it has deleted all images successfully. It may log a debug message in case a parent image could not be deleted initially.

**Output of `rpm -q buildah` or `apt list buildah`:**
local buildah 1.18.0 [build](https://github.com/mgoltzsche/cache-provisioner/blob/968403cce085fa529f1f6ce6c2da23654124ef4d/helper/Dockerfile)

**Output of `buildah version`:**

```
Version:         1.18.0
Go Version:      go1.14.13
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.8.0
Git Commit:      d3a01d00
Built:           Tue Dec 29 03:08:14 2020
OS/Arch:         linux/amd64
```

### PR DESCRIPTION
**Pull request by mgoltzsche**
When the `--prune` option is provided to the `rmi` command the existance of parent images within the store does not make the command fail (nor log anything).

Fixes #2878

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Don't log and exit with an error when `buildah rmi --prune -f` is run and the image store contains a (dangling) parent image.

#### How to verify it

Run `cd test && ./test_runner.sh rmi.bats` (contains additional test now).

#### Which issue(s) this PR fixes:

Fixes #2878

#### Does this PR introduce a user-facing change?

```release-note
fixes a bug where the rmi --prune command failed when the image store contains a (dangling) parent image.
```

### CODE REVIEW

**Comment by rhatdan** [comment]
/ok-to-test
Thanks @mgoltzsche 
Could you add a test just like you documented in the issue
LGTM

**Comment by mgoltzsche** [comment]
I've added a test to `rmi.bats`.

**Comment by TomSweeneyRedHat** [comment]
LGTM
Thanks @mgoltzsche !

**Pull request merged**
