### PR TITLE
[skip-ci] GHA: Reuse both cirrus rerun and check workflows

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

More features, less to maintain.  Everybody wins.

Depends on https://github.com/containers/podman/pull/16503

#### How to verify it

Difficult to do.  Would need to setup another repo with all the necessary secrets and push these changes to it's `main`.  Basically a PITA.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
Not sure there's much that can be "reviewed" here.  It's kind of just "merge and pray" when it comes to Github Actions.  Though after merge, I can trigger a manual run to confirm it's working.

**Comment by cevich** [comment]
Force-push: Oh woops...small typo.  Okay, NOW it's ready :grin:

**Comment by cevich** [comment]
force-push: Once again for the second-time: fixed a typo :blush:

**Review by lsm5 — APPROVED** [review]
/lgtm
/approve

**Comment by cevich** [comment]
First run of this was red, I did some magic and made it green: https://github.com/containers/buildah/actions/runs/3501120652

**Pull request merged**
