### PR TITLE
WIP: vendor c/image blob-info-caching 

### PR DESCRIPTION
**Pull request by mtrmac**
<s>By no means production ready at this point (writes data to the working directory!)</s>, primarily to trigger CI.

<s>NOTE: This, for now, includes https://github.com/containers/buildah/pull/1214 , which should probably be reviewed and merged separately.</s>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac Any progress on this?

**Comment by mtrmac** [comment]
With current master:
```console
$ skopeo copy --dest-tls-verify=false docker://wordpress docker://localhost:5000/wordpress
$ cat Dockerfile-test
FROM localhost:5000/wordpress:latest
COPY Dockerfile-test /root/Dockerfile-test
RUN echo Hello > /etc/motd
$ ./buildah --debug bud  --tls-verify=false -t result -f Dockerfile-test .
$ time sudo ./buildah --debug push --tls-verify=false result docker://localhost:5000/result1
real	0m53,046s
user	0m21,596s
sys	0m12,113s
```
With this branch, as of right now:
```console
$ ./buildah --debug bud  --tls-verify=false -t result -f Dockerfile-test .
$ time sudo ./buildah --debug push --tls-verify=false result docker://localhost:5000/result1
real	0m0,856s
user	0m0,080s
sys	0m0,101s
$ time sudo ./buildah --debug push --tls-verify=false result docker://localhost:5000/result4
real	0m0,703s
user	0m0,073s
sys	0m0,100s
```

Which is rather promising :)  I still need to
- Place the file into a reasonable location instead of `$(pwd)`
- Ensure that all the known slowness issues benefit (if they can)
- Add tests for corner cases
- Write documentation for the code

**Comment by rhatdan** [comment]
This looks very nice.  We need this ASAP.

**Comment by TomSweeneyRedHat** [comment]
Holy Toledo @mtrmac, that's some impressive initial speed ups.

**Comment by mtrmac** [comment]
NOTE: This, for now, includes https://github.com/containers/buildah/pull/1214 , which should probably be reviewed and merged separately.

**Comment by mtrmac** [comment]
Closing in favor of #1218.

**Pull request closed without merging**
