### PR TITLE
[release-1.22] Accept repositories on login/logout

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Cherry pick #3412 from @saschagrunert

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@saschagrunert PTAL
I created the release just before this finally merged in main.

**Comment by saschagrunert** [comment]
CI is not happy:
```
[+0072s] If your commit really, truly does not need tests, you can proceed
[+0072s] by adding '[NO NEW TESTS NEEDED]' to the body of your commit message.
```

**Review by saschagrunert — APPROVED** [review]

**Comment by TomSweeneyRedHat** [comment]
Thanks @saschagrunert, I've repushed with the tag.

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
