### PR TITLE
Allow processing of common options via FlagSet

### PR DESCRIPTION
**Pull request by abergmeier**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test

/kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:

Am using Buildah - but don't want to use Cobra.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@abergmeier thanks for the change, but our CI isn't thrilled with it...

```
[+0071s] # github.com/containers/buildah/pkg/parse
[+0071s] pkg/parse/parse.go:61:39: undefined: pflag
[+0071s] pkg/parse/parse.go:122:19: undefined: c
[+0071s] pkg/parse/parse.go:128:35: undefined: c
[+0071s] pkg/parse/parse.go:135:18: undefined: c
[+0071s] pkg/parse/parse.go:136:17: undefined: c
[+0071s] pkg/parse/parse.go:137:18: undefined: c
[+0071s] pkg/parse/parse.go:138:18: undefined: c
[+0071s] pkg/parse/parse.go:141:5: undefined: flag
[+0071s] pkg/parse/parse.go:152:17: undefined: c
[+0071s] pkg/parse/parse.go:153:17: undefined: c
[+0071s] pkg/parse/parse.go:153:17: too many errors
```

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @vrothberg @nalind @saschagrunert PTAL

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
