### PR TITLE
vendor logrus v1.4.2

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
vendor logrus v1.4.2

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by nalind** [comment]
LGTM.  We weren't using `logrus.IsTerminal()`, so its removal doesn't affect us.

**Comment by vrothberg** [comment]
@rh-atomic-bot r+

**Comment by vrothberg** [comment]
I missed the big WIP in the title. @TomSweeneyRedHat, is this ready to merge?

**Comment by TomSweeneyRedHat** [comment]
@vrothberg I just sat down to remove the WIP.  @jhonce had vendored 1.3 into Podman and I wanted to verify with him on that before removing the WIP.  We've both decided to go to 1.4.2, update incoming.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
