### PR TITLE
manifest: addCompression use default from containers.conf

### PR DESCRIPTION
**Pull request by rhatdan**
Replaces: https://github.com/containers/buildah/pull/5014

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by rhatdan** [comment]
@nalind @vrothberg @giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Pull request merged**
