### PR TITLE
Build static binary with `buildGoModule`

### PR DESCRIPTION
**Pull request by hswong3i**
#### What type of PR is this?

> /kind cleanup

#### What this PR does / why we need it:

[nix] Build Static Binary with `buildGoModule`

Switch from nix `channel:nixpkgs-unstable` to `channel:nixos-20.03` for better stability.

Also see:
- https://github.com/containers/crun/pull/428
- https://github.com/containers/conmon/pull/189
- https://github.com/containers/skopeo/pull/973
- https://github.com/containers/buildah/pull/2428
- https://github.com/containers/podman/pull/7076
- https://github.com/cri-o/cri-o/pull/4012

#### Does this PR introduce a user-facing change?

```release-note
Build static binary with `buildGoModule`
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@hswong3i please rebase to get #2427 which will fix the registry issue the test ran into.

**Comment by hswong3i** [comment]
@TomSweeneyRedHat rebase completed, also add test for static binary.

BTW, still WIP for improving the static binary test case. Will update again soon.

**Comment by hswong3i** [comment]
@rhatdan finally static build working, CI updated and working, also synchronize coding style between crun/conmon/skopeo/buildah/podman.

**Comment by hswong3i** [comment]
@TomSweeneyRedHat most required CI passed: https://github.com/containers/buildah/pull/2428/checks?check_run_id=852867059 ;-)

**Comment by hswong3i** [comment]
@TomSweeneyRedHat @saschagrunert as https://github.com/cirruslabs/cirrus-ci-docs/issues/681 get fixed now static binary build phase reduce from ~40mins to ~4mins (https://cirrus-ci.com/task/6631072614055936), by caching and reuse previous dependency build result ;-)

**Comment by rhatdan** [comment]
bors retry

**Pull request merged**
