### PR TITLE
Bump 1.31.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mheon @flouthoc PTAL  Bumping to get the test fix and a new BuildKit CVE fix.

**Comment by TomSweeneyRedHat** [comment]
And network hiccups.  Rerunning.

**Comment by mheon** [comment]
I don't think I can merge on this repo, but LGTM

**Comment by TomSweeneyRedHat** [comment]
Smashed it through.

**Pull request merged**
