### PR TITLE
buildah: use volatile containers

### PR DESCRIPTION
**Pull request by giuseppe**
overlay supports a new mount option "volatile" that reduces I/O by ignoring fsync and syncfs requests.

Enable it for Buildah containers as they are not supposed to survive a machine crash and they are thrown away if the build fails.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

enable "volatile" containers.  Builds are faster.

#### Does this PR introduce a user-facing change?

```release-note
On kernels where it is supported, enable the "volatile" mount option for overlay
```

### CODE REVIEW

**Comment by rhatdan** [comment]
Does storage do the right thing is "volatile" is not supported by the kernel?
LGTM

**Comment by giuseppe** [comment]
> Does storage do the right thing is "volatile" is not supported by the kernel?

if volatile is not supported by the kernel, then it is just ignored

**Review by TomSweeneyRedHat — COMMENTED** [review]
Think this will need a rebase to pick up the dockerignore reversion.  Also we need to document this somewhere.

**Comment by giuseppe** [comment]
rebased

**Comment by rhatdan** [comment]
This should NOT be back ported to the release.

@vrothberg @saschagrunert @nalind @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind @vrothberg @saschagrunert @umohnani8 @ashley-cui PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM, I like simple changes with huge impact :)

**Pull request merged**
