### PR TITLE
[CI:DOCS] Update install.md

### PR DESCRIPTION
**Pull request by necrose99**
app-containers/podman from app-emulation/

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@necrose99 thanks for the PR!  Our CI is unhappy as you did not sign you PR.  Could you please `git commit --amend -s`, then fetch, rebase, and push again please?

@lsm5 PTAL

**Comment by rhatdan** [comment]
You need to rebase, sign and push your commits.
$ git rebase -i origin
$ git push --force

**Comment by lsm5** [comment]
do we have a `[NO NEW TESTS NEEDED]` or `[CI: DOCS]` or something similar for buildah? The install.md change itself looks good. Need commits squashed and a signoff as @rhatdan mentioned.

**Review by flouthoc — APPROVED** [review]
LGTM just commit needs to be signed.

**Pull request closed without merging**
