### PR TITLE
install.md: update golang dependency

### PR DESCRIPTION
**Pull request by jingxiaolu**
After commit 92ce0bdf, golang dependency for compiling is 1.12 or higher.

Signed-off-by: Lu Jingxiao <lujingxiao@huawei.com>

### CODE REVIEW

**Comment by jingxiaolu** [comment]
golang >= 1.12 is required, otherwise we'll get error when `make`:
```bash
[root@HGH1000059941 buildah]# make
GO111MODULE=on go build -mod=vendor -ldflags '-X main.GitCommit=8fd3148 -X main.buildInfo=1575946937 -X main.cniVersion=v0.7.1'  -o buildah -tags "seccomp selinux    " ./cmd/buildah
go build github.com/containers/buildah/pkg/cgroups: module requires Go 1.12
```

Please help to check this PR, thanks~

**Comment by TomSweeneyRedHat** [comment]
Oh my, nice catch/fix.  Thanks @jingxiaolu !
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by jingxiaolu** [comment]
thank you all~

**Pull request closed without merging**
