### PR TITLE
Bump 1.7.2

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
First time trying to do the version bump with two commits in one PR.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rhatdan and @vrothberg PTAL
FYI @mheon

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
LGTM.
Thanks for the ping, @TomSweeneyRedHat. I let you merge :^)

**Comment by vrothberg** [comment]
I think we need to get https://github.com/containers/buildah/pull/1450 in prior to releasing a new version. Currently, rootless Buildah is broken which seems like a big blocker.

**Comment by vrothberg** [comment]
> LGTM.
> Thanks for the ping, @TomSweeneyRedHat. I let you merge :^)

**Comment by TomSweeneyRedHat** [comment]
I'm going to close this and do another PR so I can get #1450 included.

**Pull request closed without merging**
