### PR TITLE
[release-1.32] Recover release-branch CI

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Unfortunately maintenance CI was not enabled on this branch, resulting in the CI VM images being pruned and irrecoverably purged.  Restore CI by substituting similar images.  These images aren't a perfect match, but they are already marked for permanent retention.

#### How to verify it

PR-level CI will run and pass

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
@TomSweeneyRedHat I attempted to cherry-pick b2504c263684730552c56fff68b4b13f99078d0b to fix the conformance tests.  PLMK if you'd prefer I don't do that in this PR (or if I did it wrong).

**Comment by cevich** [comment]
Found a `c20231004t194547z-f39f38d13` which is only 2-months newer.  Maybe that could work (I'll give it a try after lunch).

**Comment by cevich** [comment]
Force-push: Removed new (broken here) blob cache system test.

**Comment by cevich** [comment]
@TomSweeneyRedHat this one is ready to go PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
@rhatdan or @nalind PTAL and merge if this LGTY

**Pull request merged**
