### PR TITLE
common: fix getFormat func

### PR DESCRIPTION
**Pull request by q384566678**
Modify the authentication method of format.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
@q384566678, thanks for the fix! Would you rephrase the commit message and describe that is fixing a bug. The commit title could be something like `common: getFormat: match entire string not only the prefix`. It's really helpful for packagers who are reading the changelog to know what has been changed.

**Comment by q384566678** [comment]
@vrothberg Done. Thanks for your suggestion.

**Comment by giuseppe** [comment]
thanks, LGTM

**Comment by vrothberg** [comment]
Once https://github.com/containers/buildah/pull/1090 is merged, you can rebase the PR and we can merge it.

**Comment by q384566678** [comment]
Rebased, PTAL.

**Comment by vrothberg** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by TomSweeneyRedHat** [comment]
@q384566678 can you try rebasing and repushing this one?

**Comment by TomSweeneyRedHat** [comment]
@q384566678 One more rebase for this one please?

**Comment by q384566678** [comment]
Rebased. PTAL

**Comment by TomSweeneyRedHat** [comment]
The test are failing as we've some tests that use a format of "dockerv2".  @nalind is it OK to change those test to pass just "docker" or do we need to be able to support a format of "docker", "dockerv1" and "dockerv2"?  Our documentation just has "docker" with no reference to the versions.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
