### PR TITLE
Adjust Ubuntu install info to also work on Pop!_OS

### PR DESCRIPTION
**Pull request by leorochael**
Tested on `Pop!_OS` 19.10

### CODE REVIEW

**Comment by rhatdan** [comment]
@leorochael You need to sign your PR.

git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
LGTM
Did not know about the ${ID**^**} syntax.

**Comment by TomSweeneyRedHat** [comment]
LGTM once tests are happy

**Comment by rhatdan** [comment]
Thanks @leorochael 
bors r+

**Comment by lsm5** [comment]
@leorochael mind creating a similar one for podman as well please, if not already?

**Comment by rhatdan** [comment]
bors retry

**Comment by rhatdan** [comment]
@cevich when you get back, can you remove the requirement for bors to have a approve setting. We maintain the two LGTM without having to go through multiple github operations.

**Comment by leorochael** [comment]
@lsm5, The podman installation instructions use a different template for the URL:

 - http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/

Which includes the `xUbuntu` segment literally, so the change above isn't necessary there as it already works for Pop!\_OS.

Truth be told, I could have "fixed" this PR by using the same URL from podman, since the installation section is explicitly talking about Ubuntu and there are no other `x{something}` folders at that URL.

**Comment by lsm5** [comment]
> @lsm5, The podman installation instructions use a different template for the URL:
> 
>     * [http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/](http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$%7BVERSION_ID%7D/)
> 

Ack, sgtm, thanks again!

**Comment by cevich** [comment]
> when you get back, can you remove the requirement for bors to have a approve setting. We maintain the two LGTM without having to go through multiple github operations.

I thought I took care of that, IIRC this `0` setting means only 'bors r+' should be needed.

https://github.com/containers/buildah/blob/master/bors.toml#L41-L44

**Pull request merged**
