### PR TITLE
Not use local image create/add manifest

### PR DESCRIPTION
**Pull request by QiWang19**
Avoid first checking the image from local storage for `manifest create` and `manifest add`
since the local image does not include other entries of the list from the registry.
`--all` flag of `manifest create` and `manifest add` can not add all of the lists as expected.
So first attempt to get manifest from the registry and if not successful, fall back to use local images.

Signed-off-by: Qi Wang <qiwan@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 does this address an issue or BZ?  If so, please add a pointer to the description.

**Comment by QiWang19** [comment]
> @QiWang19 does this address an issue or BZ? If so, please add a pointer to the description.

This does not point to an issue. Just found this may cause problems when I debug other manifest issues.

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but definitely want a head nod from @nalind.

**Pull request merged**
