### PR TITLE
[CI:DOCS] CONTRIBUTING.md: Update contact information

### LINKED ISSUE #4308: CONTRIBUTING.md out of date? Freenode?
The `CONTRIBUTING.md` file directs new contributors to the `#buildah` channel on `irc.freenode.net`, which appears to be dead. It also appears there may have been some major changes and drama at freenode in the last year that resulted in many projects and individuals moving to libera.chat, or other platforms.

Is `CONTRIBUTING.md` out of date? What are the current recommendations for communication? Where should more general questions that aren't direct issues with this repository or software go? Such as if someone had questions on how to contribute, standards, or similar? Or is it just that no one has the time or interest for that relating to this project?

### PR DESCRIPTION
**Pull request by AndASM**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
The contributor documentation is out of date.
#### How to verify it
See #4313 and CONTRIBUTING.md
#### Which issue(s) this PR fixes:
Fixes #4308 

#### Special notes for your reviewer:
Continuing from #4313. We couldn't re-open the last pull request.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM
@flouthoc @TomSweeneyRedHat @vrothberg @nalind @ashley-cui PTAL

**Review by flouthoc — APPROVED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
/lgtm

**Comment by TomSweeneyRedHat** [comment]
Thx @rhatdan !  LGTM FWIW.

**Comment by AndASM** [comment]
@TomSweeneyRedHat Sorry if it's not ideal. I hope it's still an improvement. Out of curiosity, what are the current issues in your view?

**Pull request merged**
