### PR TITLE
Tag a v1.32.0 release

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Prepare to tag a new v1.32.0 release.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by nalind** [comment]
@rhatdan @flouthoc PTAL

**Comment by nalind** [comment]
@TomSweeneyRedHat @lsm5 PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

and Thanks, was just working on this.

**Review by lsm5 — APPROVED** [review]
/approve
/lgtm
/hold

**Comment by lsm5** [comment]
not sure why some tasks were cancelled. Is that expected?

**Comment by nalind** [comment]
> not sure why some tasks were cancelled. Is that expected?

A running test gets canceled if it depends on another that failed.  If the failed test was a fluke and it's re-run, and passes, the canceled test gets requeued.

**Pull request merged**
