### PR TITLE
Check nonexsit authfile

### PR DESCRIPTION
**Pull request by QiWang19**
Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by TomSweeneyRedHat** [comment]
@rhatdan PTAL

**Comment by TomSweeneyRedHat** [comment]
Happy green test buttons.

**Comment by rhatdan** [comment]
Sadly @QiWang19 Needs a rebase.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
