### PR TITLE
[WIP] vendor c/image@9911c94 for golang+openssl support

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

### CODE REVIEW

**Comment by rhatdan** [comment]
Why is this DO NOT MERGE?

**Comment by lsm5** [comment]
> Why is this DO NOT MERGE?

just making sure I don't mess up :D, and the c/image vendoring looks like a downgrade if a commit is specified.

**Comment by rhatdan** [comment]
Yes, This should stay WIP, until we cut containers/image v4.0.0, which will hopefully happen today.

**Comment by rhatdan** [comment]
I think the latest PRs for containers/image 4.0 replace this one.  Reopen if I am mistaken.

**Pull request closed without merging**
