### PR TITLE
Touchup pull manpage

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Touch up the buildah pull man page to remove the from scratch from the title.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan this is another PR that should be in v1.4 but Red Hat CI is faling here too with unrelated issues.  Is there someone we can ping about Red Hat CI, looks like most of are PRs are hung up there.

**Comment by vrothberg** [comment]
LGTM
@TomSweeneyRedHat if it's urgent, I guess we can merge it manually.

**Comment by rhatdan** [comment]
LGTM
Merging manually.

**Pull request merged**
