### PR TITLE
Cirrus: Update VM images w/ updated bats

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

> /kind other

#### What this PR does / why we need it:

Simply updated images with newer versions of bats and disabling of F35 tests (missing golang 1.18)

Ref: https://github.com/containers/automation_images/pull/140
        and
        https://github.com/containers/automation_images/pull/149
        and
        https://github.com/containers/automation_images/pull/146

#### How to verify it

CI will pass

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
LGTM

**Comment by cevich** [comment]
Re-run failed tasks, looked like a CDN failure on one, assuming the same for others.

**Comment by cevich** [comment]
Force-push: Rebased + stuck in new images (built yesterday).

**Comment by rhatdan** [comment]
@cevich is this still a draft?

**Comment by rhatdan** [comment]
LGTM

**Comment by cevich** [comment]
Ohh it passed!  Yay.

**Comment by cevich** [comment]
Force-push: Rebased.

**Comment by cevich** [comment]
This is ready to go.

**Pull request merged**
