### PR TITLE
chore: pkg imported more than once

### PR DESCRIPTION
**Pull request by testwill**
#### What type of PR is this?

> /kind cleanup

#### What this PR does / why we need it:
pkg is being imported more than once (ST1019)
#### How to verify it
staticcheck
#### Does this PR introduce a user-facing change?

```release-note
None
```

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by rhatdan** [comment]
Thanks @testwill 
/approve
LGTM
Could you repush your PR so that the NO NEW TESTS NEEDED flag will apply.

git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
@cevich @edsantiago staticcheck might be worth including in pre-commit / validate

**Comment by cevich** [comment]
> @cevich @edsantiago staticcheck might be worth including in pre-commit / validate

I see something similar(?) listed under "enabled by default" for golang-ci-lint.  Maybe this would be good enough?  I also see in out `.golangci.yml` we have an "enable" list that doesn't include it.  I can open a PR that adds it in to see what happens.

**Comment by edsantiago** [comment]
@cevich I submitted #4884 (prior to this PR, so it should fail, that's deliberate).

**Pull request merged**
