### PR TITLE
WIP - test copy-detection

### PR DESCRIPTION
**Pull request by vrothberg**
ImageDestination.{PutBlob,TryReusingBlob} are extended to receive the
index of the layer in the corresponding image. Some transports,
containers storage in particular, require the layers to be comitted in
sequence. The new sequencing allows containers storage to commit the
layers in PutBlob.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
We hit time outs again due to the `traviswait` script. I opened https://github.com/containers/buildah/pull/1488 to fix it and rebased the PR here on top.

**Comment by rhatdan** [comment]
@vrothberg Can we update and merge this now?

**Comment by vrothberg** [comment]
> @vrothberg Can we update and merge this now?

Not yet. The integration tests seem to have a hiccup and we need to merge the PR at c/image first.

**Comment by rhatdan** [comment]
We have an up2date containers/image in buildah, should we close this PR?

**Comment by vrothberg** [comment]
@rhatdan, this PR is for testing the copy-detection PR for containers/image. I renamed this one here to avoid confusion.

**Comment by rhatdan** [comment]
Thanks @vrothberg

**Comment by rhatdan** [comment]
@vrothberg Any movement on this?

**Comment by vrothberg** [comment]
> @vrothberg Any movement on this?

https://github.com/containers/image/pull/611 needs to be reviewed, which is time-consuming. FWIW the CI of Skopeo, Buildah and Podman are happy with the changes. The recursive-lock semantics are now in storage, so we only need to iron out the bits in c/image.

**Comment by vrothberg** [comment]
Closing as the c/image PR has stalled.

**Pull request closed without merging**
