### PR TITLE
[CI:DOCS] Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

#### What type of PR is this?

 /kind other

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None

```

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@cevich 👀  please

**Comment by TomSweeneyRedHat** [comment]
@naveensrinivasan you may need a rebase
Changes LGTM, but I want @cevich to weigh in.

**Review by cevich — APPROVED** [review]
LGTM

**Pull request merged**
