### PR TITLE
install.md: add section about vendoring

### PR DESCRIPTION
**Pull request by vrothberg**
Add a section about how we do vendoring and to troubleshoot related
issues.  Note that the text is a verbatim copy from libpod's
install.md.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by vrothberg** [comment]
```
$ git checkout -qf 3f9e0d40a35bdd6e02022cf555a10e0f0e51e77d
fatal: reference is not a tree: 3f9e0d40a35bdd6e02022cf555a10e0f0e51e77d
The command "git checkout -qf 3f9e0d40a35bdd6e02022cf555a10e0f0e51e77d" failed and exited with 128 during .
```

I'll repush. Homu/Ubuntu went wild.

**Comment by vrothberg** [comment]
@rh-atomic-bot r=rhatdan

**Pull request closed without merging**
