### PR TITLE
Replace Ubuntu -> Debian SID

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Replace use of Ubuntu with Debian SID CI VM Images.

#### How to verify it

CI will pass

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Ref: https://github.com/containers/automation_images/pull/250

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
```
[+1668s] not ok 467 ignore-socket
[+1668s] # (from function `die' in file ./helpers.bash, line 332,
[+1668s] #  in test file ./copy.bats, line 274)
[+1668s] #   `die "Timed out waiting for ${TEST_SCRATCH_DIR}/test.socket (is nc installed?)"' failed
[+1668s] # /var/tmp/go/src/github.com/containers/buildah/tests /var/tmp/go/src/github.com/containers/buildah/tests
[+1668s] # nc: invalid option -- 'U'
```
Wrong `nc`. Solution:
```console
# apt-get install ncat <----- yes, "ncat", exactly like that
# update-alternatives --set nc /usr/bin/ncat
```
(scriptifying that is left as an exercise for the reader)

**Comment by cevich** [comment]
Thanks @edsantiago I just finished figuring that all out on my own...THEN found your comment lol.

**Comment by cevich** [comment]
Ref: https://github.com/containers/automation_images/pull/256

**Comment by cevich** [comment]
@nalind could you help me with the Conformance test failures? They appear legitimate to me but I'm nowhere near an expert.  This is the output from installing docker/containerd:

```
[+0001s] Installing previously downloaded/cached Docker packages
[+0002s] Selecting previously unselected package containerd.io.
[+0002s] dpkg: considering removing runc in favour of containerd.io ...
[+0002s] dpkg: yes, will remove runc in favour of containerd.io
[+0005s] (Reading database ... 101253 files and directories currently installed.)
[+0005s] Preparing to unpack .../containerd.io_1.6.18-1_amd64.deb ...
[+0005s] Unpacking containerd.io (1.6.18-1) ...
[+0007s] Removing runc (1.1.4+ds1-1+b2), to allow configuration of containerd.io (1.6.18-1) ...
[+0007s] Selecting previously unselected package docker-ce-cli.
[+0007s] Preparing to unpack .../docker-ce-cli_5%3a23.0.1-1~debian.11~bullseye_amd64.deb ...
[+0007s] Unpacking docker-ce-cli (5:23.0.1-1~debian.11~bullseye) ...
[+0009s] Selecting previously unselected package docker-ce-rootless-extras.
[+0009s] Preparing to unpack .../docker-ce-rootless-extras_5%3a23.0.1-1~debian.11~bullseye_amd64.deb ...
[+0009s] Unpacking docker-ce-rootless-extras (5:23.0.1-1~debian.11~bullseye) ...
[+0010s] Selecting previously unselected package docker-ce.
[+0010s] Preparing to unpack .../docker-ce_5%3a23.0.1-1~debian.11~bullseye_amd64.deb ...
[+0010s] Unpacking docker-ce (5:23.0.1-1~debian.11~bullseye) ...
[+0012s] Setting up containerd.io (1.6.18-1) ...
[+0012s] Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /lib/systemd/system/containerd.service.
[+0013s] Setting up docker-ce-cli (5:23.0.1-1~debian.11~bullseye) ...
[+0013s] Setting up docker-ce-rootless-extras (5:23.0.1-1~debian.11~bullseye) ...
[+0013s] Setting up docker-ce (5:23.0.1-1~debian.11~bullseye) ...
[+0014s] Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
[+0014s] Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
[+0016s] Processing triggers for runit (2.1.2-54) ...
[+0016s] Processing triggers for man-db (2.11.2-1) ...
[+0028s] Configuring /etc/containers/registries.conf
```

**Comment by cevich** [comment]
Update: I fired up the current (from `main`) Ubuntu CI VMs and find the following:

```
containerd.io_1.6.15-1_amd64.deb
docker-ce-cli_5%3a20.10.22~3-0~ubuntu-jammy_amd64.deb
docker-ce-rootless-extras_5%3a20.10.22~3-0~ubuntu-jammy_amd64.deb
docker-ce_5%3a20.10.22~3-0~ubuntu-jammy_amd64.deb
docker-scan-plugin_0.23.0~ubuntu-jammy_amd64.deb
pigz_2.6-1_amd64.deb
```

So the conformance issues may be due to the newer versions.

**Comment by nalind** [comment]
Is it possible to use the same versions of docker-ce on sid and Fedora?

**Comment by cevich** [comment]
> Is it possible to use the same versions of docker-ce on sid and Fedora?

Possibly, and likely by manually hard-coding then rebuilding the VM images :scream:  Then they're also unlikely to represent the versions run by Debian users :disappointed:  Are these versions known-broken in some way, or is there some other good reason to not use them?

For ref: [I'm already hard-coding the Debian release name](https://github.com/containers/automation_images/blob/50c823201c376b67ecd5df0d1e33266a908ca6ba/cache_images/debian_packaging.sh#L150
) (for lack of an easy way to get SID-1) when installing Docker.  In other words, "bullseye" is Debian 11 and SID is 12 ("bookworm").

**Comment by nalind** [comment]
It's... difficult to conform to the behavior of multiple different target versions at the same time.

**Comment by nalind** [comment]
When I install unstable here, the default docker.io version is 20.10.23+dfsg1-1+b1.  Is the VM getting its packages from somewhere else?

**Comment by cevich** [comment]
> It's... difficult to conform to the behavior of multiple different target versions at the same time.

Gotcha, yeah that's probably a PITA.  At least these tests are only running on Debian and not Fedora also :grin: 

> When I install unstable here

Clarification, the link I posted (above) is to [the VM image build script that installs docker](https://github.com/containers/automation_images/blob/50c823201c376b67ecd5df0d1e33266a908ca6ba/cache_images/debian_packaging.sh#L150).  It's pretty stimple, though I believe it's the latest stable version, not unstable.  Only the Debian OS is "unstable".  I could change this, but I think it might make the problem worse.

Another idea...would it be appropriate for me to just file issues and skip these tests for now with "FIXME reasons"?

**Comment by cevich** [comment]
Force-push: rebased.

**Comment by cevich** [comment]
In case it helps, I ran `docker version` and got:

```
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:54 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:54 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by cevich** [comment]
force-push: rebased

**Comment by TomSweeneyRedHat** [comment]
LGTM
but want a head nod from @nalind, especially concerning the conformance test changes
Happy green test buttons.

**Comment by cevich** [comment]
@nalind ping

**Comment by nalind** [comment]
#4639 solves my main issues, the rest looks fine.

**Comment by cevich** [comment]
force-push: Rebased.

Thanks Nalin.

**Pull request merged**
