### PR TITLE
[CI:DOCS] Switch golang 1.12 to golang 1.13

### PR DESCRIPTION
**Pull request by rhatdan**
Tutorials have an unsuported golang version referenced.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat @vrothberg @ashley-cui @QiWang19 PTAL

**Comment by QiWang19** [comment]
LGTM

**Comment by rhatdan** [comment]
bors retry

**Comment by rhatdan** [comment]
Saving the planet.

**Pull request merged**
