### PR TITLE
Fix auth.json path (validated on Fedora 38)

### PR DESCRIPTION
**Pull request by andrm**
Fix path of auth.json file.

Signed-off-by: Andreas Mack <andreas.mack@gmail.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
/kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:
I search 15 minutes for the auth.json file. It seems the documentation is wrong.

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by flouthoc** [comment]
@andrm Could you please sign the commit.

**Comment by andrm** [comment]
Ok, I think I've signed it, not sure if I did it correctly.

**Comment by andrm** [comment]
@flouthoc can you add the "lgtm" label?

**Review by flouthoc — APPROVED** [review]
LGTM
@containers/buildah-maintainers PTAL

**Comment by nalind** [comment]
LGTM.  Thanks!

**Comment by TomSweeneyRedHat** [comment]
LGTM, thanks @andrm .  I'll merge once the test wrap up.

**Pull request merged**
