### PR TITLE
Bump c/storage to v1.39.0 in main

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.  This is in preparation for the Fedora release.

Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mheon FYI  Once this and @giuseppe 's Docker fix gets in, we should be gtg

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/hold

I have restarted the flaking test.

**Pull request merged**
