### PR TITLE
Pr 1 (Add xz package)

### PR DESCRIPTION
**Pull request by jobcespedes**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake

/kind other

#### What this PR does / why we need it:
It adds xz package. It is required by buildah and podman when building a image and ADD a tar.xz file archive is used
#### How to verify it
1. Clone https://github.com/krestomatio/centos8-minimal
2. Build inside quay.io/buildah/stable
3. Run the container. 
#### Which issue(s) this PR fixes:

Fixes 2525

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
BTW Why does podman require xz?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by jobcespedes** [comment]
> BTW Why does podman require xz?
 I did the same image build with buildah and with podman. Same error in both image builds.

**Comment by rhatdan** [comment]
Yes I found where it execs the xz command.

**Comment by TomSweeneyRedHat** [comment]
@jobcespedes didn't catch this and should have earlier.  Please use a descriptive title in your commits in the future.  The commit title gets included in the Changelog and release notes and "R1" doesn't tell you much about the change.  I've added a small parenthical for now.  Thx!

bors retry

**Pull request merged**
