### PR TITLE
Bump 1.19.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@vrothberg @rhatdan @nalind PTAL

**Comment by rhatdan** [comment]
/lgtm
/hold
You will need to cherry pick this back to the 1.3 branch.

**Review by vrothberg — COMMENTED** [review]
LGTM
Thanks, @TomSweeneyRedHat !

**Comment by TomSweeneyRedHat** [comment]
@rhatdan 1.3 branch?

**Comment by nalind** [comment]
Wrinkling my nose at tagging a non-".0" release on master.  What's the plan here?

**Comment by TomSweeneyRedHat** [comment]
/hold
until @nalind thought is addressed

**Comment by TomSweeneyRedHat** [comment]
No planning here.  You think this should have been spun up on the 1.19 branch?  We'll have to pick @vrothberg 's fix I think.

**Comment by rhatdan** [comment]
This PR should go against release-1.19 not master

**Comment by TomSweeneyRedHat** [comment]
Closing, will make in 1.19 branch.

**Pull request closed without merging**
