### PR TITLE
Add missing step in installing into Ubuntu

### PR DESCRIPTION
**Pull request by cheesiong-lee**

### CODE REVIEW

**Comment by rhatdan** [comment]
@cheesiong-lee You must sign your PR

git commit -a --amend -s
git push --force

LGTM
@lsm5 PTAL

**Comment by TomSweeneyRedHat** [comment]
@cheesiong-lee thanks for signing, but now it looks like you've got two files that don't belong with this PR.  I think you need to rebase before pushing.  If you need help with that or would like me to spin up a PR to do this change, please let me know.

**Comment by rhatdan** [comment]
git rebase -i origin 
git push --force

**Comment by cheesiong-lee** [comment]
> git rebase -i origin
> git push --force

Sorry for the mistake and thanks for your command. 
Now, there is only 1 files changed.

Let me know if you need me close this PR and create another PR for the same codes?

**Comment by TomSweeneyRedHat** [comment]
No worries @cheesiong-lee , thanks so much for sticking with it.  You shouldn't need to do another PR at this point, this should be good to go.  However Travis is not happy at the moment, I don't think it has anything to do with your changes.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan or @vrothberg the bot seems to be ignoring me and the tests were cancelled due to some other job running first?  Can one of you try kicking the bot please?

**Comment by rhatdan** [comment]
@rh-atomic-bot r+
@cheesiong-lee Thanks.

**Pull request closed without merging**
