### PR TITLE
[NO TESTS NEEDED] Remove buildah bud --loglevel ...

### PR DESCRIPTION
**Pull request by rhatdan**
This was never hooked up and just causes confusion for users.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/buildah/issues/3175

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Comment by nalind** [comment]
LGTM, please rebase.

**Comment by edsantiago** [comment]
LGTM. The string `Loglevel` (capital ell) no longer appears in the tree; and `loglevel` (lower case) only appears in changelogs and in the newly-deprecated code block.

**Comment by edsantiago** [comment]
Is there a way to silence the @#$%^ "This branch is out-of-date with the base branch" message? It is anti-useful, sowing confusion and chaos and the toxic carbon emissions of unnecessary CI runs.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
