### PR TITLE
pkg/supplemented test: replace our null blobinfocache

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

In our tests, drop our own doesn't-do-anything BlobInfoCache implementation, and just use the one provided by the image library.

#### How to verify it

Tests should continue to pass.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Although it's claiming it's needing a rebase, not sure the merge will happen.

**Comment by mtrmac** [comment]
I haven’t really followed this code and I have no idea about the motivation — just for the record, c/image/pkg/blobinfocache/none.NoCache` exists.

**Comment by mtrmac** [comment]
… and of course that’s what this PR does use. I’m sorry.

**Comment by nalind** [comment]
No worries.  Thanks for confirming.

**Pull request merged**
