### PR TITLE
make,cross: restore loong64

### PR DESCRIPTION
**Pull request by michalbiesek**
Ref: 50a4acb, 5d50a73

#### What type of PR is this?

/kind cleanup

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
a couple of tests were'nt hip, I've re-run them.

**Review by flouthoc — APPROVED** [review]
This needs rebase.

**Pull request merged**
