### PR TITLE
vendor: use faster version instead compress/gzip

### PR DESCRIPTION
**Pull request by rhatdan**
Update vendoring of containers/storage and containers/image to improve
pulls and pushes compression speeds.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @vrothberg Might want to look at these failures.

**Comment by vrothberg** [comment]
`"error parsing image name \"localhost/busybox\", trying with transport \"docker://\": Invalid image name \"localhost/busybox\", expected colon-separated transport:reference"`

... which does not make much sense to me at the moment.

**Comment by vrothberg** [comment]
> ... which does not make much sense to me at the moment.

The failing tests passes for me locally. I restarted Travis and will have another look tomorrow.

**Comment by vrothberg** [comment]
@rhatdan I continue this PR over here https://github.com/containers/buildah/pull/1244 to put the parallel copying on top. (closing)

**Pull request closed without merging**
