### PR TITLE
dumpbolt: handle nested buckets

### PR DESCRIPTION
**Pull request by nalind**
When iterating through a bucket, a key with no value is a sub-bucket.  Dump the contents of those buckets after the non-sub-buckets.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
FYI @mheon

**Comment by mheon** [comment]
@nalind TY for looking into this - we use sub-buckets a lot in the libpod schema

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
