### PR TITLE
Update to F37 CI VM Images, re-enable prior-fedora

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Update to F37 CI VM Images, re-enable prior-fedora

#### How to verify it

CI will pass

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
Oof, this needs code changes.  I had to do this for podman as well.  It's a pain.

**Comment by cevich** [comment]
@containers/buildah-maintainers PTAL, any idea whats up with the `TestMountsSort` failure in the new F37 CI environment?  I eyeballed all my `io/utils` fixups and they seem correct, but maybe the underlying semantics changed?

**Comment by nalind** [comment]
> @containers/buildah-maintainers PTAL, any idea whats up with the `TestMountsSort` failure in the new F37 CI environment?

It's a bug in the function being tested; #4441 aims to fix it.

**Comment by cevich** [comment]
Thanks @nalind I'll rebase and try again.

**Pull request merged**
