### PR TITLE
imagebuildah: handle --manifest directly

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

When we're told to add built images to a manifest list, manipulate the list ourselves, so that if we're creating a list, we won't have a partially-populated list if some of the builds fail.

This also lets us include all of the platform information (including variant info, which we can't sniff out after the fact) that we were given when we started building the images.

#### How to verify it

New integration test!

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by nalind** [comment]
Rebased.

**Comment by TomSweeneyRedHat** [comment]
LGTM
@nalind, looks like you haven't rebased this one enough yet....

**Pull request merged**
