### PR TITLE
Added tutorial on how to include Buildah as library

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Follow up of https://github.com/containers/buildah/issues/1819

Signed-off-by: slinkydeveloper <francescoguard@gmail.com>

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@TomSweeneyRedHat of course, what should i write on it? An extended version of this tutorial? Can you point me where should i write it?

Anyway, I think it would be wise to publish the godocs of buildah together with this tutorial :smile:

**Comment by TomSweeneyRedHat** [comment]
@slinkydeveloper buildah.io uses *.md format for the blog posts.  Once this is complete, I'd use this tutorial as the starting point and perhaps add a bit more introductory verbiage.  buildah.io runs from a GitHub repository, so you'd just need to do the standard clone, add, commit, push loop to that repo.

The repo lives at:  https://github.com/containers/buildah.io  and the README.md has a small list of formatting/setting up stuff that you'll need to do.  The main ones are you'll need to add your info to `_config.yml` and then have the headers that are listed on that page in your blog post.

If you've any trouble with any of that, feel free to ping me.  If you find the directions in the README.md aren't clear, please let me know so we can clean them up.

Thanks!

**Comment by rhatdan** [comment]
@slinkydeveloper Thanks, might be worth writing this up as a blog and talking about how you are using it.

@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
@slinkydeveloper I'm seeing a strange error the homu tests:

```
$ make vendor
0.27s$ ./hack/tree_status.sh
tree is dirty, please commit all changes and sync the vendor.conf
```

Can you `git fetch`, `git rebase` and push again please?  @rhatdan other thoughts?

**Comment by slinkydeveloper** [comment]
Rebased and stashed, hope it works :smile:

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons!  Thanks @slinkydeveloper !

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
