### PR TITLE
Builtin volumes should be owned by the UID/GID of the container

### PR DESCRIPTION
**Pull request by rhatdan**
When creating a building VOLUME for a container we need to create it
with the ownership/permsissions of the directory that we will be mounting on.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/containers/buildah/issues/1027

**Comment by rhatdan** [comment]
@pkubatrh
PTAL

**Comment by rhatdan** [comment]
@umohnani8 @giuseppe @vrothberg @pixdrift @boaz1337 PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=umohnani8

**Comment by giuseppe** [comment]
bot, retest this please

**Comment by pkubatrh** [comment]
Does not fix #1027 for me - now the owner of the directory is the container user, so 26:26 in my case. But it is expected to have 26:0 since that is what the directory's permissions are supposed to be when no VOLUME command is used.

Additionally the volume still has incorrect permissions of 0755 instead of 0775

```
$ buildah bud .
STEP 1: FROM centos/postgresql-10-centos7
Getting image source signatures
Skipping fetch of repeat blob sha256:256b176beaff7815db2a93ee2071621ae88f451bb1e198ca73010ed5bba79b65
Skipping fetch of repeat blob sha256:efb19fea0fdb7178d5deedd98a3cbf90284dbc01f468e1dc8117b2d1becd34e9
Skipping fetch of repeat blob sha256:b4570fdc208ced0033bf04a67323eda6cd72d92bcfab46bac200860a587722cc
Skipping fetch of repeat blob sha256:213e4e250552a0d0e7e7c69ef31e783085154c9cf91cea80ed705b3eb5a35cc0
Copying blob sha256:7abe93ab1e76c5e499267463d1a865b34de7fc03967f604e4d7e8fc3dccdb9ad
 312 B / 312 B [============================================================] 0s
Copying blob sha256:120c365f623c8f32572892060297e66e9204d2be544a73ee62c2189bb32a2769
 32.89 MiB / 32.89 MiB [====================================================] 1s
Copying blob sha256:c4cdb786be2e3c8da9138910076fa8e2dfd3f9200f7c387984b5b85216292bdc
 14.27 KiB / 14.27 KiB [====================================================] 0s
Copying blob sha256:299531d7552ba9babdc195e00af0a0ab3cfbeef6aba96040b2cbfc14693619a9
 427 B / 427 B [============================================================] 0s
Copying blob sha256:655a4ead385105c0afc12f4f5e409d33cfb88286e813cb5fd75ad31c5276207e
 1.21 KiB / 1.21 KiB [======================================================] 0s
Copying config sha256:5b484f427307b8752edf50fb9270bdc0cd79d6adc29da4bdf572b37ed15feeaf
 14.50 KiB / 14.50 KiB [====================================================] 0s
Writing manifest to image destination
Storing signatures
STEP 2: RUN stat /var/lib/pgsql/data
  File: '/var/lib/pgsql/data'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fd02h/64770d	Inode: 7607796     Links: 2
Access: (0755/drwxr-xr-x)  Uid: (   26/postgres)   Gid: (   26/postgres)
Access: 2018-09-19 05:42:20.832130845 +0000
Modify: 2018-09-19 05:42:20.855130425 +0000
Change: 2018-09-19 05:42:20.855130425 +0000
 Birth: -

$ sudo docker-binary build .
Sending build context to Docker daemon 20.75 MB
Step 1/2 : FROM centos/postgresql-10-centos7
 ---> 83b475f66214
Step 2/2 : RUN stat /var/lib/pgsql/data
 ---> Running in 58b6d3a6b611
  File: '/var/lib/pgsql/data'
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d	Inode: 525492      Links: 2
Access: (0775/drwxrwxr-x)  Uid: (   26/postgres)   Gid: (    0/    root)
Access: 2018-09-19 05:43:56.509381227 +0000
Modify: 2018-09-19 05:43:56.496381465 +0000
Change: 2018-09-19 05:43:56.509381227 +0000
 Birth: -
 ---> 7d197580c09a
Removing intermediate container 58b6d3a6b611
Successfully built 7d197580c09a
```

**Comment by rhatdan** [comment]
@pkubatrh You were right, I think I have fixed it now.  The volume should have the same ownership/permissions of the volume it will be mounting over.

**Comment by pkubatrh** [comment]
@rhatdan Can confirm this fixes my use case now. Thanks!

**Comment by rhatdan** [comment]
@rh-atomic-bot r=pkubatrh

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
Homu does not seem to be working.  Merging manually.

**Pull request merged**
