### PR TITLE
move footnotes on divisive language to exactly where divisive language is used

### PR DESCRIPTION
**Pull request by krumelmonster**
My commit is not signed or using a realname but I don't believe that the changes I've made can be subject to copyright.

#### What type of PR is this?

> /kind documentation

#### What this PR does / why we need it:

I got a bit confused when reading the manpage as the footnote on problematic and divisive language appeared after a sentence that doesn't use problematic and divisive language and I think moving the footnote to just after the wording deemed problematic makes the manpage more readable

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@krumelmonster nice change!  Unfortunately our CI won't take a PR unless it's signed.  Can you do a `git commit --amend -s` and then also add `[CI:DOCS]` to the title.  That tag will bypass a lot of testing that's not needed for a documentation submission like this one.  Then do git fetch, rebase and push and it should be GTG.

LGTM other than the CI unhappiness.

**Comment by edsantiago** [comment]
@TomSweeneyRedHat see  https://github.com/containers/podman/pull/20983

I'm working on that on the podman side, and I can take this one on as well with @krumelmonster's permission.

**Comment by krumelmonster** [comment]
Thank you for picking it up @edsantiago! I really like podman and buildah for being tools that can be understood based on documentation and manpage

@TomSweeneyRedHat I knew I could sign it but I was insecure whether a signature with a non-legal name would be frowned upon. I take your comment as an invitation to make pull requests under the krumelmonster with which I'm active in OSS in the future, it is very appreciated.

**Comment by TomSweeneyRedHat** [comment]
Works for me @krumelmonster , thanks!

**Pull request closed without merging**
