### PR TITLE
Vendor in latest content from github.com/containers and opencontainers

### PR DESCRIPTION
**Pull request by rhatdan**
Update opencontainers/selinux to fix potential race condition when relabeling.
Update containers/image to pull in some debugging improvements and small potential
bugs
Update containers/libpod to fix small potential bugs.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @umohnani8 @TomSweeneyRedHat @vrothberg @nalind @pixdrift PTAL

Want to vendor in latest code before we cut 1.5 release.

**Comment by TomSweeneyRedHat** [comment]
LGTM, as  you noted we'll want to get #118 too.

**Comment by TomSweeneyRedHat** [comment]
#1188 that is.

**Comment by giuseppe** [comment]
LGTM

**Comment by giuseppe** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
