### PR TITLE
bump c/image to v5.19.3 and c/ocicrypt to v1.1.4

### PR DESCRIPTION
**Pull request by lsm5**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

This PR vendors a new c/ocicrypt which doesn't default to sha1 and thus desirable in upcoming versions of fedora and rhel.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
Bump c/image to v5.19.3 and c/ocicrypt to v1.1.4
```

### CODE REVIEW

**Comment by lsm5** [comment]
@nalind @vrothberg @TomSweeneyRedHat @rhatdan @mtrmac PTAL

**Comment by rhatdan** [comment]
Why are we back porting?

**Comment by lsm5** [comment]
> Why are we back porting?

mainly to get rid of sha1 default in ocicrypt. If we are to vendor this in podman v4.0-rhel branch, wouldn't buildah need this too? release-1.24 is the relevant branch for it.

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
My point being do we plan on releasing this early or waiting for podman 4.2 and buildah 1.27?

**Comment by lsm5** [comment]
this stuff has already gone into main and  latest branches I think. I can confirm later today.

**Comment by lsm5** [comment]
> My point being do we plan on releasing this early or waiting for podman 4.2 and buildah 1.27?

We need this in v4.0-rhel so that's why the backport. So, nothing to do with podman v4.2 or buildah 1.27.

**Comment by rhatdan** [comment]
/lgtm
I am still not sure we are going to ship new v4.0 RHEL but more likely to ship v4.1 or v4.2 Since we don't lock down to 9.1 and 8.7 as I understand it.

**Comment by lsm5** [comment]
> /lgtm I am still not sure we are going to ship new v4.0 RHEL but more likely to ship v4.1 or v4.2 Since we don't lock down to 9.1 and 8.7 as I understand it.

Thanks for the merge. AFAIK, we're going to have 9.0.0.1 which will ship from v4.0-rhel branch. @TomSweeneyRedHat can correct me if I got that wrong.

**Comment by TomSweeneyRedHat** [comment]
@lsm5 that's understanding for 9.0.0.1.

**Pull request merged**
