### PR TITLE
Vendor containers/storage v1.11-dev

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Vendor in containers/storage 1.11-dev.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
@TomSweeneyRedHat why not vendor v1.10?

**Comment by TomSweeneyRedHat** [comment]
Thought we needed latest/greatest @vrothberg?

**Comment by vrothberg** [comment]
> Thought we needed latest/greatest @vrothberg?

v1.10 is the latest :) Dan and I were secretly cutting it over the weekend (https://github.com/containers/storage/releases/tag/v1.10).

**Comment by vrothberg** [comment]
I always prefer vendoring releases of our libraries before cutting a new release for Buildah and Podman. This will hopefully ease packaging for Debian and grow confidence of that community.

**Comment by TomSweeneyRedHat** [comment]
Thanks @vrothberg I'm going to close this PR and will spin up a new one.  Backtracking to an earlier version in the same branch always gives me the willies.

**Pull request closed without merging**
