### PR TITLE
Replace map[K]bool with map[K]struct{} where it makes sense

### PR DESCRIPTION
**Pull request by serprex**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
`map[K]struct{}` is go's set type, in various places `map[K]bool` was being used as a set

#### How to verify it
No change in behavior

#### Which issue(s) this PR fixes:
None

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
/approve
@nalind @flouthoc @giuseppe @vrothberg PTAL

**Comment by rhatdan** [comment]
Lots of testing failures?

**Comment by serprex** [comment]
@rhatdan tests passing now

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
changes looks good but can you please squash your commits into one

**Comment by serprex** [comment]
@Luap99 done

**Pull request merged**
