### PR TITLE
Update 05-openshift-rootless-build.md

### PR DESCRIPTION
**Pull request by l0rd**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

When I tried to run "Buildah Tutorial 5" last step I got the following error:

```bash
$ buildah -v /home/build/output:/output:rw -v /home/build/test-script.sh:/test-script.sh:ro build -t myimage -f Containerfile.test
unknown command "build" for "buildah"

Did you mean this?
	build-using-dockerfile
```

To fix it I have replaced buildah "build" command with "build-using-dockerfile".

### CODE REVIEW

**Comment by flouthoc** [comment]
@l0rd Original documentation is correct following PR https://github.com/containers/buildah/pull/3368 did a sed on `/bud/build` so on older version try with `bud` it should work on newer versions `build` will also work.

**Comment by rhatdan** [comment]
This LGTM, for now.

@l0rd you need to sign your commits.

git commit -a --amend -s
git push --force

**Comment by l0rd** [comment]
@flouthoc from the doc "The instructions have been tested on OpenShift 4.3.28 with Buildah 1.14.8" and "`FROM quay.io/buildah/stable:v1.14.8`" make `v1.14.8` the inevitable choice for those that are following the instructions step by step (as I did).

@rhatdan commit signed

Anyway I would be happy to update the doc to use the latest stable version of buildah (`v1.22.3`) and OpenShift (`v4.8`) if that's useful.

**Pull request merged**
