### PR TITLE
vendor: update containers/storage

### PR DESCRIPTION
**Pull request by giuseppe**
inherit some fixes for rootless overlay with fuse-overlayfs.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
LGTM
Thanks for the ping.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
LGTM and beat me to the punch.  TY @giuseppe !

**Pull request closed without merging**
