### PR TITLE
WIP: Vendor/test containers/storage store load lock branch

### PR DESCRIPTION
**Pull request by saschagrunert**
For testing purposes of https://github.com/containers/storage/pull/493

### CODE REVIEW

**Comment by rhatdan** [comment]
Would this cause buildah to actually use the new code?

**Comment by saschagrunert** [comment]
> Would this cause buildah to actually use the new code?

Yes, it should.

**Comment by rhatdan** [comment]
@saschagrunert Needs a rebase.

**Comment by saschagrunert** [comment]
Sure, rebased on top of the latest master branch

**Pull request closed without merging**
