### PR TITLE
wip - Storage rw locks

### PR DESCRIPTION
**Pull request by vrothberg**
This is a test PR to check for regressions using reader-writer locks in containers/storage.

### CODE REVIEW

**Comment by rhatdan** [comment]
Needs a rebase, but we probably should wait til it gets merged into containers/storage.

**Comment by vrothberg** [comment]
> Needs a rebase, but we probably should wait til it gets merged into containers/storage.

Agreed. I would love to cut a containers/storage release once it's merged over there.

**Comment by rhatdan** [comment]
Its merged.

**Comment by vrothberg** [comment]
Closing another PR took care of it.

**Pull request closed without merging**
