### PR TITLE
DO NOT MERGE: Write output to stdout and not stderr

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

We had set the report writer to stderr so some info during
builds were being written to stderr. Move everything over
to stdout.

#### Which issue(s) this PR fixes:
Fixes https://github.com/containers/buildah/issues/2423

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by umohnani8** [comment]
@rhatdan any idea why my PRs are not automatically approved when I am an approver now?

**Comment by rhatdan** [comment]
This PR concerns me. since we might be breaking scripts. @nalind @TomSweeneyRedHat @vrothberg PTAL

**Comment by rhatdan** [comment]
Code LGTM

**Review by vrothberg — COMMENTED** [review]
I am afraid of backwards compatibility. Users will likely depend on on only the final image ID being printed on stdout.  I assume that many integration tests do as well.

**Comment by umohnani8** [comment]
@rhatdan @TomSweeneyRedHat I am seeing a few tests failing e.g https://cirrus-ci.com/task/4739030875111424?command=integration_test#L1032. I am a bit confused on how switching to stdout is causing the exit code to be 125 for those tests, do you have any idea?

**Comment by TomSweeneyRedHat** [comment]
I've dabbled in the stdout/stderr stuff in Buildah in the past and it looks simple, but has complex behaviors.  I'd like to sit on this one until after we get through the Podman v3.0 delivery then take a deeper dive.

**Comment by edsantiago** [comment]
@umohnani8 the root cause of at least one failure is this:

https://github.com/containers/buildah/blob/0ec651fd3c4a26eebaf3ca857b46138b23aec42e/tests/containers_conf.bats#L14

`buildah` should (almost) never be run in buildah gating tests. The correct usage is `run_buildah`, with the underscore.  This line is not something you touched, but by mucking with stdout/stderr the effect is:

  - old: the `$(...)` would capture stdout, which is only the container ID, which is nice and good
  + new: the `$(...)` captures stdout, including "Getting blah blah", so `$cid` is now "Getting blah blah"

This is a pretty standard existing convention: buildah and podman spit out verbose stuff to stderr, and the critical stuff (image ID, container ID) to stdout. Changing this will cause breakage worldwide.

Side note: I recommend installing [my greasemonkey log highlighter](https://github.com/edsantiago/greasemonkey/tree/master/podman-ginkgo-highlight). It is nearly impossible for a human to read podman/buildah CI logs without it.

**Comment by umohnani8** [comment]
Thank you for the tip @edsantiago, using the `--quiet` flag helped fix the test issues.

**Comment by vrothberg** [comment]
/hold

Let's find consensus.  I don't think we can merge without breaking an unknown number of users.  I am in favor of not merging as I am too afraid of the consequences.  Also, it would break own scripts :-D

**Comment by edsantiago** [comment]
I agree with the hold. @umohnani8 my comment wasn't intended to shut-up the tests, my goal was to demonstrate the problem and why it's not fixable. The `cid=$(buildah from ...)` pattern is, I'm afraid, universal. Breaking that would affect pretty much everyone who uses buildah, and would be unpopular. I would encourage us to think very carefully here.

**Comment by TomSweeneyRedHat** [comment]
Beyond any doubt, I don't want this potentially merging before Podman 3.0 goes out, bumped the title for now.

**Comment by umohnani8** [comment]
Closing as we can use the `--quiet` flag to suppress extra outputs to stderr.

**Pull request closed without merging**
