### PR TITLE
[CI:DOCS] docs: correct default authfile path

### PR DESCRIPTION
**Pull request by rhatdan**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```
Replaces #5294

### CODE REVIEW

**Comment by rhatdan** [comment]
@flouthoc @nalind @vrothberg @ashley-cui @wulfgarpro PTAL

**Comment by wulfgarpro** [comment]
@rhatdan, `auth.json` is stored at `/run/containers/0/auth.json` when rootful.

**Review by vrothberg — COMMENTED** [review]
I prefer pointing to `man containers-auth.json` instead?

**Comment by rhatdan** [comment]
Modified to point at man page.

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
