### PR TITLE
Move Host IDMAppings code from util to unshare

### PR DESCRIPTION
**Pull request by rhatdan**
This will make vendoring in pkg/unshare easier into other
packages like skopeo.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/containers/buildah/issues/1531

**Comment by rhatdan** [comment]
@vrothberg @TomSweeneyRedHat @nalind @giuseppe PTAL

**Comment by vrothberg** [comment]
Tests are not yet happy:
```
pkg/unshare/unshare_test.go:91:25: undefined: util.GetHostIDMappings
```

Otherwise, LGTM. Thanks a lot for the fix, @rhatdan!

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Pull request closed without merging**
