### PR TITLE
[release-1.27] Disable CI

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

As of 2023-06-01 there are no downstream distro. releases which depend on functional CI in this branch.  Disable CI and maintenance cirrus-cron job.

#### How to verify it

- [x] Manual confirmation with program management (e-mail sent)
- [x] Manual removal of `permanent=true` label from CI VM images w/ ID `c6013173500215296`

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
Got e-mail confirmation from PM:  "Okay to drop CI support".

**Comment by cevich** [comment]
CI VM Image `permanent=true` tag (manually) staged for update as soon as this PR merges.

**Comment by TomSweeneyRedHat** [comment]
@cevich on the off chance that we ever have to recover this file, does it make sense to rename rather than delete it?

**Comment by cevich** [comment]
> does it make sense to rename rather than delete it?

If this was a server then yes, but we've got a history in git, so it's no problem to just remove it IMHO.

**Comment by rhatdan** [comment]
@cevich is this ready to merge?

**Comment by TomSweeneyRedHat** [comment]
@cevich, if it's GTG, can you take the draft status down?

**Pull request merged**
