### PR TITLE
Move code around to not require libimage

### PR DESCRIPTION
**Pull request by Luap99**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:

Move code around to not require libimage, this allows the podman remote client to build without importing libimage which reduces its size. see https://github.com/containers/podman/pull/19718

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@mtrmac PTAL

**Comment by Luap99** [comment]
@nalind @rhatdan @flouthoc PTAL
Corresponding podman PR: https://github.com/containers/podman/pull/19951

**Review by mtrmac — COMMENTED** [review]
Note that this changes the public Go API of Buildah; I’m not sure if that makes any difference.

**Comment by Luap99** [comment]
> Note that this changes the public Go API of Buildah; I’m not sure if that makes any difference.

Yes `CleanCacheMount()` was moved from `pkg/parse` to `pkg/volumes`, not sure it that is important.
And `HardlinkChecker` was removed from `util` and moved to `copier` (but made private), not sure if that matters as well.

The main Builder API and types are untouched unless I am overlooking something.

**Comment by nalind** [comment]
> > Note that this changes the public Go API of Buildah; I’m not sure if that makes any difference.
> 
> Yes `CleanCacheMount()` was moved from `pkg/parse` to `pkg/volumes`, not sure it that is important.

`podman` calls it from there.

**Comment by TomSweeneyRedHat** [comment]
I've added the WIP on it as the Podman tests look to be failing and I don't want to accidentally merge this prior.  Feel free to remove the hold once the tests are hip.

Overall the changes LGTM, I'm not sure if the issue in Podman is due to something not being moved as it expected.

**Review by mtrmac — COMMENTED** [review]
Thanks

**Comment by edsantiago** [comment]
This breaks the podman-buildah treadmill:
```
# github.com/containers/podman/v4/cmd/podman/system                                                                                                             
cmd/podman/system/reset.go:100:14: undefined: parse.CleanCacheMount                                                                                             
make: *** [Makefile:345: bin/podman] Error 1
```
I figure there's a 99% chance you're aware of this and will fix it when it comes time to vendor buildah... but am posting because of that 1% chance.

**Comment by Luap99** [comment]
Yes as mentioned above, see the linked PR https://github.com/containers/podman/pull/19951

**Pull request merged**
