### PR TITLE
Close tarSource when finished using it

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Helps fix https://bugzilla.redhat.com/show_bug.cgi?id=1797599
@mtrmac @vrothberg PTAL

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind @QiWang19 PTAL

**Comment by TomSweeneyRedHat** [comment]
Change LGTM
However, Travis wasn't happy.  Looked like a network hiccup and I've restarted the tests.

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
I'm Done with this, Merging manually.

**Pull request merged**
