### PR TITLE
Cirrus: Re-order tasks for more parallelism

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Execute all tasks in three dependent, parallel groups

1. Meta + smoke + vendor + cross
2. Unit + int. + containerized-int. + conformance
3. Success

#### How to verify it

CI will pass in less than 55 minutes

#### Which issue(s) this PR fixes:

Ref: https://github.com/containers/buildah/pull/3699#issuecomment-1010075055

#### Special notes for your reviewer:

Depending on overall CI system load, queuing may reduce the number of parallel jobs actually run.  This aspect is almost entirely outside of our control/influence.

#### Does this PR introduce a user-facing change?

None

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
j/lgtm

**Comment by TomSweeneyRedHat** [comment]
oops
/lgtm

**Pull request merged**
