### PR TITLE
Bump c/image to 5.26.1, c/common to 0.55.1, Buildah to 1.31.0, and then to 1.32.0-dev

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Bump c/image and c/common in the first commit, then Buildah to 1.31.0 in the second, then Buildah to 1.32.0-dev in the third.  Once merged, I'll tag 1.31.0 and create a release branch for use with RHEL 8.9/9.3

[NO NEW TESTS NEEDED]

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rhatdan @vrothberg PTAL

**Comment by umohnani8** [comment]
LGTM
/hold cancel

**Comment by ashley-cui** [comment]
Pushing the green button as the bot seems to be stuck :cry:

**Pull request merged**
