### PR TITLE
update c/common

### PR DESCRIPTION
**Pull request by vrothberg**
Update containers common to the latest HEAD.  Some bug fixes in libimage
forced us to have a clearer separation between ordinary images and
manifest lists.  Hence, when looking up manifest lists without recursing
into any of their instances, we need to use `LookupManifestList()`.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@vrothberg looks like you have a vfs test issues, but not much info left behind.  In addition, you need a rebase.

**Comment by vrothberg** [comment]
> @vrothberg looks like you have a vfs test issues, but not much info left behind. 

That's because I restarted (test is rerunning). Must have been a flake.

**Comment by vrothberg** [comment]
@rhatdan, in case you take over the PR, make sure to remove the replace in go.mod.  You can `go get github.com/containers/common@master` since the other PR was merged.

**Comment by rhatdan** [comment]
@vrothberg Are you repushing this?

**Comment by vrothberg** [comment]
Yep, will push in a jiffie.

**Comment by vrothberg** [comment]
@nalind @TomSweeneyRedHat @rhatdan PTAL

Happy it's green.  That will unblock any PRs in Buildah that need a fresh c/common.

**Pull request closed without merging**
