### PR TITLE
Add and use a "copy" helper instead of podman load/save

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind failing-test 

#### What this PR does / why we need it:

Instead of using podman to cache images during integration tests, use a custom helper.  This will avoid unnecessary format conversions which I think are breaking gating tests in https://bugzilla.redhat.com/show_bug.cgi?id=1955166.

#### How to verify it

Tests should continue to pass.

#### Does this PR introduce a user-facing change?

```
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
Would `buildah pull FOO`, `buildah push FOO docker-archive:/tmp/foo` work?

**Comment by nalind** [comment]
> Would `buildah pull FOO`, `buildah push FOO docker-archive:/tmp/foo` work?

Temporarily, probably.  If, like with oci-archive, saving to a docker-archive ever forces the image to be converted to a particular format that it wasn't already in, it'll just trigger the same failure, so it's not a good long term option.

**Comment by vrothberg** [comment]
> > Would `buildah pull FOO`, `buildah push FOO docker-archive:/tmp/foo` work?
> 
> Temporarily, probably. If, like with oci-archive, saving to a docker-archive ever forces the image to be converted to a particular format that it wasn't already in, it'll just trigger the same failure, so it's not a good long term option.

In that case, `dir:` may be a good option.  I'm mostly wondering if we can recycle what Buildah can do.

**Comment by nalind** [comment]
> In that case, `dir:` may be a good option. I'm mostly wondering if we can recycle what Buildah can do.

`buildah pull`'s attempt to massage the path name in the `dir:` reference into an image name, rather than letting us specify it directly, would complicate that.

**Comment by vrothberg** [comment]
Thanks for your patience :) LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
/lgtm
/hold
until tests complete

**Comment by nalind** [comment]
Hmm, something's not right here.  Even though we load the cached images, we're still pulling them, so integration tests are taking a lot longer to run.

**Comment by nalind** [comment]
I think that the `dir:` round trip is causing the current version of `HasDifferentDigest()` to conclude that the restored-from-cache image, which doesn't include a copy of the original manifest list that `buildah pull` saves, doesn't match the remote reference that points to a manifest list.  As a result, we end up pulling images more often than we did before this patch, which is why the integration tests are timing out.  Opened https://github.com/containers/common/pull/554 to tighten up the logic in `HasDifferentDigest()`, which I think will fix that.

**Comment by nalind** [comment]
Hmm, the integration test are still taking too long (one's over 80 minutes and still going as I write this), so still not right.

**Comment by nalind** [comment]
Added a known `containers.conf`, based on the Fedora 34 version, so that the default list of capabilities in a system copy of the file doesn't affect tests.

**Comment by nalind** [comment]
Reverted overwriting containers.conf, though tests that implicitly used the system containers.conf need tweaking.

**Comment by nalind** [comment]
Added a "buildah rm -a" between a "buildah from" and a "buildah rmi" without a "-f" in the "from encrypted registry image" test.

**Comment by nalind** [comment]
Rebased.

**Review by vrothberg — COMMENTED** [review]
/lgtm

**Pull request merged**
