### PR TITLE
[release-1.26] bump dependencies

### PR DESCRIPTION
**Pull request by nalind**
Bump to the current versions of containers/storage, containers/image, containers/common, and dependencies that they pull in.
Also cherry-pick #4099, #4071, and the libseccomp.ActKill -> libseccomp.ActKillThread change from #4048 to make linters happy.
And add #4156 because tests break on my workstation without it.
Add the part of #4104 that updates a test to expect an error message that was changed in containers/storage.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
