### PR TITLE
[CI:DOCS] Simple README fix

### PR DESCRIPTION
**Pull request by MaximUltimatum**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design

/kind documentation

> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@MaximUltimatum Thanks for the PR, could you sign it?

git commit -a --amend -s
git push --force

LGTM
/approve

**Comment by MaximUltimatum** [comment]
rhatdan I got the signing set up but now my commit is showing up as verified. Would you still like me to try to sign it?

**Comment by rhatdan** [comment]
Squash your commits.

git rebase -i origin
git push --force

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM
Thanks @MaximUltimatum !

**Comment by MaximUltimatum** [comment]
@rhatdan Done. Anything else I can do?

**Comment by rhatdan** [comment]
Nope looks great Thanks.
/lgtm
/approve
/hold

**Pull request merged**
