### PR TITLE
Vendor in containers/storage v1.12.16

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg Restarted again.  Getting that error all the time.  @cevich any ideas?  Ubuntu keeps failing with locking conflicts on apt.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind @giuseppe @ashley-cui @QiWang19 PTAL

**Comment by nalind** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Comment by cevich** [comment]
> @cevich any ideas? Ubuntu keeps failing with locking conflicts on apt.

@rhatdan   Oh yes, thanks for reminding me.  I fixed this in the cache-images for libpod, but here and in buildah we're using the base-images.  I've got it on my TODO list to flip to using the cache-images here (and in buildah) which will eliminate this (very annoying) problem.

If that doesn't work out (for some reason), I'll have to apply the fix to the base-images.  This is possible, but much more difficult and not fully automate-able.

**Pull request closed without merging**
