### PR TITLE
Makefile: allow packagers to more easily add tags

### PR DESCRIPTION
**Pull request by vbatts**
With the `?=` operator, then `make binary TAGS=...` will clobber, but
this way `make binary BUILDTAGS=foo` will append.

Also, this matches the skopeo `BUILDTAGS`

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @vrothberg @nalind @giuseppe @umohnani8 PTAL

**Comment by TomSweeneyRedHat** [comment]
test issue appears to be a network flake.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan bot's ignoring me, can you see if you're hammer is bigger please?

**Comment by giuseppe** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
