### PR TITLE
Wire logger through to config

### PR DESCRIPTION
**Pull request by rhatdan**
Currently we are only wiring the logger into run_linux.go
Not into the Config section.

This PR is needed in order to update vendor in Podman.
https://github.com/containers/podman/pull/12375

[NO NEW TESTS NEEDED] Tests will be done in Podman.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@flouthoc @vrothberg @nalind @umohnani8 @saschagrunert @giuseppe @ashley-cui PTAL

**Comment by nalind** [comment]
Could use a rebase.  LGTM pending CI.

**Comment by TomSweeneyRedHat** [comment]
LGTM
once tests are happy and a rebase is done.

**Comment by nalind** [comment]
I don't really know how podman's using this, but this looks like it should be adding a `Logger` field to `ImportOptions` so that we can do the right thing for builders that were created by prior processes.

**Comment by flouthoc** [comment]
Do we need to instrument code further to use `Logger` in buildah code. But i guess that could be a different PR.

**Comment by flouthoc** [comment]
@rhatdan Where are we going to use this field in `podman`.

**Comment by rhatdan** [comment]
This returns logger messages from buildah like.
```
$ podman --remote  build --no-cache /tmp/test/
STEP 1/2: FROM fedora
STEP 2/2: SHELL [ "/bin/sh" ]
COMMIT
WARN[0000] SHELL is not supported for OCI image format, [/bin/sh] will be ignored. Must use `docker` format 
--> c8a66c46f2e
c8a66c46f2e29c557d22e98700b528a18adb69fef39d25540a90312619e7171c
podman (hosts) $ 
```
Without this change you see:
WARN[0000] SHELL is not supported for OCI image format, [/bin/sh] will be ignored. Must use `docker` format 
On the server side not on the client side.  And the user is left to wonder why it does not work.

**Pull request merged**
