### PR TITLE
Cirrus: use Ubuntu 22.04 LTS

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

To test with the latest ubuntu 22.04 lts release

#### How to verify it

cirrus tests should use 22.04 lts

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None
#### Does this PR introduce a user-facing change?

```release-note
None
```

depends on https://github.com/containers/automation_images/pull/134

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by lsm5** [comment]
wonder why the bot removed `do-not-merge/work-in-progress` the first time around.

**Comment by rhatdan** [comment]
/lgtm
@lsm5 Why do you want this held?

**Comment by lsm5** [comment]
@rhatdan IIUC, @cevich wants to make sure all test PRs are green before he merges https://github.com/containers/automation_images/pull/134 . Then the automation_images PR will merge first, followed by other PRs. @cevich correct me if I'm wrong.

**Review by cevich — APPROVED** [review]
LGTM

**Pull request merged**
