### PR TITLE
[ci:docs] buildah add/copy: spelling

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
/kind cleanup

#### Does this PR introduce a user-facing change?
None

### CODE REVIEW

**Comment by rhatdan** [comment]
I think you misspelled spelling? speilling?

**Comment by rhatdan** [comment]
Thanks @dilyanpalauzov for the PR
LGTM

**Comment by nalind** [comment]
There's a similar error with `--ignorefile` in `docs/buildah-bud.md`.  We can fix it here or in a follow-up.  LGTM either way.  Thanks!

**Pull request merged**
