### PR TITLE
inserts forgotten quotation mark

### PR DESCRIPTION
**Pull request by geonizeli**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Just insert quotation mark 😂 😂 
I think some people (not that I did) managed to copy and paste and received an error message.

#### How to verify it
Intense tool testing

#### Which issue(s) this PR fixes:
Fixes #None

#### Does this PR introduce a user-facing change?
Yes

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by rhatdan** [comment]
Thanks @geonizeli 
@TomSweeneyRedHat @nalind @giuseppe @vrothberg PTAL

**Comment by nalind** [comment]
Thanks!
/lgtm

**Pull request merged**
