### PR TITLE
Update to containers/storage v1.12.13

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@QiWang19 @TomSweeneyRedHat @vrothberg @nalind @giuseppe PTAL

**Comment by vrothberg** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
