### PR TITLE
Refactor: Use library shared idtools.ParseIDMap() instead of bundling it

### PR DESCRIPTION
**Pull request by isimluk**

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, add author to whitelist
LGTM

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat @vrothberg @giuseppe @pixdrift PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, but would like a head nod from @nalind before merging.

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
