### PR TITLE
WIP - Use SSL certificates in CI tests

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Add a test to use certificates when authenticating to a Docker Registry in Travis CI.

### CODE REVIEW

**Comment by rhatdan** [comment]
Not sure why this is a WIP, I would remove that and then we can work on it til you get the tests to pass.

**Comment by TomSweeneyRedHat** [comment]
I set it to a WIP as the tests weren't passing and it might take a bit to get them to go.  Mostly a sign for folks to not bother reviewing ATM.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Needs a rebase.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Are we done playing with this, Either close or fix the tests.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat What do you want to do?

**Comment by TomSweeneyRedHat** [comment]
I want to have a multitude of time so I can work on this.  Can we leave it as is?  If it really bugs you to have it hanging you can close it and I'll push it later if I ever get back to it.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat No problem.  About once I month I run through all old PR's to give them a kick in the shorts.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat needs a rebase.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat This PR Is old and haggard can I close it?

**Comment by rhatdan** [comment]
CLosing this since got no response.

**Pull request closed without merging**
