### PR TITLE
Update cirrus and version of golang

### PR DESCRIPTION
**Pull request by rhatdan**
#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM restarted flake

**Comment by rhatdan** [comment]
@nalind @cevich PTAL

**Comment by cevich** [comment]
X-ref: https://github.com/containers/buildah/pull/5007

The `.cirrus.yml` update should probably reference `latest`.  Nobody's likely to remember in the future, that needs updating also.

**Pull request merged**
