### PR TITLE
Bump 1.6-dev

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Bump upstream to 1.6-dev.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Green test buttons, @mheon, @rhatdan, @baude or @nalind if I could get a LGTM, I'd like to get this merged.

**Comment by TomSweeneyRedHat** [comment]
This resets the Buildah upstream version to a dev, we just cut 1.5 yesterday.  @vrothberg if you're around today, I'd happily steal a LGTM from you too.

**Comment by rhatdan** [comment]
LGTM
@rh-atomic-bot r+

**Comment by vrothberg** [comment]
> This resets the Buildah upstream version to a dev, we just cut 1.5 yesterday. @vrothberg if you're around today, I'd happily steal a LGTM from you too.

Thanks for the ping. A late LGTM :)

**Pull request closed without merging**
