### PR TITLE
chroot: fix handling of errno seccomp rules

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:

When converting seccomp rules from the runtime spec to the structure that we can feed to libseccomp, combine the prescribed errno value with the action when we're mapping the "return an errno" action from one to the other.

#### How to verify it

Currently, chroot isolation hits an error processing this seccomp rule:
```
                {
                        "names": [
                                "socket"
                        ],
                        "action": "SCMP_ACT_ERRNO",
                        "args": [
                                {
                                        "index": 0,
                                        "value": 16,
                                        "valueTwo": 0,
                                        "op": "SCMP_CMP_EQ"
                                },
                                {
                                        "index": 2,
                                        "value": 9,
                                        "valueTwo": 0,
                                        "op": "SCMP_CMP_EQ"
                                }
                        ],
                        "comment": "",
                        "includes": {},
                        "excludes": {
                                "caps": [
                                        "CAP_AUDIT_WRITE"
                                ]
                        },
                        "errnoRet": 22
                },
```
on Fedora 33.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Definitely going to need to backport this to older branches.

#### Does this PR introduce a user-facing change?

```
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@containers/buildah-maintainers PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
