### PR TITLE
Makefile: fix Makefile variable syntax

### LINKED ISSUE #1203: travis CI cannot build with seccomp
**Description** the installation script expects `seccomp` to be a Go package but cannot find it under the expected paths in travis CI, even after explicitly installing `seccomp` via `apt`.

**Steps to reproduce the issue:**
1. `git clone https://github.com/containers/buildah ${GOPATH}/src/github.com/containers/buildah`
1. `cd ${GOPATH}/src/github.com/containers/buildah`
1. `make runc all TAGS="apparmor seccomp"`
1. `sudo make install install.runc`

**Describe the results you received:** see [this error](https://travis-ci.org/operator-framework/operator-sdk/jobs/460529459#L866).

**Describe the results you expected:** no installation errors (a few weeks ago these same steps worked as expected).

**Output of `buildah version`:**

```
master (2c632d1a2de0192c3f18a2542ccb6f30a8719b1f)
```

### PR DESCRIPTION
**Pull request by estroz**
Currently `make runc all TAGS="apparmor seccomp"` fails due to bad variable expansion in the Makefile.

Closes #1203

### CODE REVIEW

**Comment by estroz** [comment]
`-tags "$(TAGS)"` passes on my machine but fails on travis, while `-tags $(TAGS)` passes on travis but fails on my machine. Might be a `make` version issue.

**Comment by estroz** [comment]
I did some cleanup and made variable delimiters consistent.

The issue with quotes in Makefiles is make interprets them verbatim, so expanding a quoted variable recursively within another set of quotes unquotes part of the expanded data. I made sure that only the final expansions in recursions contained quotes.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@vrothberg @umohnani8 @TomSweeneyRedHat @nalind @pixdrift @giuseppe PTAL

**Comment by rhatdan** [comment]
@estroz Sadly needs a rebase.

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
