### PR TITLE
CI: enable the gofumpt and whitespace linters

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Enables the gofumpt and whitespace linters and patches the things they warn about.  Preemptively patch some things a newer version of golangci-lint warns about from its "govet" linter.

#### How to verify it

No new breakage.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by nalind** [comment]
CI: enable the gofumpt and whitespace linters

**Comment by nalind** [comment]
/retitle CI: enable the gofumpt and whitespace linters

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
