### PR TITLE
mkcw: remove entrypoint binaries

### PR DESCRIPTION
**Pull request by flouthoc**
Remove generated entrypoint binaries needed to generated confidential container image and add them to `.gitignore`

#### What this PR does / why we need it:
Following binaries are always generated with build instruction, there shouldn't be any need to keep them in repo since source is already there also when `embed` directory ( in any case ) is empty on `make` it leaves un-tracked changes in the `git status` which looks unneeded.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by flouthoc — COMMENTED** [review]
~~Hmm binaries are always generted for me on local I wonder why is it needed on repo and CI ?~~

**Comment by nalind** [comment]
Still missing the "why" in the PR description.

**Comment by flouthoc** [comment]
@nalind Done.

**Comment by nalind** [comment]
LGTM, then.

**Comment by TomSweeneyRedHat** [comment]
LGTM
RPM tests are failing to build, I'm not sure if that's expected.

**Pull request merged**
