### PR TITLE
Cirrus: Remove multi-arch buildah image builds

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

These jobs have been failing since early August due to technical/scripting problems.  Disable/remove entirely since a fix is unlikely to be implemented anytime soon.

#### How to verify it

When specifying `[CI:DOCS]`, `[CI:BUILD]`, or no magic string in the PR title, CI will behave normally.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

If anybody ever cares, I gave up trying to debug the script problem in  https://github.com/containers/podman/pull/19720.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
Test`[CI:BUILD]` [behaves as expected.](https://cirrus-ci.com/task/5018465434599424)

**Comment by cevich** [comment]
Test `[CI:DOCS` [behaves as expected](https://cirrus-ci.com/build/4719328948387840).

**Comment by rhatdan** [comment]
Any update on this?

**Pull request merged**
