### PR TITLE
conformance tests: archive the context directory as 0:0

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind failing-test 

#### What this PR does / why we need it:

When uploading a context directory to dockerd, generate the archive ourselves so that we can force the ownerships in it to 0:0, which BuildKit seems to expect clients to do.

#### How to verify it

Run those conformance tests!

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve
/hold

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by flouthoc** [comment]
Rebased , squashed and merged

**Pull request merged**
