### PR TITLE
[CI:BUILD] Cirrus: Migrate multiarch build off github actions

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

The github actions workflow for this operation is complex and difficult
to maintain.  For several months now a replacement has been running well
in the podman repository.  It's scripts/components are centralized,
versioned, unit, and integration tested.  Add cirrus tasks to run the
build, and another task to allow test builds in a PR.

Note: This also adds support for a new magic CI string: `[CI:BUILD]`.
With this string in the PR title, automation will only do basic build
verification, and enable testing of the multi-arch build process.

#### How to verify it

[NO NEW TESTS NEEDED]

- [x] CI Will run normally without `[CI:BUILD]` magic string. The option to manually trigger multi-arch test build will not be visible.
- [x] CI Will only do build + verification with `[CI:BUILD]` magic string.
- [x] The option to manually trigger multi-arch test build will be visible and functional when triggered.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by cevich** [comment]
***note to me:*** This needs quay.io secrets generated and encoded.

**Comment by rhatdan** [comment]
LGTM

**Comment by cevich** [comment]
Status note: This PR needs to wait for a fix to the Dockerfiles (see https://github.com/containers/buildah/issues/4026)

**Comment by rhatdan** [comment]
@cevich @TomSweeneyRedHat What is going on with this?

**Comment by cevich** [comment]
> What is going on with this?

Tom's helping fix up the Dockerfiles (they don't/won't/can't build).  When that's done I'll rebase this and it should "Just work".

**Comment by cevich** [comment]
Force-push: Rebased onto #4050 to test if it builds now.

**Comment by cevich** [comment]
Force-push: Rebased on main.

**Comment by cevich** [comment]
Note to me: FIXME: the upstream image is throwing an error but the build is passing.

**Comment by cevich** [comment]
Force-push: Added fix for upstream image.

**Pull request merged**
