### PR TITLE
[CI:BUILD] Release 1.31 packit backport

### PR DESCRIPTION
**Pull request by lsm5**
Backporting https://github.com/containers/buildah/pull/4959 and https://github.com/containers/buildah/pull/4926

#### What type of PR is this?

/kind other

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by lsm5** [comment]
oops, looks like i added 1 extra commit. Fixing.

**Comment by lsm5** [comment]
also added eln target by backporting https://github.com/containers/buildah/pull/4964

**Comment by lsm5** [comment]
> also added eln target by backporting #4964

removed this one as it fails to build because of go-md2man issues.

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
@flouthoc @TomSweeneyRedHat good to merge.

**Pull request merged**
