### PR TITLE
imagebuildah: record image IDs and references more often

### PR DESCRIPTION
**Pull request by nalind**
Have `Commit()` and `Execute()` return the IDs and references for images that they create, to make things easier in a future commit when they won't always have names.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@vrothberg @TomSweeneyRedHat PTAL

**Comment by vrothberg** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request closed without merging**
