### PR TITLE
Correct small typo in comment

### PR DESCRIPTION
**Pull request by eschnett**
Signed-off-by: Erik Schnetter <schnetter@gmail.com>

#### What type of PR is this?

> /kind cleanup

#### What this PR does / why we need it:

Correct a comment in the code

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

None

```release-note

```

### CODE REVIEW

**Comment by flouthoc** [comment]
@eschnett Commit needs `[NO NEW TESTS NEEDED]`

**Comment by eschnett** [comment]
@flouthoc How do I add this?

**Comment by eschnett** [comment]
See https://github.com/containers/buildah/pull/4507.

**Comment by flouthoc** [comment]
@eschnett On your fork just do `git commit --amend -S -s` and it will open a text prompt then you can just add `[NO NEW TESTS NEEDED]` in the line above your `Signed-off-by` or in any new line. After that you can do `git push origin patch-1 --force` and push it.

**Comment by flouthoc** [comment]
> See #4507.

New PR LGTM

**Pull request closed without merging**
