### PR TITLE
Add BuilderIdentityAnnotation to identify buildah version used to bui…

### PR DESCRIPTION
**Pull request by rhatdan**
…ld image

We were adding this for buildah commit but not for buildah bud.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Looks like the change has upset the test apple cart @rhatdan

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind @vrothberg @ashley-cui @QiWang19 I reworked the label into the buildah library.
This should get this working properly for not changing images, and allow this to easily be vendored into OpenShift and Podman.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
