### PR TITLE
Bump fedora version from 28 to 30

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@cevich can you help us get off of papr all together?

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by cevich** [comment]
> can you help us get off of papr all together?

Yep, sure can, thanks for the reminder.

**Comment by rhatdan** [comment]
Forcing merge on this, Since the other errors are not related

**Comment by jlebon** [comment]
This doesn't work because `fedora/30/atomic` doesn't exist (though PAPR should've probably given a better error message here). The latest FAH release will be FAH29 (i.e. `fedora/29/atomic`).

>> can you help us get off of papr all together?
>
> Yep, sure can, thanks for the reminder.

:+1:

**Comment by TomSweeneyRedHat** [comment]
Just downgraded to Atomic 29 in https://github.com/containers/buildah/pull/1845.  Thanks for the heads up @jlebon

**Comment by cevich** [comment]
Ref: [Moving into Cirrus-CI](https://github.com/containers/buildah/pull/1848) will need to modify support for testing under Atomic.  We can take the same direction as for podman: Simply use a regular Fedora VM for the host, but run the tests in a container-image.  It's not a perfect solution, but there's almost-zero[*] hope of getting anything Atomic-like working under Google + Cirrus-Ci.

_[*]Extraordinary efforts are required to cope with both cloud and automation aspects we have no control over._

**Comment by rhatdan** [comment]
That is fine with me.  All that we do, is run the containers in containers test correct?  Make it match podman totally, makes sense.

**Comment by cevich** [comment]
yep yep, matchie matchie, same same.

**Pull request merged**
