### PR TITLE
Bump to v1.7

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
FYI @mheon @rhatdan @vbatts

**Comment by TomSweeneyRedHat** [comment]
oops, sorry @vbatts, meant to tag @vrothberg

**Comment by vrothberg** [comment]
Can you add another commit on top bumping the version to v1.8-dev? Just to be sure nothing comes in between by accident? Besides that, LGTM :)

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
@vrothberg we use a little script to spin this up and I've not had luck doing the two commits at once with this.  However, I will spin a new commit up shortly for dev and will be watching the PR's coming in with a soft hold in between.

**Comment by TomSweeneyRedHat** [comment]
Of all the PR's to fail with a registry flake.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan the bot's ignoring me, can you try to rekick please?

**Comment by vrothberg** [comment]
@TomSweeneyRedHat I restarted the jobs manually.

**Pull request closed without merging**
