### PR TITLE
chroot: setSeccomp add support for `ArchPARISC(64)` and `ArchRISCV64`

### PR DESCRIPTION
**Pull request by michalbiesek**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

None

```release-note
None
```

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM
Thanks @michalbiesek 
Could you repush to allow the tests to run.

**Comment by rhatdan** [comment]
@nalind @vrothberg @giuseppe @flouthoc @umohnani8 PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
