### PR TITLE
add hostname to /etc/hosts when running with host network

### LINKED ISSUE #4446: Buildah intermediate container(Id) is not resolvable
### Discussed in https://github.com/containers/buildah/discussions/4424

<div type='discussions-op-text'>

<sup>Originally posted by **SaurabhAhuja1983** November 18, 2022</sup>
### Docker  is assigning ipaddress to each intermediate container and containerId is resolvable. But buildah intermediate containerId is not resolvable...

```
I used following Dockerfile
FROM <REPO-TAKE-ANY-JAVA-IMAGE>/java_jdk_8:latest
COPY MyClass.java .

RUN echo "---" ; cat /etc/hosts ; echo "Hostname: $(hostname)" ; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass
```

```
cat MyClass.java

import java.net.InetAddress;
import java.net.UnknownHostException;

public class MyClass {
    public static void main(String args[]) {
        try {
            InetAddress ia = InetAddress.getLocalHost();
            String str = ia.getHostAddress();
            String HOSTNAME = InetAddress.getLocalHost().getHostName();
            System.out.println("hostname: " + HOSTNAME);
         } catch (final UnknownHostException e) {
            throw new IllegalStateException("cannot get host name", e);
         }
    }
}

```

```
See the following output
`buildah build --no-cache .
STEP 1/4: FROM <.............................>/java_jdk_8:latest
STEP 2/4: RUN which java
/usr/bin/java
STEP 3/4: COPY MyClass.java .
STEP 4/4: RUN echo "---" ; cat /etc/hosts ; echo "Hostname: $(hostname)" ; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass
---
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.20.203.214	agent-79ccf9cbc-cvstd
10.20.203.214	host.containers.internal
Hostname: 43d4f3951829
---
Exception in thread "main" java.lang.IllegalStateException: cannot get host name
	at MyClass.main(MyClass.java:12)
Caused by: java.net.UnknownHostException: 43d4f3951829: 43d4f3951829: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1418)
	at MyClass.main(MyClass.java:7)
Caused by: java.net.UnknownHostException: 43d4f3951829: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:866)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1288)
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:815)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1413)
	... 1 more
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN echo "---" ; cat /etc/hosts ; echo "Hostname: $(hostname)" ; echo "---"; javac MyClass.java ; /usr/bin/java -cp . MyClass": exit status 1
`
```

However the same code works fine with docker build as i could see the intermediate containerId to IP mapping in /etc/hosts.

Not sure if buildah intermediate container is not assigned an ipaddress but it's blocking our java projects from getting build as we are transitioning from docker to buildah for building images.</div>

### PR DESCRIPTION
**Pull request by Luap99**
#### What type of PR is this?

> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### What this PR does / why we need it:

Some tools depend on the hostname being present in /etc/hosts. I would
argue they are broken but its not like we can do anything about that.

This adds the hostname with the local host ip when the host network is
used. For private networking we already add the hostname.

We also now correctly force host networking in chroot mode, it was
silently ignored before thus causing extra confusion here.

#### Which issue(s) this PR fixes:

Fixes #4446

#### Does this PR introduce a user-facing change?

```release-note
buildah now adds the hostname to /etc/hosts when running with host networking.
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
A test blipped not being able to see `google.com`, I've restarted.

**Comment by Luap99** [comment]
Tests are failing because of the return error with chroot and --network change, looks like a lot of tests are testing functionality that never worked.
Given how many test fails and that commit https://github.com/containers/buildah/pull/4869/commits/d6b43c33addfb59367c0b50c2a9754af1c039573 can be considered a breaking change even when it never did what the users asked for I think it is just best to drop that commit and document it better. Basically every container in container workload that uses BUILDAH_ISOLATION=chroot would start blowing up when they have --network set and it is not set to host.
@TomSweeneyRedHat @flouthoc @nalind @rhatdan WDYT?

**Comment by TomSweeneyRedHat** [comment]
Backing out https://github.com/containers/buildah/commit/d6b43c33addfb59367c0b50c2a9754af1c039573 sounds like a good plan to me @Luap99

**Comment by SaurabhAhuja1983** [comment]
@Luap99 Thank You for working on it.
I really appreciate it.
 I see there are couple of things failing in main after this merge.
Once that's done, can you please release the new version of buildah, so that i can pick it up instead of using main.

**Comment by Luap99** [comment]
A new release will be cut in the next few weeks.

**Pull request merged**
