### PR TITLE
CI: use release-1.16 as the basis for validation tests

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

Compare new PRs on this branch against the release-1.16 branch, not against master, which continues ahead of us.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Better we change this bit sooner rather than later.

#### Does this PR introduce a user-facing change?

```
None
```

### CODE REVIEW

**Comment by nalind** [comment]
I don't think we need to wait for this before tagging 1.16.1.

**Comment by rhatdan** [comment]
LGTM

**Comment by nalind** [comment]
bors retry

**Pull request merged**
