### PR TITLE
[DO NOT MERGE] Default ostree stub

### PR DESCRIPTION
**Pull request by Silvanoc**
This PR is only to test the integration of the changes of [PR 587 of c/image](https://github.com/containers/image/pull/587).

### CODE REVIEW

**Comment by rhatdan** [comment]
@Silvanoc Whats going on with this?

**Comment by mtrmac** [comment]
@rhatdan The conversation has been going on in https://github.com/containers/image/pull/587 , let’s not fork it in here, please.

**Comment by rhatdan** [comment]
Thanks just want to get new data in each issue and PR.

**Comment by rhatdan** [comment]
Since no activity is happening over in containers/image since April, I am going to close this PR.  Reopen if you make progress.

**Pull request closed without merging**
