### PR TITLE
Move secrets code from libpod into buildah

### PR DESCRIPTION
**Pull request by rhatdan**
Starting to remove dependency on libpod from buildah.
secrets is used so that builds can access RHEL subscriptions
so this makes more sense to be in buildah then libpod.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
registry flake in CI, going to rekick.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat @giuseppe @vrothberg PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
@nalind @umohnani8 @giuseppe @vrothberg PTAL

**Comment by vrothberg** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
