### PR TITLE
Fix completions to print Names as well as IDs

### PR DESCRIPTION
**Pull request by rhatdan**
We want to complete based on container and image names as well
as IDs.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/containers/buildah/issues/1197

**Comment by TomSweeneyRedHat** [comment]
LGTM, assuming happy tests

**Comment by rhatdan** [comment]
@giuseppe @umohnani8 @nalind @pixdrift @boaz1337 @vrothberg PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by vrothberg** [comment]
Just tested it locally, LGTM as well :+1:

**Comment by vrothberg** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by vrothberg** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
