### PR TITLE
Set upperdir permissions based on source

### PR DESCRIPTION
**Pull request by rhatdan**
We are setting the permissions based on the dest dir rather
then the source dir.  Since we want this to work identical to a bind
mount, we need to have the permissions align.

There is also an issue where overlays on existing mounts is blowing up.

Begins to fix: https://github.com/containers/podman/issues/8801

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/buildah/issues/3051

@containers/podman-maintainers PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
