### PR TITLE
corrected man page section; .conf file to mention its man page

### PR DESCRIPTION
**Pull request by siretart**
Added as Debian distro patch.

Original-Author: Dmitry Smirnov <onlyjob@debian.org>
Signed-Off-By: Reinhard Tartler <siretart@tauware.de>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by siretart** [comment]
currently found at https://salsa.debian.org/go-team/packages/golang-github-containers-buildah/-/blob/debian/sid/debian/patches/man.patch

I'd prefer to not carry this as distro patch

**Comment by flouthoc** [comment]
@siretart Could you please sign the commit and add `[CI:DOCS]` or `[NO TESTS NEEDED]` in commit so CI understands that we don't need new tests for this patch and thanks for the patch !

**Comment by TomSweeneyRedHat** [comment]
LGTM
once the CI is happy @siretart TY for the patch, and @flouthoc is correct about the things that need to happen to make the CI happy.

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold

**Review by flouthoc — APPROVED** [review]

**Pull request merged**
