### PR TITLE
buildah copy and buildah add should support .containerignore

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/buildah/issues/3303

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat @umohnani8 @ashley-cui PTAL
@containers/podman-maintainers PTAL

**Review by ashley-cui — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
@vrothberg @giuseppe @saschagrunert PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM
A final head nod from @nalind would be good

**Comment by nalind** [comment]
Needs a rebase.  LGTM otherwise.

**Pull request merged**
