### PR TITLE
[v1.19] vendor containers/image@v5.10.5

### PR DESCRIPTION
**Pull request by vrothberg**
Fixes are needed to fix the remaining issues of #1589.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

@nalind @rhatdan @TomSweeneyRedHat PTAL

Do we need a BZ to get that into RHEL 8.4?  Fairly annoying bug (see https://github.com/containers/buildah/issues/1589).

### CODE REVIEW

**Comment by vrothberg** [comment]
Need the same for Podman @mheon @baude

**Comment by TomSweeneyRedHat** [comment]
We'll need a BZ, but I think we need another total version dance and may just do the one for that which would include this fix too.

**Comment by vrothberg** [comment]
> We'll need a BZ, but I think we need another total version dance and may just do the one for that which would include this fix too.

Perfect. Let me know in case the dance doesn't make it into 8.4. If not, I'll open a BZ.

**Pull request merged**
