### PR TITLE
Always close stdin pipe

### PR DESCRIPTION
**Pull request by jordemort**
This is a fix for https://github.com/containers/buildah/issues/1650.  Here is what I observed when running `echo "echo foo" | buildah run -- debian-working-container /bin/sh`:

On the first iteration of the loop, the other side of stdin is closed but our side has waiting data. Because it was closed, `pollFd.Revents&unix.POLLHUP` == `unix.POLLHUP`, so the file descriptor gets added to `removes`. However, because there is data waiting, `pollFd.Revents&unix.POLLIN` != `0`, so the first chance to trigger the logic that closes stdin is not taken. Because there is waiting data, then `n` > `0`, so the second chance to trigger the logic that closes stdin is also not taken. The data is relayed, but the file descriptor is in `removes`, so it gets removed from the polling set and there are no further chances to trigger closing stdin; thus, it hangs forever.

This removes the first chance to close stdin, responds to `n` == `0` by adding the descriptor to `removes`, and then triggers the "close stdin" logic while looping through `removes`.

cc @QiWang19 

Fixes: https://github.com/containers/buildah/issues/1650

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
But I want @nalind to review.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
LGTM, solves the issue that was reported.

Not related to this PR (buildah without the patch has the same behaviour), but a command like:

`seq 100000 | sudo ./buildah run fedora-working-container -- sh -c 'while read i; do echo $i; done'`

seems to hang

**Comment by TomSweeneyRedHat** [comment]
I've spun up #1664 to make sure we look at the issue @giuseppe spotted.

**Comment by giuseppe** [comment]
@TomSweeneyRedHat @rhatdan let's merge this PR and I will take a look at it

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@jordemort Can you rebase this PR and repush. Then we can get it merged.

Not sure what Homu is complaining about

**Comment by giuseppe** [comment]
@rh-atomic-bot retry

**Comment by giuseppe** [comment]
followup PR here: https://github.com/containers/buildah/pull/1668

**Pull request closed without merging**
