### PR TITLE
Remove mistaken code that got merged in other PR

### PR DESCRIPTION
**Pull request by rhatdan**
Miloslav had some good comments on a previous commit.

https://github.com/containers/buildah/pull/1411

These changes address his issues by removing them.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes issues found by @mtrmac in https://github.com/containers/buildah/pull/1411
@mtrmac PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, but would like a head nod from @mtrmac

**Comment by rhatdan** [comment]
OK @mtrmac Removed those also.

**Comment by mtrmac** [comment]
ACK, thanks.

**Comment by rhatdan** [comment]
@rh-atomic-bot r=mtrmac

**Pull request closed without merging**
