### PR TITLE
Update nix pin with `make nixpkgs`

### PR DESCRIPTION
**Pull request by hswong3i**
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

#### What type of PR is this?

> /kind cleanup
> /kind feature

#### What this PR does / why we need it:

Update nix pin with `make nixpkgs`

#### Does this PR introduce a user-facing change?

```release-note
Update nix pin with `make nixpkgs`
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bors retry

**Comment by TomSweeneyRedHat** [comment]
@saschagrunert thanks!  I'm not sure what's up with the CI, hopefully just bors being bors.

**Comment by TomSweeneyRedHat** [comment]
And the CI was just bors being bors, all green.

**Comment by saschagrunert** [comment]
> And the CI was just bors being bors, all green.

I re-triggered the tests, yeah it looks like a flake.

**Pull request merged**
