### PR TITLE
buildah allowed to use additional storage mounted from host

### PR DESCRIPTION
**Pull request by rhatdan**
These fixes will allow us to demonstrate multiple different ways of running the
container builds.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg @giuseppe @nalind PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, but could you change your commit message from "buidlah" to "buildahimage"?

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
@rhatdan two of the homu tests flaked, I've restarted.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan not sure what's up, but two of the homu tests are failing with 
```
$ git checkout -qf ce3a1202bd4254cc1be4cf387a9446dc94fa51e0
fatal: reference is not a tree: ce3a1202bd4254cc1be4cf387a9446dc94fa51e0
The command "git checkout -qf ce3a1202bd4254cc1be4cf387a9446dc94fa51e0" failed and exited with 128 during .
```

**Comment by vrothberg** [comment]
This looks like the one error caused by planetary positions letting homu's git go crazy. I think, @rhatdan needs to repush to change the commit ID :see_no_evil:

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, ready to merge and I think should have merged, going to try and kick the bot.

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
Still hanging around with everything good, but not merging @rhatdan

**Pull request closed without merging**
