### PR TITLE
Clarify docker.io default in push with docker-daemon

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Touches up docker-deamon verbiage per @tliron.  Thank you for the suggested verbiage and apologies for taking so long to get this done!

Fixes: #987

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mtrmac @nalind PTAL

**Comment by mtrmac** [comment]
👍 Thanks for taking care of this!

**Comment by vrothberg** [comment]
LGTM but I have some follow up questions.

- Do we need the same change for libpod?
- Does a similar behavior apply to other transports? If so, we could create a dedicate manpage for those transports (maybe in c/image?).

**Comment by mtrmac** [comment]
The `docker.io/library` normalization is common, but does not typically happen for `Buildah`/`Podman`; and `docker-daemon:` is special in that it has a particularly aggressive version of it, where it does not only _interpret_ short names with this semantics, but actively normalizes the name to explicitly include the hostname when contacting the daemon.

Yes, c/image should be maintaining a documentation of all its transports, and I can’t see it in there.  IIRC historically it lived in https://github.com/containers/skopeo/blob/master/docs/skopeo.1.md , and yes it should be split into a separate man page referenced from the others.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
