### PR TITLE
Include the FROM directive in Docker history Closes #2391 (second attempt)

### LINKED ISSUE #2391: Include the FROM directive in Docker history
Pulling this from https://bugzilla.redhat.com/show_bug.cgi?id=1649044 and @control-d

```
In the customer's own words:

---
"Please include the FROM directive in docker image information.  Nice to know what base image was used.  Docker history often lists <missing> on base image layers when pushed/pulled from a repository."
---



Just based on this I think what they would like to see, at a minimum, is:


# cat Dockerfile 
FROM fedora:latest
MAINTAINER http://fedoraproject.org/wiki/Cloud

RUN dnf -y update && dnf clean all
RUN dnf -y install nginx && dnf clean all
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN echo "nginx on Fedora" > /usr/share/nginx/html/index.html


# podman build -t test:bz1649044 .
STEP 1: FROM fedora:latest
Getting image source signatures
Skipping blob 01eb078129a0 (already present): 85.81 MiB / 85.81 MiB [=======] 0s
Copying config d09302f77cfc: 1.97 KiB / 1.97 KiB [==========================] 0s
Writing manifest to image destination
Storing signatures
STEP 2: MAINTAINER http://fedoraproject.org/wiki/Cloud
--> ff18bdd9b520b02fb3fc2ad26eb6ddc8e802b8496421902ea629801041aa8cb4
STEP 3: FROM ff18bdd9b520b02fb3fc2ad26eb6ddc8e802b8496421902ea629801041aa8cb4
STEP 4: RUN dnf -y update && dnf clean all
Fedora Modular 29 - x86_64                      388 kB/s | 1.5 MB     00:03    
{...]
--> e9fd39dc40f530626de0139e941faa5a7169f1722ac51dd135f5d6d6dcd50fe9
STEP 5: FROM e9fd39dc40f530626de0139e941faa5a7169f1722ac51dd135f5d6d6dcd50fe9
STEP 6: RUN dnf -y install nginx && dnf clean all
Fedora Modular 29 - x86_64                      2.4 MB/s | 1.5 MB     00:00    
[...]
--> b58279a3e1239bdfc870cf75cd3c4346346e40f84a999c7093b2fe948e2fdcd9
STEP 7: FROM b58279a3e1239bdfc870cf75cd3c4346346e40f84a999c7093b2fe948e2fdcd9
STEP 8: RUN echo "daemon off;" >> /etc/nginx/nginx.conf
--> 6823c19ecc131820aa2e6cbd43025b2038ac1c8f0fdef158481f3138e8816456
STEP 9: FROM 6823c19ecc131820aa2e6cbd43025b2038ac1c8f0fdef158481f3138e8816456
STEP 10: RUN echo "nginx on Fedora" > /usr/share/nginx/html/index.html
--> a75cd222709a12ba0e42d56f37988a3663c65c612a0d04e9f6ea8afdbd7f0327
STEP 11: COMMIT test:bz1649044


<start of hypothetical output>

# podman history test:bz1649044
ID             CREATED         CREATED BY                                      SIZE      COMMENT
a75cd222709a   3 minutes ago   /bin/sh -c echo "nginx on Fedora" > /usr/s...   252B      
6823c19ecc13   3 minutes ago   /bin/sh -c echo "daemon off;" >> /etc/ngin...   5.12kB    
b58279a3e123   3 minutes ago   /bin/sh -c dnf -y install nginx && dnf cle...   19.91MB   
e9fd39dc40f5   4 minutes ago   /bin/sh -c dnf -y update && dnf clean all       117MB     
ff18bdd9b520   8 minutes ago   /bin/sh -c #(nop) FROM fedora:latest            1.024kB   
d09302f77cfc   2 months ago    /bin/sh -c #(nop) CMD ["/bin/bash"]             1.024kB   
<missing>      2 months ago    /bin/sh -c #(nop) ADD file:508fcc9342ae817...   283MB     
<missing>      2 months ago    /bin/sh -c #(nop) ENV DISTTAG=fcontainer F...   283MB     
<missing>      4 months ago    /bin/sh -c #(nop) LABEL maintainer=Clement...   283MB     


OR

# podman history test:bz1649044
ID             CREATED          CREATED BY                                      SIZE      COMMENT
a75cd222709a   4 minutes ago    /bin/sh -c echo "nginx on Fedora" > /usr/s...   252B      
6823c19ecc13   4 minutes ago    /bin/sh -c echo "daemon off;" >> /etc/ngin...   5.12kB    
b58279a3e123   4 minutes ago    /bin/sh -c dnf -y install nginx && dnf cle...   19.91MB   
e9fd39dc40f5   6 minutes ago    /bin/sh -c dnf -y update && dnf clean all       117MB     
ff18bdd9b520   10 minutes ago   /bin/sh -c #(nop) MAINTAINER http://fedora...   1.024kB   FROM fedora:latest
d09302f77cfc   2 months ago     /bin/sh -c #(nop) CMD ["/bin/bash"]             1.024kB   
<missing>      2 months ago     /bin/sh -c #(nop) ADD file:508fcc9342ae817...   283MB     
<missing>      2 months ago     /bin/sh -c #(nop) ENV DISTTAG=fcontainer F...   283MB     
<missing>      4 months ago     /bin/sh -c #(nop) LABEL maintainer=Clement...   283MB     


It might even be better to record:

  FROM docker.io/library/fedora@sha256:787bce7f4d2dafd8c4923dd5c43fb2e4b8473b57ea52f6d12be9bb27bc8f1a85


As is, I don't think this fulfills the customer's request.  I apologize if the initial request was not clear enough.
```

### PR DESCRIPTION
**Pull request by dbgoytia**
Author: Diego <diego.canizales1995@gmail.com>
Date:   Fri Aug 7 12:11:31 2020 -0500

    Added reference to the parent image. Signed-off-by: Diego Goytia <diego.canizales1995@gmail.com>

Signed-off-by: Diego <diego.canizales1995@gmail.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

As requested by @TomSweeneyRedHat on #2391, taken from: https://bugzilla.redhat.com/show_bug.cgi?id=1649044

#### Which issue(s) this PR fixes:

#2391

#### Special notes for your reviewer:

This is my second pull request. First one was this, with the same changes, but squashed into a single commit: https://github.com/containers/buildah/pull/2514

Please let me know if it completes the requirement, otherwise I'll modify it! 

Thanks.

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
Almost there.

You need to fix up you commit. The first line of commit must be < 80 characters long.
Then you need an empty line.

After that you can put your signedby line.

git commit -a --amend -s
git push --force

**Comment by ironknight78** [comment]
Thank you @rhatdan ! There it goes again.

**Comment by ironknight78** [comment]
I think I gotta add the bats tests for this to come up ok. I'll work on it.

**Comment by rhatdan** [comment]
The bats tests indicate that they are now returning 3 lines rather then 1, check if this is expected after the change, if so then change the number expected to 3 and it should pass the test.

**Comment by rhatdan** [comment]
@ironknight78 Could you update this PR and add tests.  We want to get this into the buildah 1.16 release, which is coming up soon.

**Comment by ironknight78** [comment]
Of course Dan! I'm working on it. Honestly I'm a little bit stuck on the tests... I know that it is expected that the number of lines of the output to change, so that's why those tests are failing. The thing is that I think that some of the *.bats tests actually check the length of both the RootFS.DiffIDs and the History. Since i'm only appending the name of the parent file to the History, the number of RootFS.DiffIDs is not changing.. so I'm a little bit stuck :(

**Comment by TomSweeneyRedHat** [comment]
@rhatdan @nalind thoughts?
@rhatdan are we holding 1.16 for this?

**Comment by TomSweeneyRedHat** [comment]
@nalind will probably have a better suggestion, but I was able to get the test to pass with a bit of a gross change to the squash.bats test file at: https://github.com/containers/buildah/blob/master/tests/squash.bats#L14 by changing that from:

```
      expect_output "$expect"
```

to:
```
      if $output != "$expect" && $output != "$((expect + 2))" ; then
        expect_output "$expect"
      fi
```

**Comment by rhatdan** [comment]
I don't think we have to hold this for 1.6.
@ironknight78 are you still working on this?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan OK, I'll cut a 1.16 this afternoon then.

**Comment by ironknight78** [comment]
hey @rhatdan sorry I've been a little off, I was busy with some other stuff! :D I'll add the changes today and fix the commit!

**Comment by ironknight78** [comment]
I'm uncertain on how to fix this new issue:

It would seem that the manifest is not getting recognized over here:

On my local machine if I run 

```
diego@ossdevel:~$ podman manifest inspect docker.io/library/nginx
Error: error inspect manifest docker.io/library/nginx: loading manifest "docker.io/library/nginx": unable to load manifest list: unsupported format "application/vnd.docker.distribution.manifest.v2+json": manifest type not supported

```

And I'm thinking this is related to the manifest unkown issue I'm getting in the CI process:

```
[+0073s] + podman run -i --name in_podman_5436025625378816 -e CIRRUS_USER_PERMISSION=read -e CIRRUS_LAST_GREEN_BUILD_ID=4908807551713280 -e CIRRUS_DEFAULT_BRANCH=master -e CIRRUS_REPO_ID=5138144844840960 -e STORAGE_DRIVER=vfs -e CIRRUS_REPO_FULL_NAME=containers/buildah -e CIRRUS_REPO_OWNER=containers -e CIRRUS_USER_COLLABORATOR=false -e CIRRUS_SHELL=/bin/bash -e CIRRUS_HTTP_CACHE_HOST=127.0.0.1:12321 -e CIRRUS_PR=2520 -e CIRRUS_BASE_BRANCH=master -e CIRRUS_REPO_CLONE_HOST=github.com -e CIRRUS_CI=true -e CIRRUS_BUILD_ID=5436025625378816 -e CIRRUS_CLONE_DEPTH=50 -e CIRRUS_CHANGE_TITLE=Include the FROM directive in Docker history Closes #2391 (second attempt) -e BUILDAH_ISOLATION=chroot -e CIRRUS_BASE_SHA=0a8dc1f8064c573654f9cbd886a7596c5eac6f83 -e CIRRUS_REPO_NAME=buildah -e CIRRUS_REPO_CLONE_URL=https://github.com/containers/buildah.git -e CIRRUS_PR_DRAFT=false -e CIRRUS_TASK_ID=5436025625378816 -e CIRRUS_WORKING_DIR=/var/tmp/go/src/github.com/containers/buildah -e CIRRUS_CHANGE_IN_REPO=2422629d54b12cd9ac242860bbdfa01bbe9d635c -e CI=true -e CIRRUS_OS=linux -e CIRRUS_LAST_GREEN_CHANGE=fce9668d4f44d11a526be0361096e0c1e5bfd0e8 -e CIRRUS_TASK_NAME=cirrus-ci/required/in_podman -e CIRRUS_BRANCH=pull/2520 --net=host --net=container:registry --security-opt label=disable --security-opt seccomp=unconfined --cap-add=all -e GOPATH=/var/tmp/go -e GOSRC=/var/tmp/go/src/github.com/containers/buildah -e IN_PODMAN=false -e CONTAINER=podman -e CGROUP_MANAGER=cgroupfs -v /root/auth:/root/auth:ro -v /sys/fs/cgroup:/sys/fs/cgroup:rw -v /dev/fuse:/dev/fuse:rw -v /var/tmp/go/src/github.com/containers/buildah:/var/tmp/go/src/github.com/containers/buildah:z --workdir /var/tmp/go/src/github.com/containers/buildah quay.io/libpod/in_podman:master ./contrib/cirrus/setup.sh  # ./contrib/cirrus/lib.sh:247 in in_podman()
[+0073s] Trying to pull docker.io/library/the...
[+0074s]   denied: requested access to the resource is denied
[+0074s] Trying to pull registry.fedoraproject.org/the...
[+0074s]   manifest unknown: manifest unknown
[+0074s] Trying to pull quay.io/the...
[+0074s]   error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n"
[+0074s] Error: unable to pull the: 3 errors occurred:
[+0074s] 	* Error initializing source docker://the:latest: Error reading manifest latest in docker.io/library/the: errors:
[+0074s] denied: requested access to the resource is denied
[+0074s] unauthorized: authentication required
[+0074s] 
[+0074s] 	* Error initializing source docker://registry.fedoraproject.org/the:latest: Error reading manifest latest in registry.fedoraproject.org/the: manifest unknown: manifest unknown
[+0074s] 	* Error initializing source docker://quay.io/the:latest: Error reading manifest latest in quay.io/the: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL
manually please check your spelling and try again.</p>\n"
[+0074s] 
```


Any pointers into what could be going on here?

**Comment by ironknight78** [comment]
I did added the entry to the History through this line:


```
// Build history notes in the image configurations.
	appendHistory := func(history []v1.History) {
		currTime := time.Now()
		created := &currTime

		parent := i.parentImage
		logrus.Debugf("Adding parent image for the build = %s\n", parent)
		onews := v1.History{
			Created:    created,
			CreatedBy:  parent,
			Author:     "",
			Comment:    "FROM parent image:",
			EmptyLayer: true,
		}
		oimage.History = append(oimage.History, onews)

		dnews := docker.V2S2History{
			Created:    *created,
			CreatedBy:  parent,
			Author:     "",
			Comment:    "FROM parent image:",
			EmptyLayer: true,
		}
```

**Comment by rhatdan** [comment]
@nalind @QiWang19 PTAL

**Comment by nalind** [comment]
That error looks like it's coming from still attempting to pass the CIRRUS_CHANGE_TITLE variable we get in our environment into a container without quoting it, which we added a workaround for in #2553.  I think rebasing onto master will be enough here.

**Comment by ironknight78** [comment]
Ok let me retry that, thanks @nalind :+1:

**Comment by rhatdan** [comment]
@ironknight78 Any movement on this?

**Comment by rhatdan** [comment]
@ironknight78 Still out there?

**Comment by umohnani8** [comment]
Replaced by https://github.com/containers/buildah/pull/2996

**Pull request closed without merging**
