### PR TITLE
imagebuildah: stages shouldn't count as their base images

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
This is my first cherry-pick into a branch like this, so a good eyeball would be appreciated.
Picked from: #2321 and also #2306

When initializing a build stage, don't assume that the working container
will be useful for COPY instructions in subsequent stages that reference
the image that we're building FROM.

When locating previously-completed stages referenced in COPY
instructions in later stages, be consistent about requiring that those
stages need to have been completed before we can accept them as
alternate contexts for the sources being copied.

Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
Tests are not happy.

**Comment by TomSweeneyRedHat** [comment]
bors retry

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, I've tried rerunning the tests, no joy, can I ask you to give it a whirl?

**Comment by TomSweeneyRedHat** [comment]
I couldn't get the tests to restart, they were suffering from what looked like an Ubuntu network issue, so I took out the big hammer and repushed.  Fingers crossed.

**Comment by TomSweeneyRedHat** [comment]
Per @nalind's suggestion, I've added #2306 to this PR to try and get around the test issues.

**Comment by TomSweeneyRedHat** [comment]
@nalind, Ubuntu is not happy still, any thoughts on what's what?
```
+0000s] Retrying 5 times with a 30s delay, and 24s timeout for command: apt-get -qq --yes update
[+0155s] ##### (attempt #1)
[+0155s] E: The repository 'http://us-central1.gce.archive.ubuntu.com/ubuntu disco Release' no longer has a Release file.
[+0155s] E: The repository 'http://us-central1.gce.archive.ubuntu.com/ubuntu disco-updates Release' no longer has a Release file.
[+0155s] E: The repository 'http://us-central1.gce.archive.ubuntu.com/ubuntu disco-backports Release' does not have a Release file.
[+0155s] E: The repository 'http://security.ubuntu.com/ubuntu disco-security Release' no longer has a Release file.
```

**Comment by nalind** [comment]
disco isn't a long-term support release.  I'd be tempted to check if updating the images named in `.cirrus.yml` to match the values we use on the master branch would be enough, but I think we need @cevich's to help detangle this.

**Comment by rhatdan** [comment]
Well I am just going to merge.

**Comment by cevich** [comment]
@TomSweeneyRedHat @nalind sending e-mail...

**Pull request merged**
