### PR TITLE
revert #2246 FIPS mode change

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind @t8m @vrothberg @giuseppe PTAL

**Comment by rhatdan** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1804193

**Comment by vrothberg** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=1804193

Can you add that to the commit message and explain why need to revert? Having that in the git history is quite helpful.

**Comment by giuseppe** [comment]
LGTM

**Pull request merged**
