### PR TITLE
Cirrus+Bors: Simplify temp branch skipping

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
bors try

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
@cevich any idea why this is failing?

**Comment by rhatdan** [comment]
Forcing Merge.

**Comment by cevich** [comment]
> @cevich any idea why this is failing?

@rhatdan this one appears to be registry or container-image related:
https://cirrus-ci.com/task/4655859263340544?command=integration_test#L1344

Hopefully a temporary problem.  I would suggest using 'bors retry' instead of force-merging, though I also understand that sometimes progress **must** be made :smile:

**Pull request merged**
