### PR TITLE
buildah login and logout, do not need to enter user namespace

### PR DESCRIPTION
**Pull request by rhatdan**
Currently we are entering the user namespace to be able to login
and logout, since this is not required, we should not enter.

This also would allow these commands to execute within a docker
container by default.

Fixes: https://github.com/containers/buildah/issues/3037

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe do you know where this is covered in podman?  IE can we get podman login/logout to not happen within the user namespace?

**Comment by giuseppe** [comment]
> @giuseppe do you know where this is covered in podman? IE can we get podman login/logout to not happen within the user namespace?

we tag each command that needs the userns with `registry.UnshareNSRequired`

**Comment by rhatdan** [comment]
The only command I see this with is Mount?  Does this mean all other podman commands enter the user namespace?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan conformance tests aren't hip

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
