### PR TITLE
Fix parse_unsupported.go

### PR DESCRIPTION
**Pull request by rhatdan**
Also fix sort order for buildah.Options so they are easier to compare with
podman build.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @vrothberg @giuseppe @mheon @QiWang19 @nalind PTAL

**Comment by baude** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
