### PR TITLE
[CI:DOCS] Tutorial 04 - Include Debian/Ubuntu deps

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

Addresses: https://github.com/containers/buildah/issues/2922#issuecomment-1147088757

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Makes the tutorial easier to follow for Debian/Ubuntu users

#### How to verify it
Straightforward package installation

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?
```release-note
None
```

@nalind @TomSweeneyRedHat @rhatdan PTAL

@Alanthur let me know if the change works for you.

### CODE REVIEW

**Comment by lsm5** [comment]
If we aren't recommending building with btrfs and devmapper, should we suggest the `exclude_graphdriver_` tags?

**Comment by lsm5** [comment]
ack, this PR should be good to go in that case.

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
