### PR TITLE
Bump c/common to v0.47.4

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.

Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by nalind** [comment]
> As the title says.

*cough*  Going to want to tweak the commit log message, too.

**Comment by TomSweeneyRedHat** [comment]
Tweaked the message.  Gotta get my fingers off auto-pilot some day....

**Comment by TomSweeneyRedHat** [comment]
happy green test buttons

**Pull request merged**
