### PR TITLE
Fixing broken link for container-registries.conf

### PR DESCRIPTION
**Pull request by kris-nova**
The link to the container-registries.conf man page was a little off - this fixes it.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
Thanks @kris-nova !  We just moved that recently and it looks like we missed a reference.

Our Test CI system is a bit cranky and won't take a commit unless it's signed.  Could you please do `git commit --amend -s` and repush the pr?  Thanks!

**Comment by rhatdan** [comment]
LGTM
Thanks @kris-nova, just fix the commit message and we will merge.

**Comment by rhatdan** [comment]
@kris-nova Sorry to bother you, but could you update your PR so we can merge. 
git commit -a --ammend -s
git push --force

**Pull request closed without merging**
