### PR TITLE
make --format columnizing consistent with buildah images

### LINKED ISSUE #2016: Request: make `--format` columnizing consistent between `buildah containers` and `buildah images`
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

`buildah images --format 'template'` columnizes the output, while `buildah containers --format 'template'` uses the template as provided. This should be made consistent, right? If so, which is preferred?

**Steps to reproduce the issue:**

```bash
buildah from alpine:3
buildah from alpine:edge
buildah containers --format '{{.ContainerName}} :: {{.ImageName}}'
buildah images --format '{{.Name}} :: {{.Tag}} :: {{.Size}} :: {{.ID}}'
```

**Describe the results you received:**

```
alpine-working-container :: docker.io/library/alpine:3
alpine-working-container-1 :: docker.io/library/alpine:edge

docker.io/library/alpine   ::   edge   ::   5.86 MB   ::   60d63d8e1431
docker.io/library/alpine   ::   3      ::   5.82 MB   ::   965ea09ff2eb
```

**Describe the results you expected:**

Either

```
alpine-working-container :: docker.io/library/alpine:3
alpine-working-container-1 :: docker.io/library/alpine:edge

docker.io/library/alpine :: edge :: 5.86 MB :: 60d63d8e1431
docker.io/library/alpine :: 3 :: 5.82 MB :: 965ea09ff2eb
```

or 

```
alpine-working-container   :: docker.io/library/alpine:3
alpine-working-container-1 :: docker.io/library/alpine:edge

docker.io/library/alpine   ::   edge   ::   5.86 MB   ::   60d63d8e1431
docker.io/library/alpine   ::   3      ::   5.82 MB   ::   965ea09ff2eb
```

**Output of `pacman -Q buildah`:**

```
buildah 1.11.6-1
```

**Output of `buildah version`:**

```
Version:         1.11.6
Go Version:      go1.13.4
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.0.0
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```ini
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Output of `uname -a`:**

```
Linux Ingram 5.4.2-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 05 Dec 2019 12:30:04 +0000 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```ini
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
size = ""
override_kernel_check = "true"
mountopt = "nodev"
[storage.options.thinpool]
ostree_repo = ""
skip_mount_home = "false"
```

---

See relevant #437

### PR DESCRIPTION
**Pull request by boaz0**
closes #2016 

It feels great to contribute again after long time. :grinning:

### CODE REVIEW

**Comment by rhatdan** [comment]
Can you fix the man pages for buildah containers to match the new format?
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
LGTM
@rhatdan I took a quick look at the man pages and I think they're good as is.  Your call.

**Comment by rhatdan** [comment]
The man pages that use the --format flag are showing no headers, after this patch, they will show headers, I believe.

**Comment by boaz0** [comment]
Unless "table" is specified no header is shown:

```
$ ./buildah containers -a --format "{{.ContainerID}} :: {{.ContainerName}}"
44288fe4f8325bec974f79f3394d276504c5e5a174505acd167bfb7acc9485b4   ::   pg
8a05d1de192932eb75cb0e7c54e49532707eec5d493b4818785ce9dbddfc517a   ::   upbeat_tu
$ ./buildah containers -a --format "table {{.ContainerID}} :: {{.ContainerName}}"
CONTAINER ID                                                       ::   CONTAINER NAME
44288fe4f8325bec974f79f3394d276504c5e5a174505acd167bfb7acc9485b4   ::   pg
8a05d1de192932eb75cb0e7c54e49532707eec5d493b4818785ce9dbddfc517a   ::   upbeat_tu
```

**Comment by rhatdan** [comment]
Ok I was reading the man page incorrectly.

Tried patch out and it works well.

@rh-atomic-bot r+

**Pull request closed without merging**
