### PR TITLE
Add OCIRuntime to info

### LINKED ISSUE #1964: buildah info should probably indicate runtime
The `buildah info` command should probably include something like podman's `OCIRuntime`. Right now it's not easy to figure out whether it's runc or crun:
```
# buildah run --help|grep runtime
      --runtime path               path to an alternate OCI runtime (default "crun")
      --runtime-flag strings       add global flags for the container runtime
```

buildah-1.12.0-0.59.dev.git1967973.fc32.x86_64

### PR DESCRIPTION
**Pull request by m7mdkamal**
Closes #1964

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
@m7mdkamal Thanks for the PR!  The change LGTM, but I don't think you signed the commit and our CI will not take it until you do.  If you did not sign it, can you please `git commit --amend -s` and then repush it?

**Comment by rhatdan** [comment]
Thanks @m7mdkamal 
@rh-atomic-bot r+

**Comment by m7mdkamal** [comment]
@TomSweeneyRedHat yeah I signed it.

Thank you all for the support. This was my first open source contribution. And now how can find a `good second issue`? :smile:

**Comment by rhatdan** [comment]
We attempt to label them in libpod and buildah, great to have your help.

**Pull request closed without merging**
