### PR TITLE
Install new manpages to correct sections

### PR DESCRIPTION
**Pull request by siretart**
Signed-off-by: Reinhard Tartler <siretart@tauware.de>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by siretart** [comment]
currently found as distro patch at https://salsa.debian.org/go-team/packages/golang-github-containers-buildah/-/blob/debian/sid/debian/patches/build-source-manpages.patch

Without this patch, the package build breaks because dh_installmanpages fails to identify the directory where to install the manpage.

**Review by vrothberg — COMMENTED** [review]
Thanks, @siretart!

LGTM
@ashley-cui @TomSweeneyRedHat @nalind PTAL

**Comment by nalind** [comment]
LGTM.  Thanks!

**Review by ashley-cui — COMMENTED** [review]
/lgtm

thanks!

**Comment by flouthoc** [comment]
I think re-base is needed. @siretart Could you please rebase

**Comment by ashley-cui** [comment]
ah it needs an 
/approve

**Pull request merged**
