### PR TITLE
[v1.24 backport] bump to race-free `c/image` and `c/storage`

### PR DESCRIPTION
**Pull request by flouthoc**
Commits explained in bullet points.

* Bump c/storage to v1.38.3 released here: https://github.com/containers/storage/pull/1174
* Bump c/image to v5.19.2 released here: https://github.com/containers/image/pull/1503

New Names API in c/storage and c/image ensures that Name modification operations are race-free.

 * Adds a test to verify parallel/concurrent builds via podman don't race against each other.

For reference actual upstream PR: https://github.com/containers/image/pull/1480 and https://github.com/containers/storage/pull/1153

### CODE REVIEW

**Comment by jnovy** [comment]
Yes @flouthoc I will cherry-pick it from this branch once merged.

**Comment by TomSweeneyRedHat** [comment]
Tests failing, could you also bump c/common to 0.47.5?

**Comment by flouthoc** [comment]
@TomSweeneyRedHat bumped `c/common` to `0.47.5` as well however its unrelated to this PR. Tests should pass previous fails were flakes.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Partially addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2066519  RHEL 8.6 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2055487 

@rhatdan @nalind @vrothberg PTAL and if LGTY, then merge away.

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
