### PR TITLE
[release-1.22] Bump c/storage to v1.34.0

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Bump c/storage to v1.34.0 for the release-1.22 branch
Also bump go to 1.16 in Makefile and .cirrus.yml

[NO TESTS NEEDED]
[NO NEW TESTS NEEDED]

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Finally, time for :beers:

**Comment by TomSweeneyRedHat** [comment]
I'm running into a similar perm issue on two tests with this.  Were you seeing this with your testing @rhatdan?  This only has the c/storage bump in it plus the go version bumps, c/common still at v0.42.1

```
[+1386s] not ok 358 from --volume with U flag
[+1386s] # (from function `die' in file ./helpers.bash, line 228,
[+1386s] #  from function `run_buildah' in file ./helpers.bash, line 215,
[+1386s] #  in test file ./from.bats, line 306)
[+1386s] #   `run_buildah run "$ctr" stat -c "%u:%g" /mnt/testfile1.txt' failed
[+1386s] # /var/tmp/go/src/github.com/containers/buildah/tests /var/tmp/go/src/github.com/containers/buildah/tests
[+1386s] # readlink /proc/self/ns/user -> user:[4026531837]
[+1386s] # # [checking for: docker.io/library/alpine]
[+1386s] # # [restoring from cache: /var/tmp/buildah-image-cache.1 / docker.io/library/alpine]
[+1386s] # Getting image source signatures
[+1386s] # Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
[+1386s] # Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
[+1386s] # Writing manifest to image destination
[+1386s] # Storing signatures
[+1386s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah from --pull=false --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json --userns-uid-map 0:25677:26865 --userns-gid-map 0:7347:14792 --volume /var/tmp/buildah_tests.jjdy1d/testdata:/mnt:z,U alpine
[+1386s] # alpine-working-container
[+1386s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah run alpine-working-container stat -c %u:%g /mnt/testfile1.txt
[+1386s] # time="2021-08-12T23:26:03Z" level=warning msg="Error loading container config when searching for local runtime: lstat /run/containers/storage: permission denied"
[+1386s] # time="2021-08-12T23:26:03Z" level=error msg="failed to setup From and Bud flags: failed to get container config: lstat /run/containers/storage: permission denied"
[+1386s] # subprocess exited with status 1
[+1386s] # exit status 1
[+1386s] # [ rc=1 (** EXPECTED 0 **) ]
[+1386s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+1386s] # #| FAIL: exit code is 1; expected 0
[+1386s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+1386s] # /var/tmp/go/src/github.com/containers/buildah/tests
```
and

```
[+1478s] not ok 453 idmapping
[+1478s] # (from function `die' in file ./helpers.bash, line 228,
[+1478s] #  from function `run_buildah' in file ./helpers.bash, line 215,
[+1478s] #  in test file ./namespaces.bats, line 200)
[+1478s] #   `run_buildah run $RUNOPTS "$ctr" readlink /proc/self/ns/user' failed
[+1478s] # /var/tmp/go/src/github.com/containers/buildah/tests /var/tmp/go/src/github.com/containers/buildah/tests
[+1478s] # readlink /proc/self/ns/user -> user:[4026531837]
[+1478s] # Building container with --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json --quiet   alpine
[+1478s] # # [checking for: docker.io/library/alpine]
[+1478s] # # [restoring from cache: /var/tmp/buildah-image-cache.1 / docker.io/library/alpine]
[+1478s] # Getting image source signatures
[+1478s] # Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
[+1478s] # Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
[+1478s] # Writing manifest to image destination
[+1478s] # Storing signatures
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah from --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json --quiet alpine
[+1478s] # alpine-working-container
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah run --cni-config-dir=/var/tmp/buildah_tests.ykoosw/no-cni-configs alpine-working-container readlink /proc/self/ns/user
[+1478s] # user:[4026531837]
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah run --cni-config-dir=/var/tmp/buildah_tests.ykoosw/no-cni-configs alpine-working-container cat /proc/self/uid_map
[+1478s] #          0          0 4294967295
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah run --cni-config-dir=/var/tmp/buildah_tests.ykoosw/no-cni-configs alpine-working-container cat /proc/self/gid_map
[+1478s] #          0          0 4294967295
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah copy --chown 1:1 alpine-working-container /var/tmp/buildah_tests.ykoosw/somefile /
[+1478s] # 8a57c8266fd2dc6c394083be66f1ac629805d6c81b3bcbb87ced4e7932325545
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah run --cni-config-dir=/var/tmp/buildah_tests.ykoosw/no-cni-configs alpine-working-container stat -c %u:%g /somefile
[+1478s] # 1:1
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah copy alpine-working-container /var/tmp/buildah_tests.ykoosw/somedir /somedir
[+1478s] # ab402287154470a5ad7d14e4676ed64f48a8101e48a662653de3c3ed91d56073
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah run --cni-config-dir=/var/tmp/buildah_tests.ykoosw/no-cni-configs alpine-working-container stat -c %u:%g /somedir
[+1478s] # 0:0
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah run --cni-config-dir=/var/tmp/buildah_tests.ykoosw/no-cni-configs alpine-working-container stat -c %u:%g %a /somedir/someotherfile
[+1478s] # 0:0 4700
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah mount alpine-working-container
[+1478s] # /var/tmp/buildah_tests.ykoosw/root/vfs/dir/a77e0bbcb80e4a5ab659bb64ae8756d20d090049b28682e171475f4bc638e08e
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah commit alpine-working-container localhost/alpine-working:0
[+1478s] # Getting image source signatures
[+1478s] # Copying blob sha256:03901b4a2ea88eeaad62dbe59b072b28b6efa00491962b8741081c5df50c65e0
[+1478s] # Copying blob sha256:f6504a159697ca116956777c681b45ece4d05930ebdcf1a807f4e3fb18d79278
[+1478s] # Copying config sha256:79cf2ee6af816b02ef8865271eb26e4358bfe01d96a85d21b227c788de38221f
[+1478s] # Writing manifest to image destination
[+1478s] # Storing signatures
[+1478s] # 79cf2ee6af816b02ef8865271eb26e4358bfe01d96a85d21b227c788de38221f
[+1478s] # Building image with  
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah bud --cni-config-dir=/var/tmp/buildah_tests.ykoosw/no-cni-configs --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json -t localhost/alpine-bud:0 -f /var/tmp/go/src/github.com/containers/buildah/tests/./bud/namespaces/Containerfile /var/tmp/buildah_tests.ykoosw
[+1478s] # STEP 1/9: FROM alpine
[+1478s] # STEP 2/9: RUN echo "ReadlinkResult" && readlink /proc/self/ns/user
[+1478s] # ReadlinkResult
[+1478s] # user:[4026531837]
[+1478s] # STEP 3/9: RUN echo "UidMapResult" && cat /proc/self/uid_map
[+1478s] # UidMapResult
[+1478s] #          0          0 4294967295
[+1478s] # STEP 4/9: RUN echo "GidMapResult" && cat /proc/self/gid_map
[+1478s] # GidMapResult
[+1478s] #          0          0 4294967295
[+1478s] # STEP 5/9: COPY --chown=1:1 somefile /
[+1478s] # STEP 6/9: RUN echo "StatSomefileResult" && stat -c '%u:%g' /somefile
[+1478s] # StatSomefileResult
[+1478s] # 1:1
[+1478s] # STEP 7/9: COPY somedir /somedir
[+1478s] # STEP 8/9: RUN echo "StatSomedirResult" && stat -c '%u:%g' /somedir
[+1478s] # StatSomedirResult
[+1478s] # 0:0
[+1478s] # STEP 9/9: RUN echo "StatSomeotherfileResult" && stat -c '%u:%g %a' /somedir/someotherfile
[+1478s] # StatSomeotherfileResult
[+1478s] # 0:0 700
[+1478s] # COMMIT localhost/alpine-bud:0
[+1478s] # Getting image source signatures
[+1478s] # Copying blob sha256:03901b4a2ea88eeaad62dbe59b072b28b6efa00491962b8741081c5df50c65e0
[+1478s] # Copying blob sha256:1c779a700d1aa1c8d50673c58583245d297a8152cd5015e0b6f34ef69b08f376
[+1478s] # Copying config sha256:a4ac12d86a4ffbac23a4e15f74f0cdff5b1ed8c5080c4f199d894d63e09fc313
[+1478s] # Writing manifest to image destination
[+1478s] # Storing signatures
[+1478s] # --> a4ac12d86a4
[+1478s] # Successfully tagged localhost/alpine-bud:0
[+1478s] # a4ac12d86a4ffbac23a4e15f74f0cdff5b1ed8c5080c4f199d894d63e09fc313
[+1478s] # Building container with --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json --quiet --userns-uid-map=0:19632:25635 --userns-gid-map=0:5416:14143 alpine
[+1478s] # # [checking for: docker.io/library/alpine]
[+1478s] # # [restoring from cache: /var/tmp/buildah-image-cache.1 / docker.io/library/alpine]
[+1478s] # Getting image source signatures
[+1478s] # Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
[+1478s] # Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
[+1478s] # Writing manifest to image destination
[+1478s] # Storing signatures
[+1478s] # time="2021-08-12T23:27:34Z" level=error msg="A layer is mounted: layer is in use by a container"
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah from --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json --quiet --userns-uid-map=0:19632:25635 --userns-gid-map=0:5416:14143 alpine
[+1478s] # alpine-working-container-1
[+1478s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah run --cni-config-dir=/var/tmp/buildah_tests.ykoosw/no-cni-configs alpine-working-container-1 readlink /proc/self/ns/user
[+1478s] # time="2021-08-12T23:27:35Z" level=warning msg="Error loading container config when searching for local runtime: lstat /run/containers/storage: permission denied"
[+1478s] # time="2021-08-12T23:27:35Z" level=error msg="failed to setup From and Bud flags: failed to get container config: lstat /run/containers/storage: permission denied"
[+1478s] # subprocess exited with status 1
[+1478s] # exit status 1
[+1478s] # [ rc=1 (** EXPECTED 0 **) ]
[+1478s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+1478s] # #| FAIL: exit code is 1; expected 0
[+1478s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+1478s] # /var/tmp/go/src/github.com/containers/buildah/tests
```

**Comment by rhatdan** [comment]
@nalind @giuseppe This storage failure is difficult to understand.  Something in user namespace or networking changes causing these issues.

**Comment by giuseppe** [comment]
where is that failure happening?  CI seems to pass now?

**Comment by giuseppe** [comment]
nevermind my last comment, I think the issue is introduced with: https://github.com/containers/storage/commit/b4477c7a8b80ae0c2fe7aa63f20ef8b91d18cfa5

I think we should attempt the fallback path on any error, not only `ENOENT`.  When running in a user namespace, we fix the directory permissions later on (e.g. /var/lib/containers/storage is made `0711`).  The lstat fails when `/var/lib/containers/storage` is still using permissions `0700`.

Opened a PR to address it: https://github.com/containers/storage/pull/994
and https://github.com/containers/buildah/pull/3454 to verify it

**Pull request merged**
