### PR TITLE
Update containers/image to v2.0.0

### PR DESCRIPTION
**Pull request by mtrmac**
This adds v2 registries.conf format, including mirror support.

Supersedes #1526.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, I just wonder if we should bump c/image to 1.5.2 or perhaps 1.6 first and then merge here?

**Comment by mtrmac** [comment]
It would be 2.0 (breaking API changes).

A release does make sense, but I’d like to finish the documentation for that first.  In the meantime, the necessary code changes in Buildah can at least pass CI, if not be merged.

**Comment by rhatdan** [comment]
Adding [WIP] since we don't want to merge this until new version of containers/image has been cut.

**Comment by mtrmac** [comment]
Updated to v2.0.0. @rhatdan please remove WIP and merge if convenient.

**Comment by TomSweeneyRedHat** [comment]
Wowsa @mtrmac , thanks for the full service on this one!
@rhatdan PTAL.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
Just realized I never put an LGTM on this one, now I have.

**Pull request closed without merging**
