### PR TITLE
imagebuildah: make scratch config handling toggleable

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind api-change

#### What this PR does / why we need it:

The default configuration that `docker build` applies to images built using "scratch" has changed from classic builds to BuildKit.  Add a toggle for selecting which behavior to mimic.

#### How to verify it

Updated conformance test cases!

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by nalind** [comment]
_Pretty_ sure this will fix the conformance test failures in #5688.

**Comment by TomSweeneyRedHat** [comment]
LGTM
but the branch needs to be updated

**Comment by nalind** [comment]
Rebased.

**Pull request merged**
