### PR TITLE
Bump 1.8.4

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
No longer waiting.  Merging manually.

**Comment by TomSweeneyRedHat** [comment]
LGTM
and thanks!  Beat me to the punch this morn.

**Comment by rhatdan** [comment]
Had to do something on the long train ride home last night, and then finish it up this morning.

**Comment by vrothberg** [comment]
I join the game late but was having a look at the changelog and spotted two entries that on paper qualify for a minor version bump (i..e, to v1.**9**.0):

* Support --dns=none like podman
* add -t to podman run

**Pull request merged**
