### PR TITLE
update vendor containers/common v0.38.2

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
@vrothberg Manifest lists are very broken in containers-common.

**Comment by vrothberg** [comment]
> @vrothberg Manifest lists are very broken in containers-common.

Looking into it now.  The push "fix" from yesterday introduced that regression.

**Comment by vrothberg** [comment]
https://github.com/containers/common/pull/560

**Pull request closed without merging**
