### PR TITLE
Fix errors found in coverity scan

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg @giuseppe @TomSweeneyRedHat @nalind @QiWang19 @ashley-cui PTAL

**Comment by rhatdan** [comment]
Fixes: https://github.com/containers/buildah/issues/2541
@jasinner PTAL, BTW I had prepared this PR a week ago and never submitted it, your Issue reminded me of it,
Thanks.

**Comment by nalind** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
bors retry

**Pull request merged**
