### PR TITLE
Cirrus: Updates for master->main rename

### PR DESCRIPTION
**Pull request by cevich**
Ref: https://github.com/containers/buildah/issues/3227

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM
does this need to wait for #3335 or vice versa?  If not, ship it!

**Comment by cevich** [comment]
> does this need to wait for

Nope, and no conflict with it either....'cept now github is telling me I need to rebase (and run all the damn tests again) :cry:

**Comment by cevich** [comment]
Thanks Dan.

**Pull request merged**
