### PR TITLE
Fix excludes exception begining with / or ./

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/buildah/issues/3272

Testing: https://github.com/containers/storage/pull/958

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by rhatdan** [comment]
@saschagrunert @TomSweeneyRedHat @nalind @umohnani8 PTAL

**Review by saschagrunert — APPROVED** [review]
LGTM

**Pull request merged**
