### PR TITLE
Fix error check to work on Podman

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by edsantiago** [comment]
Assuming you've vendored this into podman and it works, LGTM

**Comment by rhatdan** [comment]
Podman prefixes `Error:` On the front of this message, which is causing the problem.

**Review by Luap99 — COMMENTED** [review]
LGTM, sorry @rhatdan

**Comment by nalind** [comment]
LGTM, then, but a longer description (the last argument passed to the assert function) might be preferable.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
