### PR TITLE
vendor in latest containers/common

### PR DESCRIPTION
**Pull request by rhatdan**
[ NO NEW TESTS NEEDED]

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg Something seems to be wrong in github.com/containers/common.

I am seeing this error repeatedly.

[+0873s] # time="2022-09-12T13:51:13-05:00" level=warning msg="Discarding libimage event which was not read within 2 seconds: &{1fad7e48fa1ef00da1d4da5187b1a4d3d44aad7d87864ff4ddf1e0259576cd7c localhost/scratch-image:latest 2022-09-12 13:51:11.73231185 -0500 CDT m=+0.064386174 7}"

**Comment by vrothberg** [comment]
https://github.com/containers/common/pull/1154

**Comment by flouthoc** [comment]
Needs: https://github.com/containers/common/pull/1157

**Comment by flouthoc** [comment]
@giuseppe does c/storage needs following patch ? I can open a PR but I want to confirm first. CI goes green if i apply this patch https://github.com/containers/buildah/pull/4252

```diff
diff --git a/pkg/chrootarchive/diff_unix.go b/pkg/chrootarchive/diff_unix.go
index 90f453913..aa9606374 100644
--- a/pkg/chrootarchive/diff_unix.go
+++ b/pkg/chrootarchive/diff_unix.go
@@ -109,7 +109,8 @@ func applyLayerHandler(dest string, layer io.Reader, options *archive.TarOptions
 
        cmd := reexec.Command("storage-applyLayer", dest)
        cmd.Stdin = layer
-       cmd.Env = append(os.Environ(), fmt.Sprintf("OPT=%s", data))
+       env := append(os.Environ(), fmt.Sprintf("OPT=%s", data))
+       cmd.Env = append(cmd.Env, env...)
 
        outBuf, errBuf := new(bytes.Buffer), new(bytes.Buffer)
        cmd.Stdout, cmd.Stderr = outBuf, errBuf
```

**Comment by flouthoc** [comment]
> @giuseppe does c/storage needs following patch ? I can open a PR but I want to confirm first. CI goes green if i apply this patch See: #4252
> 
> ```diff
> diff --git a/pkg/chrootarchive/diff_unix.go b/pkg/chrootarchive/diff_unix.go
> index 90f453913..aa9606374 100644
> --- a/pkg/chrootarchive/diff_unix.go
> +++ b/pkg/chrootarchive/diff_unix.go
> @@ -109,7 +109,8 @@ func applyLayerHandler(dest string, layer io.Reader, options *archive.TarOptions
>  
>         cmd := reexec.Command("storage-applyLayer", dest)
>         cmd.Stdin = layer
> -       cmd.Env = append(os.Environ(), fmt.Sprintf("OPT=%s", data))
> +       env := append(os.Environ(), fmt.Sprintf("OPT=%s", data))
> +       cmd.Env = append(cmd.Env, env...)
>  
>         outBuf, errBuf := new(bytes.Buffer), new(bytes.Buffer)
>         cmd.Stdout, cmd.Stderr = outBuf, errBuf
> ```

Not yet fully sure about this, but trying this patch again in the same PR

**Comment by rhatdan** [comment]
@giuseppe This is still failing with the updated containers/common?

**Comment by rhatdan** [comment]
@flouthoc What difference to you see with that patch?

Is cmd.Env prepopulated and we are overwriting that?

**Comment by flouthoc** [comment]
> @flouthoc What difference to you see with that patch?
> 
> Is cmd.Env prepopulated and we are overwriting that?

My patch does not helps, earlier it passed because I removed other tests and only kept the relevant tests just like its done in this PR https://github.com/containers/buildah/pull/4253, as soon as i added all the tests, the `idmapping` test started to fail again. So I don't think my patch is helpful here.

**Comment by flouthoc** [comment]
Fixed by @giuseppe here: https://github.com/containers/common/pull/1161 , so this PR needs rebase and patch https://github.com/containers/common/pull/1161 from `c/common`

**Comment by giuseppe** [comment]
alternative PR: https://github.com/containers/buildah/pull/4269

**Comment by rhatdan** [comment]
Which ever one passes first.

**Comment by flouthoc** [comment]
Changing PR title since this is only vendoring `c/common` now , alt was merged here: https://github.com/containers/buildah/pull/4269

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
I think this Needs a rebase

**Pull request merged**
