### PR TITLE
Change references from master to main

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by vrothberg** [comment]
Please remove the `CI:DOCS` and repush.  There is a number of tests that `ADD` content from master which I am afraid will break once master is gone.

**Comment by cevich** [comment]
> and repush

Sadly @vrothberg is right, a re-push is necessary after removing [CI:DOCS] :cry:

**Review by TomSweeneyRedHat — COMMENTED** [review]
LGTM
once this merges, we'll have a number of links in buildah.io that will need tending too.

**Pull request merged**
