### PR TITLE
[release-1.26]: bump to `v1.26.3`

### PR DESCRIPTION
**Pull request by flouthoc**
Bump to version `v1.26.3`

[NO NEW TESTS NEEDED]
[NO TESTS NEEDED]

### CODE REVIEW

**Comment by nalind** [comment]
LGTM

**Comment by flouthoc** [comment]
@TomSweeneyRedHat @rhatdan PTAL

**Comment by flouthoc** [comment]
@TomSweeneyRedHat requested backports already merged here expect first one https://github.com/containers/buildah/pull/4157

**Comment by TomSweeneyRedHat** [comment]
LGTM
and all the versions line up, thanks @flouthoc

**Comment by flouthoc** [comment]
Released tag here: https://github.com/containers/buildah/releases/tag/v1.26.3

**Pull request merged**
