### PR TITLE
Sort CLI flags of buildah bud

### PR DESCRIPTION
**Pull request by QiWang19**
This can fix the #1086 
Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Addresses #1086.  @QiWang19 if you haven't yet, can you try to assign that to yourself too?  We may need Dan to update something.

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by QiWang19** [comment]
@TomSweeneyRedHat Can't assign, I'll comment in that issue.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
