### PR TITLE
buildah: honor rootless config file

### PR DESCRIPTION
**Pull request by giuseppe**
and support for fuse-overlayfs by creating a new mount namespace when unsharing

Continuation of: https://github.com/containers/buildah/pull/1123

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.  I see now @giuseppe , we want to close #1123 and go forward with this one.  I'm thinking the tests issues are not related to this patch.

**Comment by giuseppe** [comment]
@TomSweeneyRedHat I'd like a ACK from @rhatdan first and what he thinks.

With this PR it will be possible to use fuse-overlayfs similarly to how it is done with podman

**Comment by rhatdan** [comment]
LGTM
@rh-atomic-bot r+

**Comment by giuseppe** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
