### PR TITLE
Vendor in latest containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes the use of additional stores, use of devices based on link paths,
properly checks the permissions on /run/usr/UID directory.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg ptal

**Comment by rhatdan** [comment]
@giuseppe @nalind PTAL

**Comment by vrothberg** [comment]
LGTM, thanks Dan!

**Comment by vrothberg** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
