### PR TITLE
Update for https://github.com/containers/image/pull/1299 + update tests

### PR DESCRIPTION
**Pull request by mtrmac**
#### What type of PR is this?

> /kind feature

#### What this PR does / why we need it:

Update c/image from a WIP https://github.com/containers/image/pull/1299:
- to eventually benefit from the better error messages
- for now, to exercise that PR to find issues, if any
- for now, to see if any Buildah tests need adjusting.

#### How to verify it

Existing tests

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac This PR needs to be rebased or closed.

**Comment by mtrmac** [comment]
@rhatdan This contains test updates that we will need to apply to Buildah soon after the c/image PR merges.

The next step is to review and merge https://github.com/containers/image/pull/1299 . Short-term, waiting after the 4.3 branching and/or release might be better, to decrease risk of last-minute instability.

**Comment by mtrmac** [comment]
c/image has now been updated, and vendoring that will break Buildah tests.

So, please review/merge this PR, so that Buildah tests match c/image and future vendor dances don’t stumble on the test failures.

**Pull request merged**
