### PR TITLE
 Avoid including linux/memfd.h

### PR DESCRIPTION
**Pull request by rhatdan**
Replaces https://github.com/containers/buildah/pull/1602

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by rhatdan** [comment]
Closes: https://github.com/containers/buildah/issues/1600

**Comment by rhatdan** [comment]
@epruesse  PTAL
@giuseppe @nalind @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
Would like to let @giuseppe take a peak, if he doesn't by tomorrow morning, I'll merge then.

**Comment by epruesse** [comment]
The conda-forge packages are built within the `condaforge/linux-anvil` container (https://github.com/conda-forge/docker-images/blob/master/linux-anvil/Dockerfile), which is based off centos:6 to have minimal libc requirements and is lacking the memfd.h file. I do believe that the patch will fix this.

**Comment by rhatdan** [comment]
@epruesse How about I add:

```
/* Open Source projects like conda-forge, want to package podman and are based 
   off of centos:6, Conda-force has minimal libc requirements and is lacking 
   the memfd.h file, so we use mmam.h
*/
```

**Comment by epruesse** [comment]
Thanks @rhatdan  - it just sounded like something where someone down the road would think "What's this, why aren't we just including the right header file" and remove the code.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
