### PR TITLE
Cirrus: Bump up to Fedora 35 & Ubuntu 21.10

### PR DESCRIPTION
**Pull request by cevich**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

The Fedora 35 cloud images have switched to UEFI boot with a GPT
partition. Formerly, all Fedora images included support for runtime
re-partitioning. However, the requirement to test alternate storage
has since been dropped/removed.  Rather than maintain a disused
feature, and supporting scripts, these Fedora VM images have reverted
to the default: Automatically resize to 100% on boot.

#### How to verify it

CI testing will pass

#### Which issue(s) this PR fixes:

`None`

#### Special notes for your reviewer:

Please wait for https://github.com/containers/podman/pull/11795 to merge first.

#### Does this PR introduce a user-facing change?

`None`

### CODE REVIEW

**Comment by cevich** [comment]
@nalind that seems to have done the trick.

**Comment by rhatdan** [comment]
@cevich is this still a draft or ready to merge?

**Comment by cevich** [comment]
> is this still a draft or ready to merge?

Thanks for checking, yes it's still a draft.  It's using a F35beta image whereas it's actually been released now.  I'll update this PR again once the podman one is ready to go, so we can keep common image-IDs across the projects (helpful for debugging).

**Comment by cevich** [comment]
@nalind were you going to make a separate PR for your 'chroot-unit-test-seccomp' branch, or should I just include it here?

**Comment by nalind** [comment]
> @nalind were you going to make a separate PR for your 'chroot-unit-test-seccomp' branch, or should I just include it here?

Feel free to pull it in if it makes things simpler.

**Comment by cevich** [comment]
> Feel free to pull it in if it makes things simpler.

I think it does, just wasn't sure if you wanted to have scrutiny beyond this PR.  Seems like the fix works, so :man_shrugging: we can run with it.

For this PR in general, the status is same as I said a few days ago: I'd like to wait until we get green-lights on the podman-side simply out of convenience to share the same image.  My plan is to open similar PRs for all the other container repos. at that time as well.

**Comment by rhatdan** [comment]
Is this still a WIP?

**Comment by cevich** [comment]
> Is this still a WIP?

Only barely.  I can un-WIP it if it's needed right now...but I think having the podman tests actually pass adds a bit more confidence the images are safe to use elsewhere.  I'm not going to press that as a hard requirement though.

**Comment by cevich** [comment]
Rebased / force-pushed / un-WIP/draft the PR.  Assuming it passes, please merge if there is a need and/or https://github.com/containers/podman/pull/11795 gets merged - whichever happens first :smile:

**Pull request merged**
