### PR TITLE
Fix cirrus compilation issues

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Per @cevich, moving the .cirrus.yaml and the contrib/cirrus
directory here to the release-v1.14 branch in hopes of fixing
compilation issues as seen in #2401

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@cevich, PTAL

**Comment by TomSweeneyRedHat** [comment]
@cevich, we're not hitting the same error anymore, but now it looks like podman isn't able to start the registry down near the bottom of contrib/cirrus/lib.sh for some reasone and I'm not quickly spotting the hang up.

**Comment by TomSweeneyRedHat** [comment]
@cevich, @vrothberg spotted issues with the registry2 image here: https://github.com/containers/libpod/pull/6676.  Perhaps that's what's biting me here?

**Comment by TomSweeneyRedHat** [comment]
I've bumped the registry to `registry:2.6` in hopes that will cure the issue with not being able to talk to the registry.

**Comment by vrothberg** [comment]
Almost there:
> [+0100s] + ./bin/buildah info  # ./contrib/cirrus/build.sh:25 in main()
[+0100s] ./contrib/cirrus/lib.sh: line 178: ./bin/buildah: Too many levels of symbolic links

**Comment by cevich** [comment]
@TomSweeneyRedHat Let's try this as the next step:

[patch.txt](https://github.com/containers/buildah/files/4832060/patch.txt)

**Comment by cevich** [comment]
FWIW: After applying that patch, you should be able to use `hack/get_ci_vm.sh` to debug this first-hand.

**Comment by TomSweeneyRedHat** [comment]
Patch applied (thx @cevich), fingers firmly crossed.

**Comment by TomSweeneyRedHat** [comment]
@cevich closer.  

```
[+0168s] Storing signatures
[+0170s] time="2020-06-25T18:18:12-04:00" level=error msg="oci runtime \"runc\" does not support CGroups V2: use system migrate to mitigate"
[+0170s] Error: this version of runc doesn't work on cgroups v2: OCI runtime error
[18:18:12] END - [+0170s] total duration since START
```
I'm going to try to force the registry to run crun rather than runc, I'm not sure if that will work with this image though.

**Comment by cevich** [comment]
> I'm going to try to force the registry to run crun rather than runc, I'm not sure if that will work with this image though.

It's worth checking how `master` is setup.  IIRC, the F31 image uses cgroupsv1 and F32 uses cgroups v2 but I could be mistaken.

**Comment by cevich** [comment]
Okay, reproduced and confirmed.  All VMs use cgroupsv2 and the setup from master we brought here, assume crun will be used.  I sent an e-mail to you and Dan asking how we should proceed.

**Comment by rhatdan** [comment]
Can we install both crun and runc on the VMs?

**Comment by cevich** [comment]
@rhatdan yes, in fact both packages are present on the system (in a directory) but only one is installed.  So installing/removing one|other|both does **not** require refreshing the bloody repo. metadata for 5 minutes :confounded: It's just an RPM install:

```diff
diff --git a/contrib/cirrus/lib.sh b/contrib/cirrus/lib.sh
index a3878e16..d3100c3b 100755
--- a/contrib/cirrus/lib.sh
+++ b/contrib/cirrus/lib.sh
@@ -85,6 +85,8 @@ SHORT_DNFY="timeout_attempt_delay_command 60s 2 5s dnf -y"
 # Longer timeout for long-running packaging command
 LONG_APTGET="timeout_attempt_delay_command 300s 5 30s $APTGET"
 LONG_DNFY="timeout_attempt_delay_command 300s 3 60s dnf -y"
+# Downloaded, but not installed packages (from VM image build process)
+PACKAGE_DOWNLOAD_DIR=/var/cache/download
 
 # Allow easy substitution for debugging if needed
 CONTAINER_RUNTIME="showrun ${CONTAINER_RUNTIME:-podman}"
diff --git a/contrib/cirrus/setup.sh b/contrib/cirrus/setup.sh
index 7a8f6dc2..6c098416 100755
--- a/contrib/cirrus/setup.sh
+++ b/contrib/cirrus/setup.sh
@@ -31,7 +31,9 @@ case "$OS_RELEASE_ID" in
 
         warn "Hard-coding podman to use runc"
         sed -i -r -e 's/^runtime = "crun"/runtime = "runc"/' /usr/share/containers/libpod.conf
-        dnf install -y /var/cache/download/runc*.rpm
+        cd "$PACKAGE_DOWNLOAD_DIR"
+        dnf install -y ./runc*.rpm ./crun*.rpm
+        cd -
 
         # Executing tests in a container requires SELinux boolean set on the host
         if [[ "$IN_PODMAN" == "true" ]]
```

**Comment by cevich** [comment]
@TomSweeneyRedHat where are we at on this one...I have an e-mail from Dan giving a :+1: to backport.  I'm not sure what that involves, but it was about a month ago he did it on master.

**Comment by TomSweeneyRedHat** [comment]
@cevich just back from 10+ days away from the keyboard.  We definitely want to get this branch happy again.  If you want to run with it, feel free, otherwise it will probably take me a few days to clear the rubble in the inbox.

**Comment by cevich** [comment]
No worries, I'm just getting back from PTO as well, have my own pile of emails to delete :grin:

**Comment by rhatdan** [comment]
@cevich said to close this.

**Pull request closed without merging**
