### PR TITLE
V1.4 Release Announcement

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Add the v1.4 Release Announcement.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
Going to force merge.  Not sure whats up with Travis, but it is not testing this PR>

**Pull request merged**
