### PR TITLE
Add base image name to comment

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Add the name of the base image being used by the build
in the comments of the first layer created.

#### Which issue(s) this PR fixes:

Fixes https://github.com/containers/buildah/issues/2391

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by umohnani8** [comment]
Example output
```
Containerfile:
FROM ubi8
ENV name=$TEST
RUN echo "hello"
RUN echo "bye"


➜  buildah git:(history) ✗ podman history test                                  
ID            CREATED        CREATED BY                        SIZE     COMMENT
0c1470c148c6  5 seconds ago  /bin/sh -c echo "bye"             1.02 kB  
c8a0151d9369  6 seconds ago  /bin/sh -c echo "hello"           2.05 kB  
3269c37eae33  7 seconds ago  /bin/sh -c #(nop) ENV name=$TEST  0 B      FROM registry.access.redhat.com/ubi8:latest
<missing>     7 weeks ago                                      20.5 kB  
<missing>     7 weeks ago                                      208 MB   Imported from -
```

**Comment by rhatdan** [comment]
Needs a test.  

@TomSweeneyRedHat @nalind PTAL

**Comment by TomSweeneyRedHat** [comment]
and all kinds of test unhappiness.

**Comment by umohnani8** [comment]
Added test to check that the comment has the `FROM image name`

**Comment by umohnani8** [comment]
@rhatdan @TomSweeneyRedHat tests are passing now. The ubuntu one looks like a flake, how do you re-run a test?

**Comment by rhatdan** [comment]
/approve
LGTM

**Review by ashley-cui — COMMENTED** [review]
/lgtm

**Comment by ashley-cui** [comment]
Oops, clicked a button that I shouldn't have... agh, sorry, can you remove that commit?

**Comment by TomSweeneyRedHat** [comment]
F33 test is barfing still....

**Pull request merged**
