### PR TITLE
Remove containerstorage workaround, move buildahimage under contrib

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Moves the buildahimage directory from the top-level to under contrib.
Also removes this link workaround for containers storage:

```
RUN mkdir /root/.config && ln -s /etc/containers /root/.config/containers
```

Things seem to work without it, however that directory is not created now and
I'm not 100% sure that's expected.

@rhatdan if any of this doesn't jive, please holler.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@vbatts heads up.  If this goes through the buildahimage Dockerfiles will be moving down a directory.

**Comment by vbatts** [comment]
oooookie dokie. Thanks for the heads up. It took me a couple days to catch when y'all renamed `git` to `upstream` :-D

**Comment by TomSweeneyRedHat** [comment]
Replaced by #1605

**Comment by TomSweeneyRedHat** [comment]
Ugh, wrong window for that LGTM.

**Pull request closed without merging**
