### PR TITLE
Update docker/libnetwork to get rid of outdated sctp package

### PR DESCRIPTION
**Pull request by saschagrunert**
After the merge of https://github.com/docker/libnetwork/pull/2403, we're now able to update the outdated SCTP package as well.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, test failures are almost certainly not related to this change.
@nalind or @vrotherberg, I'd like a head nod from one of you too.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
