### PR TITLE
fix troubleshooting redirect instructions

### PR DESCRIPTION
**Pull request by johrstrom**
The instructions in the troubleshooting.md aren't right and don't work. The container variable isn't in the right place.

### CODE REVIEW

**Comment by rhatdan** [comment]
Oops, Thanks @johrstrom LGTM

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Comment by johrstrom** [comment]
I'm not sure why tests fail, is there something I need to do on my side?  I didn't bother building as it was just a markdown doc update - I assumed no automated test ran on it.

**Comment by rhatdan** [comment]
I am going to force merge, since this is not failing any tests.

**Pull request merged**
