### PR TITLE
[CI:DOCS] Update tutorials to keep up with API changes in storage

### PR DESCRIPTION
**Pull request by nalind**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

In `docs/tutorials`:
* Call `storage.DefaultStoreOptions()` instead of `storage.DefaultStoreOptionsAutoDetectUID()`.
* Mention installing `passt` when installing build-time dependencies.
* Include the registry part of examples that use `node:12-alpine`.
* Use `registry.fedoraproject.org` for Fedora images.
* Mention Fedora 40 instead of 35 in examples.
* Mount an `emptyDir` volume in the OpenShift example, so that it can use overlay for storage
* Use a more recent buildah image as the base in the OpenShift example.
* Use a `ReplicationController` instead of a `DeploymentConfig` in the OpenShift example, because `DeploymentConfig`s are deprecated.

#### How to verify it

Review for grammar, spelling, and punctuation.

#### Which issue(s) this PR fixes:

Fixes https://github.com/containers/buildah/issues/5620

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by nalind** [comment]
/retitle Update tutorials to keep up with API changes in storage

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM and nice cleanups, TYVM!

**Pull request merged**
