### PR TITLE
Throw errors when using bogus --network flags

### PR DESCRIPTION
**Pull request by rhatdan**
Currently if you give a bogus --network flag,
buildah just ignores it and continues on.

This change will throw proper errors.

Add tests to make sure it works correctly.

Also remove some stuttering to clean up error messages.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### What type of PR is this?

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test 
> /kind feature
> /kind flake
> /kind other

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @vrothberg @TomSweeneyRedHat @giuseppe @ashley-cui @umohnani8 PTAL
@containers/podman-maintainers PTAL

**Comment by TomSweeneyRedHat** [comment]
Does this fix an issue?

**Comment by rhatdan** [comment]
There was an issue about podman build --net=container ... not working, which I can not find.  I did not think that was legal.  And while testing it, I tried --net=container1 and it did not blow up, thus this PR.

--net=container is actually supposed to work, although it is no longer documented.  In previous versions of buildah, it was the equivalent is --net=private.

**Comment by umohnani8** [comment]
code changes LGTM. Looks like a rebase is needed

**Comment by TomSweeneyRedHat** [comment]
LGTM
can you please rebase though, I think this is probably not out of date, but I'd like to be sure.

**Pull request merged**
